-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0001_core.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE events (
    id              TEXT PRIMARY KEY,
    slug            TEXT NOT NULL,
    title           TEXT NOT NULL,
    neg_risk        INTEGER NOT NULL DEFAULT FALSE,
    category        TEXT,
    start_ts        INTEGER,
    end_ts          INTEGER,
    created_ms      INTEGER NOT NULL,
    updated_ms      INTEGER NOT NULL);
CREATE UNIQUE INDEX events_slug_uq ON events (slug);
CREATE TABLE markets (
    id                  TEXT PRIMARY KEY,
    condition_id        TEXT NOT NULL,
    event_id            TEXT REFERENCES events(id),
    question            TEXT NOT NULL,
    slug                TEXT,
    accepting_orders    INTEGER NOT NULL,
    seconds_delay       INTEGER NOT NULL DEFAULT 0,
    enable_order_book   INTEGER NOT NULL DEFAULT TRUE,
    minimum_tick_size   REAL NOT NULL,
    minimum_order_size  REAL NOT NULL DEFAULT 5,
    fee_type            TEXT NOT NULL,
    neg_risk            INTEGER NOT NULL DEFAULT FALSE,
    neg_risk_group_id   TEXT,
    end_ts              INTEGER,
    outcomes_json       TEXT NOT NULL DEFAULT '[]',
    first_seen_ms       INTEGER NOT NULL,
    updated_ms          INTEGER NOT NULL,
    CONSTRAINT market_tick_sane CHECK (minimum_tick_size > 0 AND minimum_tick_size <= 0.1),
    CONSTRAINT market_size_sane CHECK (minimum_order_size > 0)
);
CREATE INDEX markets_event_ix ON markets (event_id);
CREATE TABLE tokens (
    token_id     TEXT PRIMARY KEY,
    market_id    TEXT NOT NULL REFERENCES markets(id),
    outcome      TEXT NOT NULL,
    outcome_index INTEGER NOT NULL DEFAULT 0,
    is_winner    INTEGER,
 UNIQUE (market_id, outcome_index));
CREATE INDEX tokens_market_ix ON tokens (market_id);
CREATE TABLE book_levels (
    market_id           TEXT NOT NULL REFERENCES markets(id),
    side                TEXT NOT NULL CHECK (side IN ('bid','ask')),
    price_micro         INTEGER NOT NULL CHECK (price_micro > 0 AND price_micro < 1000000),
    size_shares_micro   INTEGER NOT NULL CHECK (size_shares_micro >= 0),
    level_count         INTEGER NOT NULL DEFAULT 1,
    updated_ms          INTEGER NOT NULL,
    PRIMARY KEY (market_id, side, price_micro));
CREATE TABLE tape_trades (
    id              INTEGER PRIMARY KEY,
    market_id       TEXT NOT NULL,
    token_id        TEXT NOT NULL,
    side            TEXT NOT NULL CHECK (side IN ('BUY','SELL')),
    price_micro     INTEGER NOT NULL CHECK (price_micro > 0 AND price_micro < 1000000),
    size_shares_micro INTEGER NOT NULL CHECK (size_shares_micro > 0),
    taker_is_maker  INTEGER NOT NULL DEFAULT FALSE,
    exchange_ts     INTEGER NOT NULL,
    ingest_ms       INTEGER NOT NULL,
    raw_json        TEXT NOT NULL);
CREATE INDEX tape_market_time_ix ON tape_trades (market_id, exchange_ts);
CREATE INDEX tape_time_ix        ON tape_trades (exchange_ts);
CREATE TABLE users (
    id              TEXT PRIMARY KEY,
    stonks_address  TEXT,
    created_ms      INTEGER NOT NULL,
    tier            TEXT NOT NULL DEFAULT 'free' CHECK (tier IN ('free','trader','pro','team')),
    entitlement_until_ms INTEGER NOT NULL DEFAULT 0);
CREATE TABLE idempotency_keys (
    user_id         TEXT NOT NULL REFERENCES users(id),
    key             TEXT NOT NULL,
    request_hash    TEXT NOT NULL,
    state           TEXT NOT NULL CHECK (state IN ('in_progress','done')),
    response_json   TEXT,
    order_hash      TEXT,
    created_ms      INTEGER NOT NULL DEFAULT (CAST(strftime('%s','now') AS INTEGER) * 1000),
    PRIMARY KEY (user_id, key));
CREATE TABLE kill_switch_state (
    id              INTEGER PRIMARY KEY,
    engaged         INTEGER NOT NULL,
    reason          TEXT NOT NULL CHECK (length(reason) BETWEEN 4 AND 400),
    changed_by      TEXT NOT NULL,
    at_ms           INTEGER NOT NULL);
