-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0002_money.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE balances (
    user_id         TEXT PRIMARY KEY REFERENCES users(id),
    usdc_available_micro   INTEGER NOT NULL DEFAULT 0 CHECK (usdc_available_micro >= 0),
    usdc_locked_micro      INTEGER NOT NULL DEFAULT 0 CHECK (usdc_locked_micro >= 0),
    version         INTEGER NOT NULL DEFAULT 0,
    reconcile_ms    INTEGER NOT NULL DEFAULT 0,
    CHECK (usdc_available_micro + usdc_locked_micro >= 0)
);
CREATE TABLE order_intents (
    id                  TEXT PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(id),
    market_id           TEXT NOT NULL,
    token_id            TEXT NOT NULL,
    side                TEXT NOT NULL CHECK (side IN ('BUY','SELL')),
    price_micro         INTEGER NOT NULL CHECK (price_micro > 0 AND price_micro < 1000000),
    size_micro          INTEGER NOT NULL CHECK (size_micro > 0),
    notional_micro      INTEGER NOT NULL CHECK (notional_micro >= 0),
    state               TEXT NOT NULL CHECK (state IN ('pending','rejected','queued','submitting',
                                                        'uncertain','submitted','cancelled')),
    risk_code           TEXT,
    risk_latency_ms     REAL,
    idempotency_key     TEXT NOT NULL,
    venue_order_id      TEXT,
    client_order_hash   TEXT,
    created_ms          INTEGER NOT NULL,
    updated_ms          INTEGER NOT NULL DEFAULT 0,
 UNIQUE (user_id, idempotency_key));
CREATE INDEX intents_open_ix  ON order_intents (user_id, state, created_ms)
    WHERE state IN ('pending','queued','submitting','uncertain','submitted');
CREATE TABLE orders (
    id                  TEXT PRIMARY KEY,
    intent_id           TEXT NOT NULL REFERENCES order_intents(id),
    user_id             TEXT NOT NULL REFERENCES users(id),
    token_id            TEXT NOT NULL,
    market_id           TEXT NOT NULL,
    side                TEXT NOT NULL CHECK (side IN ('BUY','SELL')),
    price_micro         INTEGER NOT NULL,
    size_micro          INTEGER NOT NULL,
    size_matched_micro  INTEGER NOT NULL DEFAULT 0 CHECK (size_matched_micro >= 0),
    state               TEXT NOT NULL CHECK (state IN ('live','partial','filled','cancelled','expired','rejected')),
    acknowledged        INTEGER NOT NULL DEFAULT FALSE,
    builder_code        TEXT NOT NULL,
    metadata            TEXT,
    expiration_ts       INTEGER NOT NULL DEFAULT 0,
    placed_ms           INTEGER NOT NULL,
    updated_ms          INTEGER NOT NULL,
    CHECK (size_matched_micro <= size_micro)
);
CREATE INDEX orders_user_state_ix ON orders (user_id, state, placed_ms)
    WHERE state IN ('live','partial');
CREATE INDEX orders_intent_ix     ON orders (intent_id);
CREATE TABLE fills (
    id                  INTEGER PRIMARY KEY,
    order_id            TEXT NOT NULL REFERENCES orders(id),
    trade_id            TEXT,
    taker_order_id      TEXT,
    side                TEXT NOT NULL CHECK (side IN ('BUY','SELL')),
    price_micro         INTEGER NOT NULL CHECK (price_micro > 0 AND price_micro < 1000000),
    size_micro          INTEGER NOT NULL CHECK (size_micro > 0),
    notional_micro      INTEGER NOT NULL,
    fee_micro           INTEGER NOT NULL DEFAULT 0,
    maker               INTEGER NOT NULL,
    exchange_ts         INTEGER NOT NULL,
    ingest_ms           INTEGER NOT NULL,
    source              TEXT NOT NULL CHECK (source IN ('ws','rest_poll','reconcile','on_chain')),
    raw_json            TEXT NOT NULL);
CREATE UNIQUE INDEX fills_dedupe_ix ON fills (order_id, exchange_ts, price_micro, size_micro, maker);
CREATE INDEX fills_order_ix ON fills (order_id);
CREATE TABLE cash_ledger (
    id              INTEGER PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id),
    kind            TEXT NOT NULL CHECK (kind IN ('deposit','withdraw','buy','sell_fill','merge_receipt',
                                                  'resolution_payout','fee','refund','adjust')),
    amount_micro    INTEGER NOT NULL CHECK (amount_micro <> 0),
    ref_table       TEXT NOT NULL,
    ref_id          TEXT NOT NULL,
    created_ms      INTEGER NOT NULL,
    reason          TEXT NOT NULL,
 UNIQUE (ref_table, ref_id, kind, user_id));
CREATE INDEX cash_user_time_ix ON cash_ledger (user_id, created_ms);
CREATE TABLE position_lots (
    id                  INTEGER PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(id),
    token_id            TEXT NOT NULL,
    market_id           TEXT NOT NULL,
    shares_open_micro   INTEGER NOT NULL CHECK (shares_open_micro >= 0),
    basis_micro         INTEGER NOT NULL CHECK (basis_micro >= 0),
    opened_ms           INTEGER NOT NULL,
    source              TEXT NOT NULL CHECK (source IN ('fill','merge','transfer','adjust')),
    CHECK (shares_open_micro = 0 OR basis_micro > 0)
);
CREATE TABLE position_snapshots (
    id                  INTEGER PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(id),
    token_id            TEXT NOT NULL,
    shares_micro        INTEGER NOT NULL CHECK (shares_micro >= 0),
    our_computed_micro  INTEGER NOT NULL,
    delta_micro         INTEGER GENERATED ALWAYS AS (shares_micro - our_computed_micro) STORED,
    source              TEXT NOT NULL CHECK (source IN ('on_chain','data_api','clob')),
    observed_ms         INTEGER NOT NULL);
CREATE TABLE builder_attribution (
    id                  INTEGER PRIMARY KEY,
    order_id            TEXT,
    intent_id           TEXT NOT NULL,
    user_id             TEXT NOT NULL,
    builder_code        TEXT NOT NULL,
    fee_bps_expected    INTEGER NOT NULL,
    fee_micro_expected  INTEGER NOT NULL,
    fee_micro_observed  INTEGER,
    market_id           TEXT NOT NULL,
    token_id            TEXT NOT NULL,
    placed_ms           INTEGER NOT NULL,
    CHECK (fee_bps_expected BETWEEN 0 AND 1000)
);
CREATE INDEX attribution_unreconciled_ix ON builder_attribution (placed_ms)
    WHERE fee_micro_observed IS NULL;
