-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0004_product.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE feature_flags (
    name          TEXT PRIMARY KEY,
    kind          TEXT NOT NULL CHECK (kind IN ('bool','number','string')),
    value_json    TEXT NOT NULL);
CREATE TABLE flag_audit (
    id            INTEGER PRIMARY KEY,
    name          TEXT NOT NULL,
    old_value     TEXT,
    new_value     TEXT NOT NULL,
    changed_by    TEXT NOT NULL,
    reason        TEXT NOT NULL,
    at_ms         INTEGER NOT NULL);
CREATE INDEX flag_audit_name_ix ON flag_audit (name, at_ms);
CREATE TABLE entitlements (
    user_id         TEXT PRIMARY KEY REFERENCES users(id),
    plan            TEXT NOT NULL CHECK (plan IN ('free','trader','pro','team')),
    max_alerts      INTEGER NOT NULL,
    max_watchlists  INTEGER NOT NULL,
    max_automation_rules INTEGER NOT NULL,
    radar_poll_ms   INTEGER NOT NULL,
    api_rpm         INTEGER NOT NULL,
    updated_ms      INTEGER NOT NULL);
CREATE TABLE subscriptions (
    id                  TEXT PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(id),
    provider            TEXT NOT NULL CHECK (provider IN ('stripe','telegram_stars')),
    status              TEXT NOT NULL CHECK (status IN ('active','past_due','cancelled','trialing')),
    current_period_end_ms INTEGER NOT NULL,
    amount_micro        INTEGER NOT NULL CHECK (amount_micro >= 0),
    currency            TEXT NOT NULL,
    provider_event_id   TEXT,
    updated_ms          INTEGER NOT NULL);
CREATE UNIQUE INDEX subs_provider_event_uq ON subscriptions (provider, provider_event_id)
    WHERE provider_event_id IS NOT NULL;
CREATE TABLE alert_rules (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id),
    market_id       TEXT,
    event_id        TEXT,
    kind            TEXT NOT NULL CHECK (kind IN ('price_level','spread_widen','whale_fill','resolve_lead',
                                                  'illiquid_top','new_market','manual')),
    fires_per_window INTEGER NOT NULL DEFAULT 3 CHECK (fires_per_window BETWEEN 1 AND 24),
    window_ms       INTEGER NOT NULL DEFAULT 3600000 CHECK (window_ms >= 60000),
    params_json     TEXT NOT NULL DEFAULT '{}',
    enabled         INTEGER NOT NULL DEFAULT TRUE,
    created_ms      INTEGER NOT NULL,
    CONSTRAINT rule_has_target CHECK (market_id IS NOT NULL OR event_id IS NOT NULL)
);
CREATE TABLE alert_fires (
    id              INTEGER PRIMARY KEY,
    rule_id         TEXT NOT NULL REFERENCES alert_rules(id),
    fired_ms        INTEGER NOT NULL,
    observed_price_micro INTEGER,
    observed_delta_ticks INTEGER,
    delivered       INTEGER NOT NULL DEFAULT FALSE,
    channel         TEXT CHECK (channel IN ('telegram','email','push','webhook','inapp')),
 UNIQUE (rule_id, fired_ms));
CREATE INDEX alert_fires_recent_ix ON alert_fires (rule_id, fired_ms);
CREATE TABLE copy_configs (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id),
    source_user     TEXT NOT NULL,
    mode            TEXT NOT NULL CHECK (mode IN ('mirror','ratio','cap')),
    ratio_bps       INTEGER CHECK (ratio_bps BETWEEN 1 AND 10000),
    max_order_micro INTEGER CHECK (max_order_micro > 0),
    max_daily_micro INTEGER CHECK (max_daily_micro > 0),
    blocked_markets TEXT NOT NULL DEFAULT '[]',
    enabled         INTEGER NOT NULL DEFAULT FALSE,
    created_ms      INTEGER NOT NULL,
    CHECK (max_order_micro IS NOT NULL AND max_daily_micro IS NOT NULL)
);
CREATE TABLE automation_rules (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id),
    kind            TEXT NOT NULL CHECK (kind IN ('take_profit','stop_loss','auto_redeem','scale_out','hedge',
                                                  'entry','exit','cancel','alert')),
    trigger_json    TEXT NOT NULL,
    max_loss_micro  INTEGER NOT NULL DEFAULT 0 CHECK (max_loss_micro >= 0),
    enabled         INTEGER NOT NULL DEFAULT FALSE,
    last_run_ms     INTEGER,
    CONSTRAINT redemption_needs_no_ceiling CHECK (kind = 'auto_redeem' OR max_loss_micro > 0)
);
CREATE TABLE watchlists (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id),
    name            TEXT NOT NULL,
    position        INTEGER NOT NULL DEFAULT 0,
    UNIQUE (user_id));
CREATE TABLE watchlist_items (
    watchlist_id    TEXT NOT NULL REFERENCES watchlists(id),
    market_id       TEXT NOT NULL,
    added_ms        INTEGER NOT NULL,
    PRIMARY KEY (watchlist_id, market_id));
CREATE TABLE referrals (
    code            TEXT PRIMARY KEY,
    owner_user      TEXT NOT NULL REFERENCES users(id),
    share_bps       INTEGER NOT NULL DEFAULT 0 CHECK (share_bps BETWEEN 0 AND 5000),
    created_ms      INTEGER NOT NULL);
CREATE TABLE referral_events (
    id              INTEGER PRIMARY KEY,
    code            TEXT NOT NULL REFERENCES referrals(code),
    referred_user   TEXT NOT NULL,
    fee_micro       INTEGER NOT NULL CHECK (fee_micro >= 0),
    accrual_micro   INTEGER NOT NULL CHECK (accrual_micro >= 0),
    at_ms           INTEGER NOT NULL,
 UNIQUE (code, referred_user, at_ms));
CREATE INDEX referral_accrual_ix ON referral_events (code, at_ms);
CREATE TABLE audit_log (
    id              INTEGER PRIMARY KEY,
    at_ms           INTEGER NOT NULL,
    actor_type      TEXT NOT NULL CHECK (actor_type IN ('user','admin','service','automation')),
    actor_id        TEXT NOT NULL,
    action          TEXT NOT NULL,
    target_table    TEXT,
    target_id       TEXT,
    request_id      TEXT NOT NULL,
    detail_json     TEXT NOT NULL DEFAULT '{}',
    CHECK (substr(trim(detail_json), 1, 1) = '{')
);
CREATE INDEX audit_actor_ix ON audit_log (actor_id, at_ms);
CREATE INDEX audit_action_ix ON audit_log (action, at_ms);
