-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0006_ingest.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE IF NOT EXISTS ingest_cursors (
    source        TEXT PRIMARY KEY,
    cursor_json   TEXT NOT NULL DEFAULT '{}',
    last_event_ms INTEGER NOT NULL DEFAULT 0,
    last_frame_ms INTEGER NOT NULL DEFAULT 0,
    state         TEXT NOT NULL DEFAULT 'ok'
                  CHECK (state IN ('ok','lagging','stale','silent','down')),
    updated_ms    INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS market_meta_versions (
    id            INTEGER PRIMARY KEY,
    market_id     TEXT NOT NULL,
    field         TEXT NOT NULL,
    old_value     TEXT NOT NULL,
    new_value     TEXT NOT NULL,
    seen_ms       INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS market_meta_versions_market_time_idx ON market_meta_versions (market_id, seen_ms);
CREATE TABLE IF NOT EXISTS tape_fills (
    trade_id           INTEGER,
    dedupe_key         TEXT NOT NULL,
    market_id          TEXT NOT NULL,
    token_id           TEXT NOT NULL,
    outcome            TEXT,
    outcome_index      INTEGER,
    wallet             TEXT NOT NULL,
    side               TEXT NOT NULL CHECK (side IN ('BUY','SELL')),
    price_micro        INTEGER NOT NULL CHECK (price_micro > 0 AND price_micro < 1000000),
    size_micro         INTEGER NOT NULL CHECK (size_micro > 0),
    usd_notional_micro INTEGER NOT NULL CHECK (usd_notional_micro >= 0),
    ts_ms              INTEGER NOT NULL,
    ingest_ms          INTEGER NOT NULL,
    source             TEXT NOT NULL CHECK (source IN ('ws','rest')),
    fee_rate_bps       INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (trade_id),
 UNIQUE (dedupe_key)
);
CREATE INDEX IF NOT EXISTS tape_fills_market_time_idx ON tape_fills (market_id, ts_ms);
CREATE INDEX IF NOT EXISTS tape_fills_wallet_time_idx ON tape_fills (wallet, ts_ms);
CREATE INDEX IF NOT EXISTS tape_fills_big_idx ON tape_fills (usd_notional_micro, ts_ms)
    WHERE usd_notional_micro >= 10000000000;
CREATE TABLE IF NOT EXISTS market_rollups (
    market_id        TEXT NOT NULL,
    bucket_ms        INTEGER NOT NULL,
    interval         TEXT NOT NULL CHECK (interval IN ('1m','5m','1h','1d')),
    fills            INTEGER NOT NULL DEFAULT 0 CHECK (fills >= 0),
    volume_micro     INTEGER NOT NULL DEFAULT 0,
    vwap_micro       INTEGER NOT NULL DEFAULT 0,
    max_fill_micro   INTEGER NOT NULL DEFAULT 0,
    median_fill_micro INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (market_id, interval, bucket_ms)
);
CREATE TABLE IF NOT EXISTS wallet_rollups (
    wallet           TEXT NOT NULL,
    day_ms           INTEGER NOT NULL,
    fills            INTEGER NOT NULL DEFAULT 0,
    volume_micro     INTEGER NOT NULL DEFAULT 0,
    markets          INTEGER NOT NULL DEFAULT 0,
    buy_micro        INTEGER NOT NULL DEFAULT 0,
    sell_micro       INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (wallet, day_ms)
);
CREATE TABLE IF NOT EXISTS wallet_labels (
    wallet           TEXT NOT NULL,
    label            TEXT NOT NULL,
    confidence       INTEGER NOT NULL,
    evidence_json    TEXT NOT NULL DEFAULT '{}',
    publishable      INTEGER NOT NULL DEFAULT FALSE,
    first_seen_ms    INTEGER NOT NULL,
    last_seen_ms     INTEGER NOT NULL,
    PRIMARY KEY (wallet, label)
);
CREATE TABLE IF NOT EXISTS wallet_label_history (
    id               INTEGER PRIMARY KEY,
    wallet           TEXT NOT NULL,
    label            TEXT NOT NULL,
    confidence       INTEGER NOT NULL,
    publishable      INTEGER NOT NULL,
    seen_ms          INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS signals (
    id               INTEGER PRIMARY KEY,
    rule_id          TEXT NOT NULL,
    kind             TEXT NOT NULL,
    market_id        TEXT NOT NULL,
    token_id         TEXT NOT NULL DEFAULT '',
    severity         TEXT NOT NULL CHECK (severity IN ('info','notice','urgent')),
    title            TEXT NOT NULL,
    body_json        TEXT NOT NULL DEFAULT '{}',
    dedupe_key       TEXT NOT NULL,
    fired_bucket     INTEGER NOT NULL DEFAULT 0,
    fired_ms         INTEGER NOT NULL,
 UNIQUE (rule_id, dedupe_key, fired_bucket)
);
CREATE TABLE IF NOT EXISTS signal_state (
    rule_id          TEXT NOT NULL,
    dedupe_key       TEXT NOT NULL,
    last_fired_ms    INTEGER NOT NULL,
    PRIMARY KEY (rule_id, dedupe_key)
);
CREATE TABLE IF NOT EXISTS alert_deliveries (
    id               INTEGER PRIMARY KEY,
    signal_id        INTEGER NOT NULL,
    user_id          TEXT NOT NULL,
    channel          TEXT NOT NULL,
    priority         INTEGER NOT NULL DEFAULT 2,
    queued_ms        INTEGER NOT NULL,
    sent_ms          INTEGER,
    status           TEXT NOT NULL DEFAULT 'queued'
                     CHECK (status IN ('queued','sent','dropped_rate_limited','digest_scheduled','failed')),
    reason           TEXT
);
CREATE INDEX IF NOT EXISTS alert_deliveries_pending_idx ON alert_deliveries (priority, queued_ms)
    WHERE status = 'queued';
CREATE INDEX IF NOT EXISTS alert_deliveries_latency_idx ON alert_deliveries (sent_ms - queued_ms, queued_ms)
    WHERE status = 'sent';
CREATE TABLE IF NOT EXISTS alert_rules (
    id               TEXT PRIMARY KEY,
    owner            TEXT NOT NULL,
    kind             TEXT NOT NULL,
    params_json      TEXT NOT NULL DEFAULT '{}',
    market_filter_json TEXT NOT NULL DEFAULT '{}',
    cooldown_s       INTEGER NOT NULL DEFAULT 300,
    severity         TEXT,
    channels_json    TEXT NOT NULL DEFAULT '[]',
    enabled          INTEGER NOT NULL DEFAULT TRUE,
    created_ms       INTEGER NOT NULL,
    updated_ms       INTEGER NOT NULL
);
