-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0007_ingest_market_stats.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE IF NOT EXISTS market_stats (
    condition_id        TEXT PRIMARY KEY,
    volume_24h_micro    INTEGER NOT NULL DEFAULT 0,
    liquidity_micro     INTEGER NOT NULL DEFAULT 0,
    fill_count          INTEGER NOT NULL DEFAULT 0 CHECK (fill_count >= 0),
    last_fill_ms        INTEGER NOT NULL DEFAULT 0,
    last_book_change_ms INTEGER NOT NULL DEFAULT 0,
    resolved_seen_ms    INTEGER NOT NULL DEFAULT 0,
    meta_json           TEXT NOT NULL DEFAULT '{}',
    updated_ms          INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS market_stats_activity_ix ON market_stats (volume_24h_micro, updated_ms);
