-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0008_trading_plane.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

BEGIN;
CREATE TABLE wallets (
    user_id             TEXT PRIMARY KEY REFERENCES users(id),
    provider            TEXT NOT NULL CHECK (provider IN ('turnkey','privy','dynamic','self_hosted')),
    custody             TEXT NOT NULL CHECK (custody IN ('delegated','read_only')),
    address             TEXT,
    proxy_address       TEXT,
    signature_type      INTEGER NOT NULL DEFAULT 3 CHECK (signature_type IN (0,1,2,3)),
    policy_hash         TEXT NOT NULL,
    policy_gap          TEXT,
    state               TEXT NOT NULL CHECK (state IN ('provisioned','funded','trading','suspended','closing')),
    created_ms          INTEGER NOT NULL,
    updated_ms          INTEGER NOT NULL,
    CHECK ((custody = 'delegated') = (signature_type IN (1,2,3)))
);
CREATE TABLE wallet_events (
    id                  INTEGER PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(id),
    event               TEXT NOT NULL,
    detail_json         TEXT NOT NULL DEFAULT '{}',
    actor               TEXT NOT NULL DEFAULT 'user',
    at_ms               INTEGER NOT NULL,
    CHECK (event IN
        ('provisioned','policy_drift','policy_gap','deposit_detected','deposit_credited','deposit_stuck',
         'allowance_granted','allowance_revoked','withdraw_requested','withdraw_sent','withdraw_denied',
         'export_requested','export_completed','suspended','reinstated','closed'))
);
CREATE INDEX wallet_events_user_idx ON wallet_events(user_id, at_ms);
CREATE TABLE allowances (
    user_id             TEXT NOT NULL REFERENCES users(id),
    token               TEXT NOT NULL,
    spender             TEXT NOT NULL,
    amount_micro        INTEGER NOT NULL CHECK (amount_micro BETWEEN 0 AND 9223372036854775807),
    checked_ms          INTEGER NOT NULL,
    PRIMARY KEY (user_id, token, spender));
CREATE TABLE deposits (
    id                  INTEGER PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(id),
    asset               TEXT NOT NULL,
    chain               TEXT NOT NULL,
    amount_micro        INTEGER NOT NULL CHECK (amount_micro > 0),
    tx_hash             TEXT,
    bridge_tx_hash      TEXT,
    credit_key          TEXT NOT NULL UNIQUE,
    status              TEXT NOT NULL,
    confirmations       INTEGER NOT NULL DEFAULT 0,
    attempts            INTEGER NOT NULL DEFAULT 0,
    last_error          TEXT,
    first_seen_ms       INTEGER NOT NULL,
    resolved_ms         INTEGER,
    CHECK (status = 'credited' OR resolved_ms IS NULL),
    CHECK (status IN
        ('detecting','confirming','bridging','crediting','credited','stuck','failed'))
);
CREATE INDEX deposits_user_idx ON deposits(user_id, first_seen_ms);
CREATE TABLE withdrawals (
    id                  INTEGER PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(id),
    asset               TEXT NOT NULL,
    chain               TEXT NOT NULL,
    amount_micro        INTEGER NOT NULL CHECK (amount_micro > 0),
    dest_address        TEXT NOT NULL,
    typed_amount        TEXT NOT NULL,
    typed_address       TEXT NOT NULL,
    allowlist_hit       INTEGER NOT NULL DEFAULT FALSE,
    cooldown_ok         INTEGER NOT NULL DEFAULT FALSE,
    notified_email      INTEGER NOT NULL DEFAULT FALSE,
    notified_telegram   INTEGER NOT NULL DEFAULT FALSE,
    password_verified   INTEGER NOT NULL DEFAULT FALSE,
    status              TEXT NOT NULL,
    deny_code           TEXT,
    tx_hash             TEXT,
    idempotency_key     TEXT NOT NULL UNIQUE,
    requested_ms        INTEGER NOT NULL,
    completed_ms        INTEGER,
    CHECK (status NOT IN ('submitted','confirmed') OR (notified_email AND notified_telegram)),
    CHECK (status IN
        ('awaiting_confirmation','queued','submitted','confirmed','failed','denied'))
);
CREATE INDEX withdrawals_user_idx ON withdrawals(user_id, requested_ms);
CREATE TABLE address_allowlist (
    user_id             TEXT NOT NULL REFERENCES users(id),
    address             TEXT NOT NULL,
    added_ms            INTEGER NOT NULL,
    usable_ms           INTEGER NOT NULL,
    added_by            TEXT NOT NULL DEFAULT 'user',
    note                TEXT,
    PRIMARY KEY (user_id, address));
CREATE TABLE order_lifecycle (
    id                  INTEGER PRIMARY KEY,
    order_id            TEXT NOT NULL,
    intent_id           TEXT NOT NULL,
    user_id             TEXT NOT NULL,
    state               TEXT NOT NULL,
    reason              TEXT NOT NULL DEFAULT '',
    source              TEXT NOT NULL CHECK (source IN ('venue_ws','venue_rest','reconciler','user','system')),
    show_as_working     INTEGER NOT NULL DEFAULT FALSE,
    at_ms               INTEGER NOT NULL,
    CHECK (state IN
        ('draft','preflight','signing','submitted','live','partial','filled','cancelled','rejected',
         'expired','unknown','reconciled'))
);
CREATE INDEX order_lifecycle_intent_idx ON order_lifecycle(intent_id, at_ms);
CREATE TABLE order_directives (
    intent_id           TEXT PRIMARY KEY REFERENCES order_intents(id),
    order_type          TEXT NOT NULL DEFAULT 'GTC' CHECK (order_type IN ('GTC','GTD','FOK','FAK','MARKET')),
    expiration_ts       INTEGER NOT NULL DEFAULT 0,
    builder_bps         INTEGER NOT NULL DEFAULT 0 CHECK (builder_bps BETWEEN 0 AND 1000),
    fee_rate_bps        INTEGER NOT NULL DEFAULT 0 CHECK (fee_rate_bps >= 0),
    audience            TEXT NOT NULL DEFAULT 'user' CHECK (audience IN ('user','automation','copy')),
    rule_id             TEXT NOT NULL DEFAULT '',
    config_id           TEXT NOT NULL DEFAULT '',
    max_slippage_bps    INTEGER NOT NULL DEFAULT 0,
    all_in_limit_micro  INTEGER NOT NULL DEFAULT 0,
    created_ms          INTEGER NOT NULL);
CREATE TABLE order_notifications (
    id                  INTEGER PRIMARY KEY,
    intent_id           TEXT NOT NULL,
    user_id             TEXT NOT NULL,
    event               TEXT NOT NULL,
    channel             TEXT NOT NULL DEFAULT 'in_app' CHECK (channel IN ('in_app','email','telegram')),
    status              TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','sent','failed','dead')),
    priority            INTEGER NOT NULL DEFAULT 0,
    detail_json         TEXT NOT NULL DEFAULT '{}',
    at_ms               INTEGER NOT NULL,
    delivered_ms        INTEGER,
    attempts            INTEGER NOT NULL DEFAULT 0,
    CHECK (event IN
        ('queued','submitted','live','partial_fill','filled','cancelled','rejected','expired','unknown',
         'reconciled','position_closed','alert'))
);
CREATE INDEX order_notifications_open_idx ON order_notifications(status, priority, at_ms);
CREATE TABLE automation_rule_targets (
    rule_id             TEXT NOT NULL,
    market_id           TEXT NOT NULL,
    token_id            TEXT NOT NULL DEFAULT '',
    created_ms          INTEGER NOT NULL,
    PRIMARY KEY (rule_id, market_id));
CREATE TABLE automation_rule_state (
    rule_id             TEXT PRIMARY KEY REFERENCES automation_rules(id),
    paused_reason       TEXT NOT NULL DEFAULT '',
    armed_market_id     TEXT NOT NULL DEFAULT '',
    armed_token_id      TEXT NOT NULL DEFAULT '',
    take_profit_bp      INTEGER,
    stop_loss_bp        INTEGER,
    failure_count       INTEGER NOT NULL DEFAULT 0,
    last_error          TEXT NOT NULL DEFAULT '',
    updated_ms          INTEGER NOT NULL,
    CHECK (take_profit_bp IS NULL OR (take_profit_bp > 0 AND take_profit_bp <= 10000)),
    CHECK (stop_loss_bp IS NULL OR (stop_loss_bp > 0 AND stop_loss_bp <= 10000))
);
CREATE TABLE order_attempts (
    client_order_hash   TEXT PRIMARY KEY,
    intent_id           TEXT NOT NULL,
    user_id             TEXT NOT NULL,
    token_id            TEXT NOT NULL,
    side                TEXT NOT NULL,
    price_micro         INTEGER NOT NULL,
    size_micro          INTEGER NOT NULL,
    order_type          TEXT NOT NULL,
    expiration_ts       INTEGER NOT NULL DEFAULT 0,
    signature_type      INTEGER NOT NULL,
    builder_code        TEXT NOT NULL,
    payload_digest      TEXT NOT NULL,
    signed_ms           INTEGER NOT NULL,
    submitted_ms        INTEGER,
    ack_ms              INTEGER);
CREATE TABLE venue_fees (
    order_id            TEXT PRIMARY KEY,
    intent_id           TEXT NOT NULL,
    fee_rate_bps        INTEGER NOT NULL DEFAULT 0,
    builder_bps         INTEGER NOT NULL DEFAULT 0,
    est_platform_micro  INTEGER NOT NULL DEFAULT 0,
    est_builder_micro   INTEGER NOT NULL DEFAULT 0,
    actual_platform_micro INTEGER,
    actual_builder_micro  INTEGER,
    delta_micro         INTEGER,
    at_ms               INTEGER NOT NULL);
CREATE TABLE reconcile_cursors (
    name                TEXT PRIMARY KEY CHECK (name = 'main'),
    watermark_ms        INTEGER NOT NULL DEFAULT 0,
    in_flight           INTEGER NOT NULL DEFAULT 0,
    last_run_ms         INTEGER NOT NULL DEFAULT 0,
    last_error          TEXT,
    updated_ms          INTEGER NOT NULL);
CREATE TABLE reconcile_actions (
    id                  INTEGER PRIMARY KEY,
    case_name           TEXT NOT NULL,
    intent_id           TEXT NOT NULL DEFAULT '',
    order_id            TEXT NOT NULL DEFAULT '',
    action              TEXT NOT NULL,
    dedupe_key          TEXT NOT NULL UNIQUE,
    at_ms               INTEGER NOT NULL);
CREATE TABLE reconcile_open (
    dedupe_key          TEXT PRIMARY KEY,
    case_name           TEXT NOT NULL,
    intent_id           TEXT NOT NULL DEFAULT '',
    order_id            TEXT NOT NULL DEFAULT '',
    since_ms            INTEGER NOT NULL,
    note                TEXT NOT NULL DEFAULT '',
    attempts            INTEGER NOT NULL DEFAULT 0,
    escalated_ms        INTEGER,
    CHECK (case_name IN
        ('submitted_unacked','no_ack','orphan','lagging_fill','closing_market','ghost_order',
         'ambiguous_settlement','cancelled_race'))
);
CREATE INDEX reconcile_open_age_idx ON reconcile_open(since_ms);
CREATE TABLE risk_blocklists (
    market_id           TEXT PRIMARY KEY,
    reason              TEXT NOT NULL,
    source              TEXT NOT NULL CHECK (source IN ('uma_dispute','manual','auto_insider')),
    added_by            TEXT NOT NULL,
    added_ms            INTEGER NOT NULL,
    expires_ms          INTEGER);
CREATE TABLE loss_halts (
    user_id             TEXT PRIMARY KEY REFERENCES users(id),
    threshold_micro     INTEGER NOT NULL,
    realized_micro      INTEGER NOT NULL,
    tripped_ms          INTEGER NOT NULL,
    acknowledged_ms     INTEGER,
    acknowledged_by     TEXT);
CREATE TABLE rate_counters (
    key                 TEXT NOT NULL,
    bucket_ms           INTEGER NOT NULL,
    count               INTEGER NOT NULL DEFAULT 0,
    updated_ms          INTEGER NOT NULL,
    PRIMARY KEY (key, bucket_ms));
CREATE TABLE kill_switch_drills (
    id                  INTEGER PRIMARY KEY,
    started_ms          INTEGER NOT NULL,
    t_zero_ms           INTEGER NOT NULL,
    observed_ms         INTEGER NOT NULL,
    propagation_ms      INTEGER,
    verdict             TEXT NOT NULL CHECK (verdict IN ('pass','fail')),
    budget_ms           INTEGER NOT NULL,
    artifact            TEXT);
CREATE TABLE copy_config_policy (
    config_id             TEXT PRIMARY KEY REFERENCES copy_configs(id),
    max_entry_deviation_bps INTEGER NOT NULL DEFAULT 150 CHECK (max_entry_deviation_bps BETWEEN 0 AND 2000),
    min_interval_ms       INTEGER NOT NULL DEFAULT 0 CHECK (min_interval_ms >= 0),
    take_profit_bp        INTEGER CHECK (take_profit_bp IS NULL OR take_profit_bp > 0),
    stop_loss_bp          INTEGER CHECK (stop_loss_bp IS NULL OR stop_loss_bp > 0),
    min_seconds_to_resolution INTEGER NOT NULL DEFAULT 900 CHECK (min_seconds_to_resolution >= 0),
    copy_up_to_side       INTEGER NOT NULL DEFAULT FALSE,
    max_price_micro       INTEGER CHECK (max_price_micro IS NULL OR (max_price_micro > 0 AND max_price_micro < 1000000)),
    hop_depth             INTEGER NOT NULL DEFAULT 1 CHECK (hop_depth BETWEEN 1 AND 1),
    paused_reason         TEXT,
    updated_ms            INTEGER NOT NULL);
CREATE TABLE copy_events (
    id                  INTEGER PRIMARY KEY,
    copier_id           TEXT NOT NULL,
    source_user_id      TEXT NOT NULL,
    source_intent_id    TEXT NOT NULL DEFAULT '',
    intent_id           TEXT NOT NULL DEFAULT '',
    action              TEXT NOT NULL,
    reason              TEXT NOT NULL DEFAULT '',
    deviation_bps       INTEGER NOT NULL DEFAULT 0,
    at_ms               INTEGER NOT NULL,
    CHECK (action IN
        ('copied','skipped','tp_filled','sl_filled','paused','resumed','source_stopped','insider_flagged',
         'rate_limited'))
);
CREATE INDEX copy_events_copier_idx ON copy_events(copier_id, at_ms);
CREATE TABLE copy_source_stats (
    source_user_id      TEXT NOT NULL,
    window_days         INTEGER NOT NULL,
    closed_trades       INTEGER NOT NULL DEFAULT 0,
    win_rate_bp         INTEGER NOT NULL DEFAULT 0,
    realized_pnl_micro  INTEGER NOT NULL DEFAULT 0,
    fees_micro          INTEGER NOT NULL DEFAULT 0,
    net_after_fees_micro INTEGER NOT NULL DEFAULT 0,
    max_drawdown_micro  INTEGER NOT NULL DEFAULT 0,
    longest_losing_streak INTEGER NOT NULL DEFAULT 0,
    avg_latency_ms      INTEGER NOT NULL DEFAULT 0,
    updated_ms          INTEGER NOT NULL,
    PRIMARY KEY (source_user_id, window_days));
CREATE TABLE copy_economics (
    source_user_id      TEXT PRIMARY KEY REFERENCES users(id),
    copier_count        INTEGER NOT NULL DEFAULT 0,
    copier_volume_micro INTEGER NOT NULL DEFAULT 0,
    fees_micro          INTEGER NOT NULL DEFAULT 0,
    builder_fees_micro  INTEGER NOT NULL DEFAULT 0,
    copier_net_micro    INTEGER NOT NULL DEFAULT 0,
    source_payout_micro INTEGER NOT NULL DEFAULT 0,
    updated_ms          INTEGER NOT NULL);
CREATE TABLE automation_rule_policy (
    rule_id               TEXT PRIMARY KEY REFERENCES automation_rules(id),
    trigger_json          TEXT NOT NULL DEFAULT '{}',
    actions_json          TEXT NOT NULL DEFAULT '[]',
    dry_run_completed_ms  INTEGER,
    max_per_day           INTEGER NOT NULL DEFAULT 24 CHECK (max_per_day BETWEEN 1 AND 288),
    min_interval_ms       INTEGER NOT NULL DEFAULT 60000 CHECK (min_interval_ms >= 1000),
    human_priority_ms     INTEGER NOT NULL DEFAULT 120000,
    last_fire_ms          INTEGER NOT NULL DEFAULT 0,
    updated_ms            INTEGER NOT NULL);
CREATE TABLE automation_runs (
    id                  INTEGER PRIMARY KEY,
    rule_id             TEXT NOT NULL,
    user_id             TEXT NOT NULL,
    mode                TEXT NOT NULL,
    outcome             TEXT NOT NULL,
    reason              TEXT NOT NULL DEFAULT '',
    deny_code           TEXT NOT NULL DEFAULT '',
    intent_id           TEXT NOT NULL DEFAULT '',
    detail_json         TEXT NOT NULL DEFAULT '{}',
    at_ms               INTEGER NOT NULL,
    CHECK (mode IN ('dry_run','live')),
    CHECK (outcome IN ('placed','would_place','skipped','failed'))
);
CREATE INDEX automation_runs_rule_idx ON automation_runs(rule_id, at_ms);
CREATE TABLE builder_attribution_terms (
    attribution_id        INTEGER PRIMARY KEY,
    builder_code          TEXT NOT NULL DEFAULT '',
    fee_bps               INTEGER NOT NULL DEFAULT 0,
    notional_micro        INTEGER NOT NULL DEFAULT 0,
    excluded_reason       TEXT NOT NULL DEFAULT '',
    code_fingerprint      TEXT NOT NULL DEFAULT '',
    recorded_ms           INTEGER NOT NULL);
CREATE TABLE builder_attribution_measures (
    attribution_id        INTEGER PRIMARY KEY,
    order_id              TEXT NOT NULL DEFAULT '',
    chain_measured_micro  INTEGER,
    notional_micro        INTEGER NOT NULL DEFAULT 0,
    source                TEXT NOT NULL CHECK (source IN ('chain_log','builder_trades_api','manual')),
    delta_micro           INTEGER,
    reconciled_ms         INTEGER);
CREATE TABLE builder_revenue_daily (
    day                 TEXT PRIMARY KEY,
    orders              INTEGER NOT NULL DEFAULT 0,
    fills               INTEGER NOT NULL DEFAULT 0,
    volume_micro        INTEGER NOT NULL DEFAULT 0,
    expected_micro      INTEGER NOT NULL DEFAULT 0,
    chain_micro         INTEGER NOT NULL DEFAULT 0,
    platform_fee_micro  INTEGER NOT NULL DEFAULT 0,
    delta_micro         INTEGER NOT NULL DEFAULT 0,
    status              TEXT NOT NULL DEFAULT 'unreconciled'
                          CHECK (status IN ('unreconciled','matched','investigating','settled')),
    updated_ms          INTEGER NOT NULL);
CREATE TABLE chain_events (
    id                  INTEGER PRIMARY KEY,
    source              TEXT NOT NULL,
    kind                TEXT NOT NULL,
    block_number        INTEGER,
    log_index           INTEGER,
    tx_hash             TEXT NOT NULL,
    order_id            TEXT NOT NULL DEFAULT '',
    maker               TEXT NOT NULL DEFAULT '',
    taker               TEXT NOT NULL DEFAULT '',
    token_id            TEXT NOT NULL DEFAULT '',
    matched_micro       INTEGER NOT NULL DEFAULT 0,
    price_micro         INTEGER NOT NULL DEFAULT 0,
    fee_micro           INTEGER NOT NULL DEFAULT 0,
    builder             TEXT NOT NULL DEFAULT '',
    seen_ms             INTEGER NOT NULL,
    UNIQUE (tx_hash, log_index),
    CHECK (source IN ('clob_ws','clob_rest','chain_log'))
);
CREATE TABLE flag_audit_p06 (
    id                  INTEGER PRIMARY KEY,
    key                 TEXT NOT NULL,
    old_value           TEXT,
    new_value           TEXT,
    actor               TEXT NOT NULL,
    reason              TEXT NOT NULL,
    at_ms               INTEGER NOT NULL);
COMMIT;
