-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0009_security.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

BEGIN;
CREATE TABLE user_identities (
    kind            TEXT NOT NULL,
    value           TEXT NOT NULL,
    user_id         TEXT NOT NULL REFERENCES users(id),
    state           TEXT NOT NULL DEFAULT 'claimed',
    claimed_ms      INTEGER NOT NULL,
    verified_ms     INTEGER,
    proof_kind      TEXT NOT NULL DEFAULT '',
    revoked_ms      INTEGER,
    UNIQUE (kind, value),
    CHECK (kind IN ('email','telegram','wallet','handle')),
    CHECK (state IN ('claimed','verified','revoked')),
    CHECK (revoked_ms IS NULL OR revoked_ms >= 0)
);
CREATE INDEX user_identities_user ON user_identities (user_id, kind);
CREATE TABLE password_credentials (
    user_id         TEXT PRIMARY KEY REFERENCES users(id),
    phc           TEXT NOT NULL,
    kdf           TEXT NOT NULL DEFAULT 'argon2id',
    memory_kib    INTEGER NOT NULL,
    time_cost     INTEGER NOT NULL,
    parallelism   INTEGER NOT NULL,
    set_ms        INTEGER NOT NULL,
    updated_ms    INTEGER NOT NULL,
    gen           INTEGER NOT NULL DEFAULT 1,
    CHECK (kdf IN ('argon2id','argon2i')),
    CHECK (memory_kib >= 19456),
    CHECK (time_cost >= 2),
    CHECK (parallelism >= 1),
    CHECK (gen >= 1)
);
CREATE TABLE auth_sessions (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id),
    kind            TEXT NOT NULL,
    device_label    TEXT NOT NULL DEFAULT '',
    token_hash      TEXT NOT NULL UNIQUE,
    family_id       TEXT NOT NULL,
    issued_ms       INTEGER NOT NULL,
    last_seen_ms    INTEGER NOT NULL,
    expires_ms      INTEGER NOT NULL,
    revoked_ms      INTEGER,
    revoked_reason  TEXT NOT NULL DEFAULT '',
    cred_gen        INTEGER NOT NULL DEFAULT 1,
    ip_hash         TEXT NOT NULL DEFAULT '',
    ua_hash         TEXT NOT NULL DEFAULT '',
    CHECK (kind IN ('web','telegram','mobile','service','break_glass')),
    CHECK (ua_hash IS NULL OR length(ua_hash) <= 1500)
);
CREATE INDEX auth_sessions_user ON auth_sessions (user_id, revoked_ms);
CREATE INDEX auth_sessions_family ON auth_sessions (family_id);
CREATE TABLE refresh_secrets (
    token_hash      TEXT PRIMARY KEY,
    family_id       TEXT NOT NULL,
    user_id         TEXT NOT NULL REFERENCES users(id),
    issued_ms       INTEGER NOT NULL,
    used_ms         INTEGER,
    reused_ms       INTEGER,
    revoked_ms      INTEGER);
CREATE INDEX refresh_secrets_family ON refresh_secrets (family_id);
CREATE TABLE auth_events (
    id              INTEGER PRIMARY KEY,
    user_id         TEXT NOT NULL DEFAULT '',
    kind            TEXT NOT NULL,
    at_ms           INTEGER NOT NULL,
    session_id      TEXT NOT NULL DEFAULT '',
    ip_hash         TEXT NOT NULL DEFAULT '',
    detail_json     TEXT NOT NULL DEFAULT '{}');
CREATE INDEX auth_events_user_time ON auth_events (user_id, at_ms);
CREATE TABLE totp_enrollments (
    user_id         TEXT PRIMARY KEY REFERENCES users(id),
    secret_wrapped  TEXT NOT NULL,
    nonce           TEXT NOT NULL,
    alg             TEXT NOT NULL DEFAULT 'AES-256-GCM',
    digits          INTEGER NOT NULL DEFAULT 6,
    period_s        INTEGER NOT NULL DEFAULT 30,
    enrolled_ms     INTEGER NOT NULL,
    verified_ms     INTEGER,
    kek_version     INTEGER NOT NULL DEFAULT 1,
    tag             TEXT NOT NULL DEFAULT '',
    last_step       INTEGER NOT NULL DEFAULT -1,
    failed_count    INTEGER NOT NULL DEFAULT 0,
    locked_until_ms INTEGER NOT NULL DEFAULT 0,
    CHECK (alg = 'AES-256-GCM'),
    CHECK (digits IN (6,8)),
    CHECK (period_s IN (30,60)),
    CHECK (locked_until_ms IS NULL OR locked_until_ms >= 0)
);
CREATE TABLE withdrawal_addresses (
    id              TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL REFERENCES users(id),
    address         TEXT NOT NULL,
    label           TEXT NOT NULL DEFAULT '',
    added_ms        INTEGER NOT NULL,
    usable_ms       INTEGER NOT NULL,
    confirmed_ms    INTEGER,
    removed_ms      INTEGER,
    added_via       TEXT NOT NULL DEFAULT 'user',
    skip_cooldown   INTEGER NOT NULL DEFAULT FALSE,
    CHECK (added_via IN ('user','support_verified','import')),
    CHECK (skip_cooldown = FALSE)
);
CREATE INDEX withdrawal_addresses_user ON withdrawal_addresses (user_id, removed_ms);
CREATE TABLE telegram_nonces (
    auth_hash       TEXT PRIMARY KEY,
    user_id         TEXT NOT NULL,
    seen_ms         INTEGER NOT NULL,
    used_ms         INTEGER,
    bound_session   TEXT NOT NULL DEFAULT '');
CREATE TABLE kek_versions (
    version         INTEGER PRIMARY KEY,
    created_ms      INTEGER NOT NULL,
    retired_ms      INTEGER,
    provider        TEXT NOT NULL DEFAULT 'env',
    key_id          TEXT NOT NULL DEFAULT '',
    ceremony_by     TEXT NOT NULL DEFAULT '',
    witnesses       TEXT NOT NULL DEFAULT '',
    audit_note      TEXT NOT NULL DEFAULT '',
    CHECK (provider IN ('env','kms','hsm','mock')),
    CHECK (audit_note IS NULL OR length(audit_note) <= 1500)
);
CREATE TABLE key_wraps (
    user_id         TEXT NOT NULL REFERENCES users(id),
    dek_version     INTEGER NOT NULL,
    wrapped_dek     TEXT NOT NULL,
    nonce           TEXT NOT NULL,
    tag             TEXT NOT NULL,
    kek_version     INTEGER NOT NULL REFERENCES kek_versions(version),
    policy_hash     TEXT NOT NULL,
    created_ms      INTEGER NOT NULL,
    rotated_ms      INTEGER,
    revoked_ms      INTEGER,
    messages_wrapped INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, dek_version),
    CHECK (messages_wrapped >= 0)
);
CREATE TABLE revoke_jobs (
    id              TEXT PRIMARY KEY,
    scope           TEXT NOT NULL,
    requested_by    TEXT NOT NULL,
    started_ms      INTEGER NOT NULL,
    finished_ms     INTEGER,
    total           INTEGER NOT NULL,
    revoked         INTEGER NOT NULL DEFAULT 0,
    failed          INTEGER NOT NULL DEFAULT 0,
    batch_size      INTEGER NOT NULL,
    per_call_ms     INTEGER NOT NULL DEFAULT 0,
    detail_json     TEXT NOT NULL DEFAULT '{}',
    CHECK (scope IN ('user','all','node','code')),
    CHECK (total >= 0),
    CHECK (revoked >= 0),
    CHECK (failed >= 0),
    CHECK (batch_size BETWEEN 1 AND 2000),
    CHECK (detail_json IS NOT NULL)
);
CREATE TABLE route_auth_levels (
    operation       TEXT PRIMARY KEY,
    level           TEXT NOT NULL,
    object_check    TEXT NOT NULL DEFAULT '',
    note            TEXT NOT NULL DEFAULT '',
    CHECK (level IN ('public','user','user-owns-resource','admin','service')),
    CHECK (note IS NULL OR length(note) <= 1500)
);
CREATE TABLE wash_findings (
    id              INTEGER PRIMARY KEY,
    user_id         TEXT NOT NULL,
    builder_code    TEXT NOT NULL DEFAULT '',
    score_bps       INTEGER NOT NULL,
    factors_json    TEXT NOT NULL,
    window_start_ms INTEGER NOT NULL,
    window_end_ms   INTEGER NOT NULL,
    volume_micro    INTEGER NOT NULL DEFAULT 0,
    action          TEXT NOT NULL,
    at_ms           INTEGER NOT NULL,
    decided_by      TEXT NOT NULL DEFAULT 'rule',
    CHECK (score_bps BETWEEN 0 AND 10000),
    CHECK (action IN ('watch','hold_payout','freeze','clear')),
    CHECK (decided_by IS NULL OR length(decided_by) <= 1500)
);
CREATE TABLE broadcast_gates (
    id              INTEGER PRIMARY KEY,
    market_id       TEXT NOT NULL,
    verdict         TEXT NOT NULL,
    reasons_json    TEXT NOT NULL,
    audience        INTEGER NOT NULL DEFAULT 0,
    at_ms           INTEGER NOT NULL,
    gate_version    TEXT NOT NULL DEFAULT 'p07.1',
    CHECK (verdict IN ('broadcast','hold','refused')),
    CHECK (audience >= 0),
    CHECK (gate_version IS NULL OR length(gate_version) <= 1500)
);
CREATE TABLE builder_code_status (
    code            TEXT PRIMARY KEY,
    state           TEXT NOT NULL,
    last_seen_ms    INTEGER NOT NULL,
    changed_ms      INTEGER NOT NULL,
    reject_count    INTEGER NOT NULL DEFAULT 0,
    source          TEXT NOT NULL DEFAULT 'venue_rejection',
    note            TEXT NOT NULL DEFAULT '',
    CHECK (state IN ('active','throttled','disabled','unknown')),
    CHECK (source IN ('venue_rejection','manual','api')),
    CHECK (note IS NULL OR length(note) <= 1500)
);
CREATE TABLE secret_inventory (
    name            TEXT PRIMARY KEY,
    environment     TEXT NOT NULL,
    stored_in       TEXT NOT NULL,
    owner           TEXT NOT NULL,
    rotate_by_ms    INTEGER NOT NULL,
    last_rotated_ms INTEGER NOT NULL DEFAULT 0,
    can_rotate_live INTEGER NOT NULL DEFAULT TRUE,
    note            TEXT NOT NULL DEFAULT '',
    CHECK (environment IN ('dev','staging','prod')),
    CHECK (stored_in IN ('kms','secret_manager','env','provider_console')),
    CHECK (note IS NULL OR length(note) <= 1500)
);
CREATE TABLE backup_restore_tests (
    id              INTEGER PRIMARY KEY,
    kind            TEXT NOT NULL,
    encrypted       INTEGER NOT NULL,
    taken_ms        INTEGER NOT NULL,
    restore_started_ms INTEGER NOT NULL,
    restore_done_ms INTEGER,
    verified_rows   INTEGER NOT NULL DEFAULT 0,
    money_checks_ok INTEGER NOT NULL DEFAULT FALSE,
    tested_by       TEXT NOT NULL DEFAULT '',
    note            TEXT NOT NULL DEFAULT '',
    CHECK (kind IN ('pg_snapshot','sqlite_file','ledger_csv','keystore')),
    CHECK (encrypted IN (0,1)),
    CHECK (note IS NULL OR length(note) <= 1500)
);
CREATE TABLE drill_records (
    id              INTEGER PRIMARY KEY,
    kind            TEXT NOT NULL,
    started_ms      INTEGER NOT NULL,
    finished_ms     INTEGER,
    verdict         TEXT NOT NULL DEFAULT 'incomplete',
    measured_ms     INTEGER NOT NULL DEFAULT 0,
    failed_step     TEXT NOT NULL DEFAULT '',
    participants    TEXT NOT NULL DEFAULT '',
    notes           TEXT NOT NULL DEFAULT '',
    CHECK (kind IN ('key_compromise','phishing_support','pg_failover','channel_poison')),
    CHECK (verdict IN ('pass','fail','incomplete')),
    CHECK (notes IS NULL OR length(notes) <= 1500)
);
CREATE TABLE incident_findings (
    id              INTEGER PRIMARY KEY,
    component       TEXT NOT NULL,
    threat          TEXT NOT NULL,
    actor           TEXT NOT NULL,
    control         TEXT NOT NULL,
    owner           TEXT NOT NULL,
    test_ref        TEXT NOT NULL,
    severity        TEXT NOT NULL,
    likelihood      INTEGER NOT NULL,
    impact_micro    INTEGER NOT NULL DEFAULT 0,
    rank            INTEGER NOT NULL,
    status          TEXT NOT NULL DEFAULT 'open',
    accepted_reason TEXT NOT NULL DEFAULT '',
    note            TEXT NOT NULL DEFAULT '',
    CHECK (severity IN ('critical','high','medium','low')),
    CHECK (likelihood BETWEEN 1 AND 5),
    CHECK (rank >= 1),
    CHECK (status IN ('open','mitigated','accepted')),
    CHECK (note IS NULL OR length(note) <= 1500)
);
CREATE UNIQUE INDEX incident_findings_rank ON incident_findings (rank);
COMMIT;
