-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0010_market_surfaces.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE IF NOT EXISTS market_meta (
    market_id           TEXT PRIMARY KEY REFERENCES markets(id),
    category            TEXT,
    resolution_source   TEXT,
    resolution_criteria TEXT,
    image_url           TEXT,
    updated_ms          INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS market_activity (
    market_id           TEXT PRIMARY KEY REFERENCES markets(id),
    open_interest_micro INTEGER NOT NULL DEFAULT 0,
    volume_7d_micro     INTEGER NOT NULL DEFAULT 0,
    volume_30d_micro    INTEGER NOT NULL DEFAULT 0,
    price_24h_ago_micro INTEGER,
    last_price_micro    INTEGER,
    updated_ms          INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS market_activity_volume_ix ON market_activity (volume_7d_micro);
