-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0011_terminal.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE IF NOT EXISTS copy_config_guards (
    config_id                   TEXT PRIMARY KEY REFERENCES copy_configs(id),
    dry_run                     INTEGER NOT NULL DEFAULT TRUE,
    skip_if_moved_cents         INTEGER NOT NULL DEFAULT 2,
    do_not_enter_within_hours   INTEGER NOT NULL DEFAULT 24,
    category_filter             TEXT NOT NULL DEFAULT '',
    min_price_micro             INTEGER,
    max_price_micro             INTEGER,
    take_profit_micro           INTEGER,
    stop_loss_micro             INTEGER,
    live_since_ms               INTEGER,
    updated_ms                  INTEGER NOT NULL,
    CHECK (skip_if_moved_cents BETWEEN 0 AND 50),
    CHECK (do_not_enter_within_hours BETWEEN 0 AND 168),
    CHECK (min_price_micro  IS NULL OR (min_price_micro BETWEEN 1 AND 999999)),
    CHECK (max_price_micro  IS NULL OR (max_price_micro BETWEEN 1 AND 999999))
);
CREATE TABLE IF NOT EXISTS copy_dry_runs (
    id                  INTEGER PRIMARY KEY,
    config_id           TEXT NOT NULL REFERENCES copy_configs(id),
    copier_id           TEXT NOT NULL DEFAULT '',
    source_user_id      TEXT NOT NULL DEFAULT '',
    source_intent_id    TEXT NOT NULL DEFAULT '',
    market_id           TEXT NOT NULL DEFAULT '',
    would_action        TEXT NOT NULL,
    would_size_micro    INTEGER NOT NULL DEFAULT 0,
    would_price_micro   INTEGER NOT NULL DEFAULT 0,
    source_price_micro  INTEGER NOT NULL DEFAULT 0,
    deviation_bps       INTEGER NOT NULL DEFAULT 0,
    reason              TEXT NOT NULL DEFAULT '',
    at_ms               INTEGER NOT NULL,
    CHECK (would_action IN ('enter', 'exit', 'skip'))
);
CREATE INDEX IF NOT EXISTS copy_dry_runs_config_idx ON copy_dry_runs(config_id, at_ms);
CREATE TABLE IF NOT EXISTS trader_metrics (
    wallet_id           TEXT NOT NULL,
    window_key          TEXT NOT NULL,
    fills               INTEGER NOT NULL DEFAULT 0,
    resolved_markets    INTEGER NOT NULL DEFAULT 0,
    wins                INTEGER NOT NULL DEFAULT 0,
    win_rate_bps        INTEGER,
    sample_gate         INTEGER NOT NULL DEFAULT 20,
    volume_micro        INTEGER NOT NULL DEFAULT 0,
    realised_micro      INTEGER NOT NULL DEFAULT 0,
    unrealised_micro    INTEGER NOT NULL DEFAULT 0,
    best_micro          INTEGER NOT NULL DEFAULT 0,
    worst_micro         INTEGER NOT NULL DEFAULT 0,
    max_drawdown_micro  INTEGER NOT NULL DEFAULT 0,
    avg_hold_ms         INTEGER NOT NULL DEFAULT 0,
    median_hold_ms      INTEGER NOT NULL DEFAULT 0,
    open_fills          INTEGER NOT NULL DEFAULT 0,
    matched_positions   INTEGER NOT NULL DEFAULT 0,
    distinct_markets    INTEGER NOT NULL DEFAULT 0,
    computed_ms         INTEGER NOT NULL,
    PRIMARY KEY (wallet_id, window_key),
    CHECK (win_rate_bps IS NULL OR resolved_markets >= sample_gate),
    CHECK (max_drawdown_micro >= 0)
);
CREATE TABLE IF NOT EXISTS trader_metric_snapshots (
    id                  INTEGER PRIMARY KEY,
    wallet_id           TEXT NOT NULL,
    window_key          TEXT NOT NULL,
    resolved_markets    INTEGER NOT NULL,
    wins                INTEGER NOT NULL,
    win_rate_bps        INTEGER,
    realised_micro      INTEGER NOT NULL,
    max_drawdown_micro  INTEGER NOT NULL,
    at_ms               INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS trader_metric_snapshots_wallet_idx ON trader_metric_snapshots(wallet_id, at_ms);
CREATE TABLE IF NOT EXISTS trader_metric_series (
    id                  INTEGER PRIMARY KEY,
    wallet_id           TEXT NOT NULL,
    window_key          TEXT NOT NULL,
    ts_ms               INTEGER NOT NULL,
    cum_micro           INTEGER NOT NULL,
    peak_micro          INTEGER NOT NULL,
    drawdown_micro      INTEGER NOT NULL,
    open_positions      INTEGER NOT NULL DEFAULT 0,
    CHECK (drawdown_micro = peak_micro - cum_micro),
    CHECK (drawdown_micro >= 0)
);
CREATE INDEX IF NOT EXISTS trader_metric_series_key_idx ON trader_metric_series(wallet_id, window_key, ts_ms);
CREATE TABLE IF NOT EXISTS whale_views (
    id                  TEXT PRIMARY KEY,
    user_id             TEXT NOT NULL REFERENCES users(id),
    name                TEXT NOT NULL,
    filters_json        TEXT NOT NULL DEFAULT '{}',
    channel             TEXT NOT NULL DEFAULT 'telegram',
    severity            TEXT NOT NULL DEFAULT 'notice' CHECK (severity IN ('info','notice','urgent')),
    scope               TEXT NOT NULL DEFAULT 'global' CHECK (scope IN ('global','market')),
    market_id           TEXT,
    rule_id             TEXT,
    created_ms          INTEGER NOT NULL,
    CHECK ((scope = 'market') = (market_id IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS whale_views_user_idx ON whale_views(user_id, created_ms);
CREATE TABLE IF NOT EXISTS wallet_pseudonyms (
    wallet_id           TEXT PRIMARY KEY,
    anon_id             TEXT NOT NULL,
    first_seen_ms       INTEGER NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS wallet_pseudonyms_anon_idx ON wallet_pseudonyms(anon_id);
