-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0012_notifications.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE automation_rule_labels (
    rule_id             TEXT PRIMARY KEY REFERENCES automation_rules(id),
    name                TEXT NOT NULL DEFAULT '',
    updated_ms          INTEGER NOT NULL,
    CHECK (length(name) <= 80)
);
CREATE TABLE notification_settings (
    user_id             TEXT PRIMARY KEY REFERENCES users(id),
    quiet_start_min     INTEGER NOT NULL DEFAULT -1,
    quiet_end_min       INTEGER NOT NULL DEFAULT -1,
    tz_offset_min       INTEGER NOT NULL DEFAULT 0,
    digest_mode         TEXT NOT NULL DEFAULT 'off' CHECK (digest_mode IN ('off','hourly','daily')),
    digest_at_min       INTEGER NOT NULL DEFAULT 480,
    default_channel     TEXT NOT NULL DEFAULT 'telegram'
                        CHECK (default_channel IN ('telegram','email','webhook')),
    updated_ms          INTEGER NOT NULL,
    CHECK ((quiet_start_min = -1 AND quiet_end_min = -1)
           OR (quiet_start_min BETWEEN 0 AND 1439 AND quiet_end_min BETWEEN 0 AND 1439)),
    CHECK (tz_offset_min BETWEEN -840 AND 840),
    CHECK (digest_at_min BETWEEN 0 AND 1439)
);
