-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0013_leaderboard.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE leaderboard_snapshots (
    board           TEXT NOT NULL,
    window_key      TEXT NOT NULL,
    wallet          TEXT NOT NULL,
    rank            INTEGER NOT NULL CHECK (rank >= 1),
    score_bps       INTEGER NOT NULL,
    settled         INTEGER NOT NULL DEFAULT 0 CHECK (settled >= 0),
    drawdown_micro  INTEGER NOT NULL DEFAULT 0 CHECK (drawdown_micro >= 0),
    computed_ms     INTEGER NOT NULL,
    PRIMARY KEY (board, window_key, wallet, computed_ms));
CREATE INDEX leaderboard_snapshots_wallet_ix ON leaderboard_snapshots (wallet, board, computed_ms);
CREATE INDEX leaderboard_snapshots_board_ix ON leaderboard_snapshots (board, window_key, computed_ms);
CREATE TABLE wallet_integrity (
    wallet                  TEXT PRIMARY KEY,
    state                   TEXT NOT NULL CHECK (state IN ('ranked', 'provisional', 'blew_up', 'excluded', 'review')),
    reasons_json            TEXT NOT NULL DEFAULT '{}',
    washed_micro            INTEGER NOT NULL DEFAULT 0 CHECK (washed_micro >= 0),
    verified_micro          INTEGER NOT NULL DEFAULT 0 CHECK (verified_micro >= 0),
    best_trade_share_bps    INTEGER NOT NULL DEFAULT 0 CHECK (best_trade_share_bps BETWEEN 0 AND 10000),
    derived_from            TEXT NOT NULL DEFAULT '',
    provisional_until_ms    INTEGER,
    computed_ms             INTEGER NOT NULL);
CREATE TABLE leaderboard_exclusions (
    id          INTEGER PRIMARY KEY,
    wallet      TEXT NOT NULL,
    board       TEXT NOT NULL DEFAULT '',
    action      TEXT NOT NULL CHECK (action IN ('exclude', 'include', 'flag', 'clear')),
    reason      TEXT NOT NULL,
    actor       TEXT NOT NULL,
    at_ms       INTEGER NOT NULL);
CREATE INDEX leaderboard_exclusions_wallet_ix ON leaderboard_exclusions (wallet, at_ms);
CREATE TABLE leaderboard_runs (
    board           TEXT NOT NULL,
    window_key      TEXT NOT NULL,
    bucket_hour     INTEGER NOT NULL,
    ranked          INTEGER NOT NULL DEFAULT 0 CHECK (ranked >= 0),
    unranked        INTEGER NOT NULL DEFAULT 0 CHECK (unranked >= 0),
    blew_up         INTEGER NOT NULL DEFAULT 0 CHECK (blew_up >= 0),
    duration_ms     INTEGER NOT NULL DEFAULT 0 CHECK (duration_ms >= 0),
    computed_ms     INTEGER NOT NULL,
    PRIMARY KEY (board, window_key, bucket_hour));
