-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0014_follows.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE IF NOT EXISTS trader_follows (
    user_id     TEXT NOT NULL REFERENCES users (id),
    anon_wallet TEXT NOT NULL,
    label       TEXT NOT NULL DEFAULT '',
    created_ms  INTEGER NOT NULL,
    PRIMARY KEY (user_id, anon_wallet)
);
CREATE INDEX trader_follows_user_ix ON trader_follows (user_id, created_ms);
CREATE INDEX trader_follows_wallet_ix ON trader_follows (anon_wallet, created_ms);
