-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0015_leaderboard_identity.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE IF NOT EXISTS leaderboard_identity (
    user_id    TEXT PRIMARY KEY REFERENCES users (id),
    state      TEXT NOT NULL CHECK (state IN ('private', 'listed')),
    handle     TEXT NOT NULL DEFAULT '',
    listed_ms  INTEGER,
    updated_ms INTEGER NOT NULL,
    CHECK (state = 'listed' OR listed_ms IS NULL)
);
CREATE INDEX leaderboard_identity_listed_ix ON leaderboard_identity (state, user_id);
