-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0016_referrals.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

DROP TABLE IF EXISTS referral_events;
DROP TABLE IF EXISTS referrals;
CREATE TABLE IF NOT EXISTS referral_links (
    user_id     TEXT NOT NULL REFERENCES users (id),
    code        TEXT PRIMARY KEY,
    token       TEXT NOT NULL,
    kind        TEXT NOT NULL DEFAULT 'link',
    state       TEXT NOT NULL DEFAULT 'active',
    created_ms  INTEGER NOT NULL,
    retired_ms  INTEGER,
    CHECK (kind IN ('link','short')),
    CHECK (state IN ('active','retired')),
    CHECK (retired_ms IS NULL OR retired_ms >= created_ms),
    CHECK (kind <> 'short' OR length(code) BETWEEN 4 AND 16)
);
CREATE UNIQUE INDEX referral_links_token_ix ON referral_links (token)
    WHERE kind = 'link';
CREATE UNIQUE INDEX referral_links_one_short_ix ON referral_links (user_id)
    WHERE kind = 'short' AND state = 'active';
CREATE UNIQUE INDEX referral_links_one_link_ix ON referral_links (user_id)
    WHERE kind = 'link' AND state = 'active';
CREATE TABLE IF NOT EXISTS referral_clicks (
    id          INTEGER PRIMARY KEY,
    referrer    TEXT NOT NULL,
    code        TEXT NOT NULL DEFAULT '',
    token       TEXT NOT NULL DEFAULT '',
    device_hash TEXT NOT NULL DEFAULT '',
    ip_hash     TEXT NOT NULL DEFAULT '',
    landing     TEXT NOT NULL DEFAULT '',
    at_ms       INTEGER NOT NULL
);
CREATE INDEX referral_clicks_referrer_ix ON referral_clicks (referrer, at_ms);
CREATE INDEX referral_clicks_token_ix ON referral_clicks (token, at_ms);
CREATE TABLE IF NOT EXISTS referral_signals (
    user_id     TEXT NOT NULL REFERENCES users (id),
    kind        TEXT NOT NULL,
    hash        TEXT NOT NULL,
    first_ms    INTEGER NOT NULL,
    last_ms     INTEGER NOT NULL,
    PRIMARY KEY (user_id, kind, hash),
    CHECK (kind IN ('device','ip','funding')),
    CHECK (hash LIKE '_\_%' ESCAPE '\'),
    CHECK (last_ms >= first_ms)
);
CREATE INDEX referral_signals_hash_ix ON referral_signals (kind, hash);
CREATE TABLE IF NOT EXISTS referral_attributions (
    referee        TEXT PRIMARY KEY REFERENCES users (id),
    referrer       TEXT NOT NULL REFERENCES users (id),
    code           TEXT NOT NULL DEFAULT '',
    token          TEXT NOT NULL DEFAULT '',
    state          TEXT NOT NULL DEFAULT 'pending',
    reason         TEXT NOT NULL DEFAULT '',
    signed_up_ms   INTEGER NOT NULL,
    qualify_order  TEXT NOT NULL DEFAULT '',
    qualify_ms     INTEGER NOT NULL DEFAULT 0,
    notional_micro INTEGER NOT NULL DEFAULT 0,
    term_ends_ms   INTEGER NOT NULL DEFAULT 0,
    builder_code   TEXT NOT NULL DEFAULT '',
    decided_ms     INTEGER NOT NULL DEFAULT 0,
    CHECK (state IN ('pending','qualified','review','refused','expired','clawed_back')),
    CHECK (state <> 'qualified' OR qualify_ms > 0),
    CHECK (referee <> referrer),
    CHECK (qualify_ms = 0 OR qualify_ms >= signed_up_ms)
);
CREATE INDEX referral_attributions_referrer_ix ON referral_attributions (referrer, state, signed_up_ms);
CREATE INDEX referral_attributions_term_ix ON referral_attributions (state, term_ends_ms);
CREATE TABLE IF NOT EXISTS referral_accruals (
    id                  INTEGER PRIMARY KEY,
    referrer            TEXT NOT NULL REFERENCES users (id),
    referee             TEXT NOT NULL REFERENCES users (id),
    day                 TEXT NOT NULL,
    fee_observed_micro  INTEGER NOT NULL CHECK (fee_observed_micro >= 0),
    share_bps           INTEGER NOT NULL CHECK (share_bps BETWEEN 0 AND 10000),
    share_micro         INTEGER NOT NULL CHECK (share_micro > 0),
    created_ms          INTEGER NOT NULL,
 UNIQUE (referrer, referee, day),
    CHECK (share_micro <= fee_observed_micro)
);
CREATE INDEX referral_accruals_referrer_ix ON referral_accruals (referrer, created_ms);
CREATE TABLE IF NOT EXISTS referral_reviews (
    id            INTEGER PRIMARY KEY,
    kind          TEXT NOT NULL,
    subject       TEXT NOT NULL,
    referee       TEXT NOT NULL DEFAULT '',
    state         TEXT NOT NULL DEFAULT 'open',
    findings_json TEXT NOT NULL DEFAULT '[]',
    decision      TEXT NOT NULL DEFAULT '',
    actor         TEXT NOT NULL DEFAULT '',
    opened_ms     INTEGER NOT NULL,
    decided_ms    INTEGER NOT NULL DEFAULT 0,
    CHECK (kind IN ('velocity','shared_device_or_ip','duplicate_funding','self_referral',
                    'payout_threshold','clawback','manual')),
    CHECK (state IN ('open','cleared','actioned')),
    CHECK (decided_ms = 0 OR decided_ms >= opened_ms)
);
CREATE INDEX referral_reviews_open_ix ON referral_reviews (state, opened_ms);
CREATE INDEX referral_reviews_subject_ix ON referral_reviews (subject, opened_ms);
CREATE TABLE IF NOT EXISTS referral_payouts (
    id            INTEGER PRIMARY KEY,
    referrer      TEXT NOT NULL REFERENCES users (id),
    period        TEXT NOT NULL,
    amount_micro  INTEGER NOT NULL CHECK (amount_micro > 0),
    method        TEXT NOT NULL DEFAULT 'usdc',
    status        TEXT NOT NULL DEFAULT 'pending',
    tax_form      TEXT NOT NULL DEFAULT '',
    tax_reported  INTEGER NOT NULL DEFAULT FALSE,
    tx_ref        TEXT NOT NULL DEFAULT '',
    approved_ms   INTEGER NOT NULL DEFAULT 0,
    sent_ms       INTEGER NOT NULL DEFAULT 0,
    created_ms    INTEGER NOT NULL,
 UNIQUE (referrer, period),
    CHECK (method IN ('usdc','bank','credit')),
    CHECK (status IN ('pending','approved','sent','failed','clawed_back')),
    CHECK (status NOT IN ('approved','sent') OR tax_form <> '')
);
CREATE INDEX referral_payouts_referrer_ix ON referral_payouts (referrer, period);
CREATE INDEX referral_payouts_status_ix ON referral_payouts (status, created_ms);
