-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0017_public_pages.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE IF NOT EXISTS public_page_hits (
    kind            TEXT NOT NULL,
    subject_hash    TEXT NOT NULL,
    window_start_ms INTEGER NOT NULL,
    hits            INTEGER NOT NULL DEFAULT 0,
    locked_until_ms INTEGER NOT NULL DEFAULT 0,
    last_ms         INTEGER NOT NULL
);
CREATE UNIQUE INDEX public_page_hits_uq ON public_page_hits (kind, subject_hash, window_start_ms);
CREATE INDEX public_page_hits_subject_ix ON public_page_hits (subject_hash, last_ms);
CREATE TABLE IF NOT EXISTS public_page_blocks (
    subject_hash TEXT NOT NULL,
    scope        TEXT NOT NULL DEFAULT 'all',
    reason       TEXT NOT NULL,
    kind         TEXT NOT NULL DEFAULT 'manual',
    until_ms     INTEGER NOT NULL,
    created_ms   INTEGER NOT NULL,
    created_by   TEXT NOT NULL DEFAULT '',
    PRIMARY KEY (subject_hash, scope)
);
CREATE INDEX public_page_blocks_until_ix ON public_page_blocks (until_ms);
CREATE TABLE IF NOT EXISTS public_page_budget (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,
    note        TEXT NOT NULL DEFAULT '',
    updated_ms  INTEGER NOT NULL
);
