-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0019_telegram.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE IF NOT EXISTS telegram_updates (
    update_id   INTEGER PRIMARY KEY,
    kind        TEXT NOT NULL DEFAULT 'unknown',
    chat_id     TEXT NOT NULL DEFAULT '',
    user_id     TEXT NOT NULL DEFAULT '',
    command     TEXT NOT NULL DEFAULT '',
    state       TEXT NOT NULL DEFAULT 'claimed',
    note        TEXT NOT NULL DEFAULT '',
    runs        INTEGER NOT NULL DEFAULT 0,
    first_ms    INTEGER NOT NULL,
    done_ms     INTEGER NOT NULL DEFAULT 0,
    CHECK (state IN ('claimed','done','failed'))
);
CREATE INDEX IF NOT EXISTS telegram_updates_chat_ix ON telegram_updates (chat_id, first_ms);
CREATE TABLE IF NOT EXISTS telegram_sessions (
    chat_id      TEXT PRIMARY KEY,
    step         TEXT NOT NULL DEFAULT 'idle',
    payload_json TEXT NOT NULL DEFAULT '{}',
    message_id   INTEGER NOT NULL DEFAULT 0,
    started_ms   INTEGER NOT NULL,
    updated_ms   INTEGER NOT NULL,
    expires_ms   INTEGER NOT NULL,
    version      INTEGER NOT NULL DEFAULT 1,
    CHECK (step IN ('idle','choose_market','choose_side','choose_size','confirm_order','custom_size',
                    'withdraw_amount','withdraw_address','export_disclaimer','export_confirm','alert_rule',
                    'copy_config','verify_handle')),
    CHECK (expires_ms > started_ms),
    CHECK (updated_ms >= started_ms)
);
CREATE INDEX IF NOT EXISTS telegram_sessions_expiry_ix ON telegram_sessions (expires_ms);
CREATE TABLE IF NOT EXISTS telegram_outbox (
    id             INTEGER PRIMARY KEY,
    chat_id        TEXT NOT NULL,
    chat_type      TEXT NOT NULL DEFAULT 'private',
    priority       INTEGER NOT NULL,
    method         TEXT NOT NULL DEFAULT 'sendMessage',
    text           TEXT NOT NULL DEFAULT '',
    keyboard_json  TEXT NOT NULL DEFAULT '',
    edit_message_id INTEGER NOT NULL DEFAULT 0,
    state          TEXT NOT NULL DEFAULT 'queued',
    attempts       INTEGER NOT NULL DEFAULT 0,
    claim_ms       INTEGER NOT NULL DEFAULT 0,
    created_ms     INTEGER NOT NULL,
    due_ms         INTEGER NOT NULL DEFAULT 0,
    sent_ms        INTEGER NOT NULL DEFAULT 0,
    note           TEXT NOT NULL DEFAULT '',
    CHECK (state IN ('queued','sending','sent','failed')),
    CHECK (priority BETWEEN 1 AND 999),
    CHECK (attempts >= 0)
);
CREATE INDEX IF NOT EXISTS telegram_outbox_ready_ix ON telegram_outbox (state, due_ms, priority, id);
CREATE TABLE IF NOT EXISTS telegram_commands (
    id          INTEGER PRIMARY KEY,
    at_ms       INTEGER NOT NULL,
    chat_id     TEXT NOT NULL,
    chat_type   TEXT NOT NULL DEFAULT 'private',
    user_id     TEXT NOT NULL DEFAULT '',
    command     TEXT NOT NULL DEFAULT '',
    action      TEXT NOT NULL DEFAULT '',
    ok          INTEGER NOT NULL DEFAULT 1,
    dur_ms      INTEGER NOT NULL DEFAULT 0,
    update_id   INTEGER NOT NULL DEFAULT 0,
    CHECK (ok IN (0, 1)),
    CHECK (dur_ms >= 0)
);
CREATE INDEX IF NOT EXISTS telegram_commands_day_ix ON telegram_commands (at_ms, chat_id);
CREATE INDEX IF NOT EXISTS telegram_commands_chat_ix ON telegram_commands (chat_id, at_ms);
CREATE TABLE IF NOT EXISTS telegram_broadcasts (
    id          INTEGER PRIMARY KEY,
    channel     TEXT NOT NULL,
    kind        TEXT NOT NULL DEFAULT '',
    market_id   TEXT NOT NULL DEFAULT '',
    message_id  INTEGER NOT NULL DEFAULT 0,
    quality     INTEGER NOT NULL DEFAULT 0,
    fired_ms    INTEGER NOT NULL,
    CHECK (quality BETWEEN 0 AND 100)
);
CREATE INDEX IF NOT EXISTS telegram_broadcasts_cadence_ix ON telegram_broadcasts (channel, fired_ms);
