-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0021_executor_state.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE IF NOT EXISTS executor_state (
    id              INTEGER PRIMARY KEY CHECK (id = 1),
    at_ms           INTEGER NOT NULL,
    pid             TEXT NOT NULL DEFAULT '',
    version         TEXT NOT NULL DEFAULT '',
    ticks           INTEGER NOT NULL DEFAULT 0,
    note            TEXT NOT NULL DEFAULT '',
    CHECK (note IS NULL OR length(note) <= 400)
);
