-- GENERATED by tools/build-sqlite-migrations.py from db/migrations/0022_payment_events.sql -- do not edit.
-- Dev/CI portable subset; Postgres remains the product database.

CREATE TABLE IF NOT EXISTS payment_events (
    event_id    TEXT PRIMARY KEY,
    provider    TEXT NOT NULL CHECK (provider IN ('stripe', 'telegram_stars')),
    event_type  TEXT NOT NULL DEFAULT '',
    received_ms INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS payment_events_provider_ix ON payment_events (provider, received_ms);
