-- GENERATED by tools/build-sqlite-migrations.py -- do not edit.
-- append-only enforcement for the portable subset, mirroring 0005_triggers.sql.

CREATE TRIGGER append_only_cash_ledger_update BEFORE UPDATE ON cash_ledger BEGIN SELECT RAISE(ABORT,'append-only table: cash_ledger is not updatable'); END;

CREATE TRIGGER append_only_cash_ledger_delete BEFORE DELETE ON cash_ledger BEGIN SELECT RAISE(ABORT,'append-only table: cash_ledger is not deletable'); END;

CREATE TRIGGER append_only_fills_update BEFORE UPDATE ON fills BEGIN SELECT RAISE(ABORT,'append-only table: fills is not updatable'); END;

CREATE TRIGGER append_only_fills_delete BEFORE DELETE ON fills BEGIN SELECT RAISE(ABORT,'append-only table: fills is not deletable'); END;

CREATE TRIGGER append_only_tape_trades_update BEFORE UPDATE ON tape_trades BEGIN SELECT RAISE(ABORT,'append-only table: tape_trades is not updatable'); END;

CREATE TRIGGER append_only_tape_trades_delete BEFORE DELETE ON tape_trades BEGIN SELECT RAISE(ABORT,'append-only table: tape_trades is not deletable'); END;

CREATE TRIGGER append_only_builder_attribution_update BEFORE UPDATE ON builder_attribution BEGIN SELECT RAISE(ABORT,'append-only table: builder_attribution is not updatable'); END;

CREATE TRIGGER append_only_builder_attribution_delete BEFORE DELETE ON builder_attribution BEGIN SELECT RAISE(ABORT,'append-only table: builder_attribution is not deletable'); END;

CREATE TRIGGER append_only_position_snapshots_update BEFORE UPDATE ON position_snapshots BEGIN SELECT RAISE(ABORT,'append-only table: position_snapshots is not updatable'); END;

CREATE TRIGGER append_only_position_snapshots_delete BEFORE DELETE ON position_snapshots BEGIN SELECT RAISE(ABORT,'append-only table: position_snapshots is not deletable'); END;

CREATE TRIGGER append_only_audit_log_update BEFORE UPDATE ON audit_log BEGIN SELECT RAISE(ABORT,'append-only table: audit_log is not updatable'); END;

CREATE TRIGGER append_only_audit_log_delete BEFORE DELETE ON audit_log BEGIN SELECT RAISE(ABORT,'append-only table: audit_log is not deletable'); END;

CREATE TRIGGER append_only_flag_audit_update BEFORE UPDATE ON flag_audit BEGIN SELECT RAISE(ABORT,'append-only table: flag_audit is not updatable'); END;

CREATE TRIGGER append_only_flag_audit_delete BEFORE DELETE ON flag_audit BEGIN SELECT RAISE(ABORT,'append-only table: flag_audit is not deletable'); END;

CREATE TRIGGER append_only_alert_fires_update BEFORE UPDATE ON alert_fires BEGIN SELECT RAISE(ABORT,'append-only table: alert_fires is not updatable'); END;

CREATE TRIGGER append_only_alert_fires_delete BEFORE DELETE ON alert_fires BEGIN SELECT RAISE(ABORT,'append-only table: alert_fires is not deletable'); END;

CREATE TRIGGER append_only_kill_switch_state_update BEFORE UPDATE ON kill_switch_state BEGIN SELECT RAISE(ABORT,'append-only table: kill_switch_state is not updatable'); END;

CREATE TRIGGER append_only_kill_switch_state_delete BEFORE DELETE ON kill_switch_state BEGIN SELECT RAISE(ABORT,'append-only table: kill_switch_state is not deletable'); END;

CREATE TRIGGER append_only_referral_events_update BEFORE UPDATE ON referral_events BEGIN SELECT RAISE(ABORT,'append-only table: referral_events is not updatable'); END;

CREATE TRIGGER append_only_referral_events_delete BEFORE DELETE ON referral_events BEGIN SELECT RAISE(ABORT,'append-only table: referral_events is not deletable'); END;
