/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Never touches Postgres/Redis. A pod that is not READY must not also be declared DEAD, or the fleet restart-storms during an upstream outage.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Reports the database and whether the flag store is still on BOOT DEFAULTS. The second one matters: a
         *     pod serving traffic on defaults during an incident looks healthy and behaves like a different
         *     product (it has no kill-switch flag, no rate caps, no staged features).
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{market_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Market header (one request, cached; never re-fetched on tape events) */
        get: operations["getMarket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{market_id}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Order-book ladder, aggregate by price level
         * @description Served from the ingest service's materialised snapshot, never proxied to the venue per request: one user must
         *     not be able to spend the shared rate budget (P04 rule 2). `bids` and `asks` are BOTH best-first, so
         *     the ladder's depth bar can render without re-sorting. A market with no book returns 404 rather than
         *     two empty arrays — an empty array would render as "no liquidity", which is a different claim.
         */
        get: operations["getBook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{market_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trade-derived candles for the price chart
         * @description Candles from OUR fills, not the venue's `/prices-history`: the venue's series samples mid-price on its
         *     own schedule and is Cloudflare-cached (measured in P01), so it is a different object with the same
         *     name. Consequences are stated rather than implied - a bucket with no fills is a GAP with `trades: 0`,
         *     not a flat candle, and `sampled` says when the 20k-fill read cap was reached.
         *
         *     The server builds 1m, 5m, 15m and 1h. 6h and 1d are derived by the client by bucketing the 1h
         *     candles, and both lists are served so a client feature-detects instead of trusting a changelog.
         */
        get: operations["getMarketHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{market_id}/holders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Wallets we have seen trade this market, with published labels only
         * @description Provenance is `tape`: these are the wallets in OUR fill log, so a whale that traded before ingest
         *     started is invisible and a wallet that only posted unfilled orders never appears. Not the venue's
         *     holder list, and the rail says which one it is. Addresses are pseudonymised exactly as in `/v1/tape`
         *     (sha256 with a local prefix), and `insider_suspect` filters out at the join because it is not a
         *     publishable label.
         */
        get: operations["getMarketHolders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One negRisk event, every market under it, and the invariant they must satisfy
         * @description The 128-row table's data source. Two statements, and the difference matters:
         *
         *       * `probabilitySum`/`deviation`/`tolerance` are the INVARIANT. For a negRisk event the YES prices
         *         partition one dollar, so the sum must be near 1 - near, because each price is only known to a
         *         tick and the sum of N quotes is only known to N ticks, which is exactly `tolerance`.
         *       * `buyAllCost`/`sellAllProceeds`/`opportunity` are the TRADABLE statement, computed from executable
         *         levels rather than mids: buying one of every outcome costs the sum of the best asks, selling one
         *         of every outcome returns the sum of the best bids. `opportunity` is null unless one of those
         *         crosses a dollar by more than a tick, because a screen that shouts at every 1-tick deviation
         *         teaches its reader to ignore it.
         *
         *     A market with only one side has no mid; it is marked `summable: false` and excluded from the sum
         *     instead of borrowing its last trade price, which would put a stale number into a live invariant.
         */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets/{market_id}/fills": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The durable fill log the ingest writes (deduplicated, labelled, no addresses)
         * @description Separate from `/v1/tape` on purpose. `/v1/tape` answers from `tape_trades` (the P04 table the tape widget
         *     and the risk gate were built against); this answers from `tape_fills`, the log P05's ingest writes with
         *     `UNIQUE (dedupe_key)` — the rows the volume rollups, the whale percentile and the leaderboard are computed
         *     from. Without this read the durable tape is a table nobody serves.
         *
         *     `since` is exclusive and is the VENUE's millisecond clock, exactly as in `/v1/tape`: mixing the venue's
         *     clock with our ingest cursor produces either a duplicate or a hole, and a hole in a fill log reads to a
         *     user as a suppressed trade.
         */
        get: operations["getMarketFills"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tape": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent fills (REST backfill only; the live tape is WebSocket)
         * @description `/trades` at the venue is Cloudflare-cached, so REST can never be the live tape (measured in P01:
         *     14.7-33.3 fills/sec arrive over `wss://ws-subscriptions-clob.polymarket.com/ws/market`). This
         *     endpoint exists for the first paint and for replay after a gap; `since` is exclusive.
         */
        get: operations["getTape"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/markets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Market/event list (cursor-paginated; Gamma caps at 100 per page)
         * @description Cursor, never offset: `limit=5000` and `tag_slug` are IGNORED by Gamma (measured in P01), so a page
         *     size above 100 silently returns 100 and an offset walk over a changing list repeats and skips
         *     markets. Cursor pagination is what makes "30k markets backfilled" a bounded job.
         */
        get: operations["listMarkets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Place an order through the risk gate (202 = queued, not accepted)
         * @description The only mutating endpoint in P04. Sequence (docs/P04 §D5): validate → risk gate → idempotency begin
         *     → sign → POST once → record. The gate runs BEFORE signing; nothing is signed that has not passed it.
         *     A replay of the same key returns the stored answer verbatim, including this 202 body.
         */
        post: operations["placeOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/orders/intents/{intent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll one intent
         * @description Scoped to the caller: another user's id yields 404, not 403, so the endpoint cannot be used to probe
         *     which intent ids exist. `uncertain` is a legitimate, permanent-looking state — the executor refuses
         *     to re-POST an order whose response was lost, and says so, rather than risk a duplicate.
         */
        get: operations["getIntent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/kill-switch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Engage or disengage the trading kill switch
         * @description Append-only history (one row per change; the current state is the newest row). A reason of 4-400
         *     characters is mandatory in the schema, not in a code comment, because a switch pulled without a reason
         *     is unreviewable. Cancelling is always permitted while engaged; placing is not — there is no endpoint
         *     that submits an order while the switch is on.
         */
        post: operations["killSwitch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a password for a short session and a single-use refresh token
         * @description Argon2id, with the parameters read back out of the stored hash: a credential minted under a weaker setting is re-hashed on a successful login, so the upgrade happens while we hold the plaintext. A wrong identifier and a wrong password return the same body, for the same time, because a login form that says "no such account" is a user-enumeration API. Ten failures in fifteen minutes closes the door on the account; the per-IP budget lives in the ingest rate limiter, where a spray actually hurts.
         */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token for a new pair (reuse of a spent token kills the family)
         * @description The refresh token is single-use. Presenting a spent token is not a retry, it is the signature of a thief who has a copy of it, and the response is to revoke the whole family: the attacker's token and the victim's new one, plus an `auth_events` row the alarm reads. The token itself is never stored, only its SHA-256, so a read of this table cannot mint a session.
         */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End this session
         * @description Ends the calling session only. "Everywhere" is a separate, explicit action with its own row, because the two are different intents and the wrong one is unrecoverable in the middle of an incident.
         */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * This account's sessions, with no token material in any field
         * @description The per-device list: kind, label, issued, last seen, and the reason it was revoked. Rows are safe to render because the tokens behind them are hashes. This is the screen a user is sent to when an alert says "a new device signed in", which is why it exists before the settings page does.
         */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sessions/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke one of this account's sessions, or all of them
         * @description Object-level authorisation in the WHERE clause: the row is looked up by (id, user), so somebody else's session id is a miss rather than a 403. A session id is a lockout primitive if that comparison is missing, and a body that guesses the shape of a foreign id gets the same answer as one that guesses wrong about a real one.
         */
        post: operations["revokeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/telegram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in from a Telegram Mini App (initData signature, freshness, replay)
         * @description Three checks in this order: the HMAC-SHA256 of the data-check-string under the key `HMAC-SHA256("WebAppData", botToken)`; `auth_date` inside five minutes for a login; then the nonce table, which is what makes a captured payload useless a second time. A malformed token in the environment is a 503, not a permissive fallback — every failure mode here is chosen so that a misconfiguration looks broken rather than open.
         */
        post: operations["authTelegram"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/totp/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate an authenticator secret, show it once, store it wrapped
         * @description The secret is sealed under the same KEK hierarchy as the signing keys and is never cached after the one comparison that needs it. Enrolment is not complete until a code has been *entered*: `verified_ms` stays null, so a hijacked session cannot attach an attacker's authenticator and have it mean anything. Re-enrolment is allowed — a lost phone is a real event — and writes an event the user sees on their next login.
         */
        post: operations["totpEnroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/totp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a 6-digit code (and consume its window)
         * @description RFC 6238 with one step of leeway, a five-try budget per enrolment, and single-use steps: a correct code for a step already accepted is `reused`, not `ok`. The distinction is the difference between "the user mistyped" and "somebody watched the user type it", and the second one needs an event.
         */
        post: operations["totpVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet/withdrawal-addresses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saved destinations, with the hold remaining on each
         * @description Address values are shown short-form in the API and in full only on the screens where the owner is typing them back. `cooldownRemainingMs` is in the payload because the number is the product's promise, and hiding it turns a 24-hour safety hold into an unexplained failure.
         */
        get: operations["listAddresses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet/withdrawal-addresses/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a withdrawal destination (usable after the 24 hour hold, TOTP required)
         * @description The hold starts when the destination is confirmed, not when it was typed, and nothing skips it: the schema column that would allow the skip has a CHECK permitting only `false`, so the temptation is visible in the table. An address already saved by another account is recorded as an event — shared destinations are legitimate (an exchange deposit address) and worth noticing at the same time.
         */
        post: operations["addAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/wallet/withdrawal-addresses/remove": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a saved destination (never while it is inside its hold)
         * @description Removing a destination you cannot yet use is refused, and that refusal is the control: an attacker who adds their own address uses deletion to erase the evidence before the first payout clears. The hold has to outlast the attacker's patience, not the session. A verified second factor is required for the removal itself, for the same reason it is required to add one: the caller deleting a destination is changing where the account's money can go.
         */
        post: operations["removeAddress"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/revoke-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Break-glass: end every session, one statement, two named approvers
         * @description Two distinct approvers and a reason of at least twenty characters, validated by the same function the P06 kill drill uses. The single most dangerous account in this product is the one that can log everybody out, because that is what an attacker does to stop you from seeing what they did — so the path exists, it is loud, and every use of it is an event.
         */
        post: operations["adminRevokeSessions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description price in (0,1) USDC as a dot-decimal string with at most 6 decimals. Strings are not a stylistic
         *     choice: the venue's own client types these as float (py-clob-client-v2 1.1.0), and we refuse to let
         *     a JSON number become the input to a money path.
         * @example 0.5
         * @example 0.999
         * @example 0.001
         */
        Price: string;
        Levels: {
            price: components["schemas"]["Price"];
            shares: string;
            /** @description cumulative size from the top of this side, as a decimal string. Served rather than left to the client because deriving it means summing floats in a render loop, and the depth bar is a fraction of the largest cumulative figure on either side. P09 added it to the payload and to this schema in the same change: a field the ladder cannot work without is not optional documentation. */
            cumShares: string;
            /** @description how many venue orders sit at this price; 1 is a real answer and must render */
            levels: number;
        }[];
        Fill: {
            price: components["schemas"]["Price"];
            size: string;
            /** @enum {string} */
            side: "BUY" | "SELL";
            maker?: boolean;
            /** @description venue clock, ms */
            exchangeTs: number;
            /** @description our clock, ms; freshness uses THIS, never exchangeTs */
            ingestMs?: number;
        };
        /** @description one row of `tape_fills`. `price`/`shares`/`notional` are decimal strings off integers, so the response cannot smuggle a float into a client that renders it as a money figure. */
        DurableFill: {
            price: components["schemas"]["Price"];
            shares: string;
            notional: string;
            /** @enum {string} */
            side: "BUY" | "SELL";
            /** @description the venue's own label; '' when the row has none, never a guess */
            outcome?: string;
            /** @description ms, the venue's clock — the only clock a cursor may use */
            venueTs: number;
            /** @description ms, our clock — the only clock freshness may use */
            ingestMs: number;
            /** @enum {string} */
            source: "rest" | "ws";
            /** @description sha256 of the counterparty address with a local prefix, 10 hex chars. The address itself is never returned: a public tape that echoes every trader's wallet is an address book of our users' counterparties, and `raw_json` is withheld for the same reason. */
            anonWallet: string;
            labels?: components["schemas"]["Labels"];
        };
        /** @description the fields the risk gate reads (P01 D5.2) plus what the header renders. acceptingOrders, secondsDelay, minimumOrderSize and enableOrderBook are required because a missing one is a different order-management UI, not a default. */
        Market: {
            id: string;
            question: string;
            acceptingOrders: boolean;
            secondsDelay: number;
            /**
             * @description canonical text, normalised at the boundary - Postgres NUMERIC and SQLite REAL return this column differently, and the gate compares strings
             * @enum {string}
             */
            minimumTickSize: "0.001" | "0.01";
            minimumOrderSize: string;
            /** @description open taxonomy (6 values seen in P01); no enum on purpose */
            feeType: string;
            enableOrderBook: boolean;
            endDate?: number | null;
            category?: string;
            eventId?: string | null;
            outcomeCount?: number;
            negRisk?: boolean;
            volume24h?: components["schemas"]["Price"];
            liquidity?: components["schemas"]["Price"];
            openInterest?: components["schemas"]["Price"];
            lastPrice?: components["schemas"]["Price"] | null;
            price24hAgo?: components["schemas"]["Price"] | null;
            /** @description signed difference of two prices in micro units, null when our tape does not reach back 24h. Zero would be a claim we do not have the data to make. */
            change24h?: components["schemas"]["Price"] | null;
            /** @description integer micro units; null when one side is missing, which is not a spread of zero */
            spreadMicro?: number | null;
            event?: components["schemas"]["EventSummary"];
            slug?: string;
            eventTitle?: string | null;
            eventSlug?: string | null;
            volume7d?: components["schemas"]["Price"];
            volume30d?: components["schemas"]["Price"];
            /** @description verbatim from the venue, including a `javascript:` URL if a market creator wrote one. It is data here on purpose: the client is what refuses to render it as a link, and a fixture that never reaches the client proves nothing about the client. */
            resolutionSource?: string | null;
            /** @description attacker-influenced text, returned verbatim and rendered as sanitised PLAIN TEXT by the client. Sanitising in the API would hide the fixture that proves the client does not trust it. */
            resolutionCriteria?: string | null;
            /** @description wallets WE have seen trade this market, not the venue's holder list, which does not exist for every market. The rail labels it "seen trading" for that reason. */
            holderCount?: number;
        };
        /** @description published labels only; `insider_suspect` is never publishable, so it cannot appear here */
        Labels: ("whale" | "smart_money" | "new_wallet" | "insider_suspect" | "cluster" | "wash_like")[];
        /** @description one price bucket derived from our fills. A bucket with `trades: 0` does not exist in the array - the gaps are ABSENT rather than flat, because a candle drawn across a gap is a chart inventing prices. */
        Candle: {
            /** @description bucket start */
            t: number;
            o: components["schemas"]["Price"];
            h: components["schemas"]["Price"];
            l: components["schemas"]["Price"];
            c: components["schemas"]["Price"];
            shares: string;
            trades: number;
            notional: components["schemas"]["Price"];
        };
        /** @description what a discovery card needs to summarise an event instead of listing it. The 128-outcome event is the reason this exists: a card that lists 128 rows is unreadable and one that shows the first three is wrong, so the card shows the top three BY 24h VOLUME and says how many it left out. */
        EventSummary: {
            id: string;
            title: string;
            marketCount: number;
            totalVolume24h: components["schemas"]["Price"];
            hiddenCount: number;
            topOutcomes: {
                marketId: string;
                question: string;
                price: components["schemas"]["Price"] | null;
                volume24h: components["schemas"]["Price"];
            }[];
        };
        Event: {
            id: string;
            slug?: string;
            title: string;
            negRisk: boolean;
            category?: string | null;
            endTs?: number | null;
            marketCount: number;
        };
        /** @description one market under the event, i.e. one row of the 128-row table the client virtualises */
        EventOutcome: {
            marketId: string;
            question: string;
            acceptingOrders: boolean;
            /** @enum {string} */
            minimumTickSize: "0.001" | "0.01";
            minimumOrderSize: string;
            price: components["schemas"]["Price"] | null;
            bestBid?: components["schemas"]["Price"] | null;
            bestAsk?: components["schemas"]["Price"] | null;
            volume24h: components["schemas"]["Price"];
            liquidity: components["schemas"]["Price"];
            openInterest?: components["schemas"]["Price"];
            change24h?: components["schemas"]["Price"] | null;
            /** @description false when the market has one side or none, so it has no mid. Excluded from the sum rather than borrowing its last trade price, which would put a stale number into a live invariant. */
            summable: boolean;
        };
        /** @description every read payload carries these three fields */
        Stamped: {
            /** @description ms epoch of the data, not of the response */
            asOf: number;
            /** @description ms epoch after which the client must mark the data stale AND stop offering to trade (design system D5.5: 3s tape/book, 5s price, 120s metadata) */
            staleAfter: number;
            cache: {
                ttlMs: number;
                key?: string | null;
                public: boolean;
                immutable?: boolean;
            };
        };
        Error: {
            /** @description no `detail` field, ever: that is where a Python message would leak. Logs carry the code and the request id instead. */
            error: {
                /** @enum {string} */
                code: "RISK_HALT" | "MARKET_NOT_ACCEPTING" | "NO_ORDER_BOOK" | "STALE_QUOTE" | "BAD_SIDE" | "UNKNOWN_TICK" | "OFF_TICK" | "BAD_MARKET_META" | "BELOW_MIN_SIZE" | "ZERO_SIZE" | "BAD_AMOUNT" | "OVER_ORDER_CAP" | "PRICE_FAR_FROM_MID" | "TOO_MANY_OPEN" | "DAILY_CAP" | "IDEM_CONFLICT" | "IDEM_IN_PROGRESS" | "IDEM_KEY_REQUIRED" | "RISK_UNAVAILABLE" | "SIGNER_UNAVAILABLE" | "BAD_REASON" | "NOT_FOUND" | "VALIDATION" | "INTERNAL" | "UNAUTHENTICATED" | "SESSION_STALE" | "SESSION_REVOKED" | "SESSION_MISMATCH" | "ADMIN_REQUIRED" | "LOGIN_FAILED" | "ACCOUNT_LOCKED" | "TOTP_REQUIRED" | "TOTP_INVALID" | "TOTP_LOCKED" | "ADDRESS_COOLDOWN" | "ADDRESS_LIMIT" | "REMOVE_DURING_COOLDOWN" | "NO_SUCH_RESOURCE" | "REFRESH_UNKNOWN" | "REFRESH_REUSED" | "REFRESH_EXPIRED" | "TELEGRAM_REPLAY" | "TELEGRAM_INVALID" | "SECURITY_ENV_MISSING" | "KEYSTORE_TAMPER" | "BREAK_GLASS_DENIED" | "AUTHZ_UNDECLARED";
                /** @description user-safe by construction */
                message: string;
                retryable: boolean;
                requestId: string;
            };
        };
    };
    responses: {
        /** @description no such resource */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description refused by policy or by the venue feed's state */
        Denied: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description idempotency key reused with a different body, or a market that cannot accept orders */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description request rejected before any money logic ran */
        Validation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description unexpected failure (logged with the request id; the body never says why) */
        Internal: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description 8-128 chars of [A-Za-z0-9_-]. Required on every mutating endpoint; the 400 for its absence is part
         *     of the contract so a client cannot "just try without it" once and conclude it is optional.
         */
        IdempotencyKey: string;
        /**
         * @description dev only (PGM_AUTH_MODE=dev-header). In every other deployment this is a bearer token and the user id
         *     comes from it; a header a client can set is not an authentication mechanism.
         */
        UserId: string;
    };
    requestBodies: never;
    headers: {
        /** @description echoed if sent, generated otherwise; appears on every response including errors */
        xRequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description process answers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ok: true;
                    };
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ready: boolean;
                        problems: ("db_unreachable" | "flags_from_defaults" | "venue_disconnected")[];
                    };
                };
            };
            500: components["responses"]["Internal"];
            /** @description not ready (same body; the status is what the orchestrator reads) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        ready: false;
                        problems: string[];
                    };
                };
            };
        };
    };
    getMarket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description market metadata */
            200: {
                headers: {
                    "x-request-id": components["headers"]["xRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stamped"] & {
                        market: components["schemas"]["Market"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    getBook: {
        parameters: {
            query?: {
                /** @description levels per side; 400 is the design-system ladder cap and is also the hard maximum. The limit is applied to the RAW ladder before aggregation, so a bucket count can be lower than `depth` - the alternative is loading the whole book into memory to count it, which is the cost this endpoint exists to avoid. */
                depth?: number;
                /** @description bucket width for the ladder. A 0.001-tick market has a thousand levels per dollar, so the raw ladder is unreadable; 1c and 5c fold it. Rounding is DIRECTIONAL - a bid rounds down and an ask rounds up - so an aggregated level never shows a price the user could not have got. */
                aggregate?: "raw" | "1c" | "5c";
            };
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description book snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stamped"] & {
                        market: string;
                        bids: components["schemas"]["Levels"];
                        asks: components["schemas"]["Levels"];
                        /** @enum {string} */
                        aggregate: "raw" | "1c" | "5c";
                        aggregateStep?: components["schemas"]["Price"] | null;
                        tickSize?: components["schemas"]["Price"] | null;
                        bestBid?: components["schemas"]["Price"];
                        bestAsk?: components["schemas"]["Price"];
                        midPrice?: components["schemas"]["Price"];
                        /** @description the largest cumulative size on either side, so a depth bar can be a fraction of it without the chart summing the ladder itself */
                        maxCumShares?: string;
                        /** @description metadata arithmetic on integers, never a float price */
                        spreadTicks: number | null;
                        oneSided: null | {
                            /** @enum {string} */
                            side: "asks-only" | "bids-only";
                            /** @description a machine code; the client owns the words */
                            why: string;
                            levels: number;
                            notionalUsdc: components["schemas"]["Price"];
                            bestAsk?: components["schemas"]["Price"];
                            bestBid?: components["schemas"]["Price"];
                        };
                        ageMs: number;
                    };
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
            500: components["responses"]["Internal"];
        };
    };
    getMarketHistory: {
        parameters: {
            query?: {
                interval?: "1m" | "5m" | "15m" | "1h";
                /** @description buckets of history, counted back from now; it bounds the fill read as well as the output */
                limit?: number;
            };
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description candles, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stamped"] & {
                        market: string;
                        interval: string;
                        bucketMs: number;
                        /** @description the oldest bucket boundary the request reaches */
                        fromTs?: number;
                        candles: components["schemas"]["Candle"][];
                        serverIntervals: string[];
                        derivedIntervals: string[];
                        /** @enum {string} */
                        source: "fills";
                        /** @description the read cap was hit; the left edge is not the beginning of the market */
                        sampled?: boolean;
                    };
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
            500: components["responses"]["Internal"];
        };
    };
    getMarketHolders: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description holders by notional, largest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stamped"] & {
                        market: string;
                        /** @enum {string} */
                        provenance: "tape";
                        holderCount: number;
                        holders: {
                            anonWallet: string;
                            notional: components["schemas"]["Price"];
                            fills: number;
                            firstSeenMs?: number;
                            lastSeenMs?: number;
                            /** @description share of the tape's notional */
                            shareBp: number;
                            labels: components["schemas"]["Labels"];
                        }[];
                    };
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
            500: components["responses"]["Internal"];
        };
    };
    getEvent: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the event and its outcomes, biggest 24h volume first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stamped"] & {
                        event: components["schemas"]["Event"];
                        outcomes: components["schemas"]["EventOutcome"][];
                        probabilitySum: components["schemas"]["Price"] | null;
                        deviation: components["schemas"]["Price"] | null;
                        tolerance: components["schemas"]["Price"];
                        withinTolerance: boolean | null;
                        summableCount?: number;
                        buyAllCost?: components["schemas"]["Price"] | null;
                        sellAllProceeds?: components["schemas"]["Price"] | null;
                        opportunity: null | {
                            /** @enum {string} */
                            kind: "buy-all" | "sell-all";
                            edge: components["schemas"]["Price"];
                        };
                    };
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
            500: components["responses"]["Internal"];
        };
    };
    getMarketFills: {
        parameters: {
            query?: {
                /** @description exclusive cursor = venue ts_ms */
                since?: number;
                limit?: number;
            };
            header?: never;
            path: {
                market_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description fills, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stamped"] & {
                        market: string;
                        /** @description what the ingest keys every table on */
                        conditionId: string;
                        rows: components["schemas"]["DurableFill"][];
                        nextCursor: number | null;
                    };
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
            500: components["responses"]["Internal"];
        };
    };
    getTape: {
        parameters: {
            query: {
                marketId: string;
                /** @description exclusive cursor = venue exchange_ts (ms). Never our ingest clock: the venue's order of fills is what a user reads, and mixing clocks makes a gap look like a duplicate. */
                since?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description fills, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stamped"] & {
                        rows: components["schemas"]["Fill"][];
                        nextCursor: number | null;
                    };
                };
            };
            404: components["responses"]["NotFound"];
            422: components["responses"]["Validation"];
            500: components["responses"]["Internal"];
        };
    };
    listMarkets: {
        parameters: {
            query?: {
                /** @description opaque `<sort key>|<id>` from the previous page. It encodes the key the rows were ordered BY, not the row id: paging by id while ordering by end_ts repeats one market and drops another, and a single-page test cannot see it. (This endpoint did exactly that for ten minutes.) */
                cursor?: string | null;
                limit?: number;
                /** @description accepting orders right now */
                live?: boolean;
                sortBy?: "endsSoon" | "newMarket" | "spread" | "volume24h" | "liquidity" | "openInterest" | "move24h";
                /** @description case-folded substring over question, slug and category, matched with instr() rather than LIKE so a user's own % cannot change the meaning of their own search. Three columns, not four: the prompt asks for tags as well, and we do not store tags - a typeahead that searches a column which does not exist is a docstring, not a feature. */
                q?: string;
                /** @description the P09 filter vocabulary. Case-folded, canonicalised server-side, and a value outside the vocabulary is a 422 rather than an empty page, because "no markets match" and "you spelled the category wrong" are different answers. */
                category?: "Politics" | "Sports" | "Crypto" | "Finance" | "Economics" | "Tech" | "Culture" | "Weather" | "Geopolitics" | "Other";
                /** @description micro-USDC over the last 24h, in integer micro units - a float here would be a float in the money path */
                minVolume24h?: number;
                minLiquidity?: number;
                minOpenInterest?: number;
                /** @description only markets whose end is between now and now+N hours. A market that already ended is NOT within the window, which is what stops a dead market leading the default sort. */
                endsWithinHours?: number;
                /** @description only markets first seen in the last N hours */
                newWithinHours?: number;
                negRiskOnly?: boolean;
                /** @description false by default - markets under $1,000 of 24h volume are omitted and counted in `longTail.hiddenCount`. P01 measured a median event at $19,910/day, so the default view is what someone can actually trade and the long tail is one parameter away, never silently dropped. */
                includeLongTail?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description a page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stamped"] & {
                        items: components["schemas"]["Market"][];
                        nextCursor: string | null;
                        /** @enum {string} */
                        sortBy?: "endsSoon" | "newMarket" | "spread" | "volume24h" | "liquidity" | "openInterest" | "move24h";
                        /** @description market counts per category, with every filter applied EXCEPT the category one and without the cursor: a category tab that zeroes the other tabs is a tab nobody can navigate back from */
                        facets?: {
                            [key: string]: number;
                        };
                        categories?: string[];
                        longTail?: {
                            includeLongTail: boolean;
                            thresholdMicro: number;
                            /** @description left out by the filter ABOVE */
                            hiddenCount: number;
                        };
                        /** @description what the server accepts today */
                        sortKeys?: string[];
                        /**
                         * @description the venue's real limit, exposed so a client cannot "optimize" by requesting 5000 and then trusting the count
                         * @constant
                         */
                        pageSizeHardCap: 100;
                    };
                };
            };
            422: components["responses"]["Validation"];
            500: components["responses"]["Internal"];
        };
    };
    placeOrder: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description 8-128 chars of [A-Za-z0-9_-]. Required on every mutating endpoint; the 400 for its absence is part
                 *     of the contract so a client cannot "just try without it" once and conclude it is optional.
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
                /**
                 * @description dev only (PGM_AUTH_MODE=dev-header). In every other deployment this is a bearer token and the user id
                 *     comes from it; a header a client can set is not an authentication mechanism.
                 */
                "X-User-Id"?: components["parameters"]["UserId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    marketId: string;
                    tokenId: string;
                    /**
                     * @description uppercase; the venue is case-sensitive
                     * @enum {string}
                     */
                    side: "BUY" | "SELL";
                    price: components["schemas"]["Price"];
                    /** @description shares as a decimal string; must be >= the market's minimum_order_size (5, measured in P01) and a multiple of the market's tick when multiplied out */
                    size: string;
                };
            };
        };
        responses: {
            /** @description queued for the executor */
            202: {
                headers: {
                    "x-request-id": components["headers"]["xRequestId"];
                    /** @description gate latency, on success AND on denial — the only way to see the gate getting slow */
                    "x-risk-latency-ms"?: string;
                    /** @description how many checks ran before the verdict (denials stop early by design) */
                    "x-risk-checks"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        intentId: string;
                        /** @constant */
                        state: "queued";
                        riskLatencyMs?: number;
                        notionalMicro: number;
                        /** @description the GET target for the intent's terminal state */
                        poll: string;
                        note?: string;
                    };
                };
            };
            /** @description missing or malformed Idempotency-Key (checked before any work) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": {
                     *         "code": "IDEM_KEY_REQUIRED",
                     *         "message": "mutating endpoints require an Idempotency-Key of 8-128 chars [A-Za-z0-9_-]",
                     *         "retryable": false,
                     *         "requestId": "0123456789abcdef"
                     *       }
                     *     }
                     */
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description P07: no session. `POST /v1/orders` is `user`, and the identity comes from the bearer token it carries — a `X-User-Id` header is a development identity that a pod configured with `PGM_REQUIRE_SECURITY_ENV=1` does not accept, and a header that disagrees with a valid session is a 403 `SESSION_MISMATCH`, never a preference for whichever one is easier. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            403: components["responses"]["Denied"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["Validation"];
            /** @description too many open orders; retryable */
            429: {
                headers: {
                    "Retry-After"?: 2;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["Internal"];
            /** @description trading disabled (kill switch, stale feed, no signer, risk service down); retryable */
            503: {
                headers: {
                    "Retry-After"?: 2;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getIntent: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description dev only (PGM_AUTH_MODE=dev-header). In every other deployment this is a bearer token and the user id
                 *     comes from it; a header a client can set is not an authentication mechanism.
                 */
                "X-User-Id"?: components["parameters"]["UserId"];
            };
            path: {
                intent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current intent state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stamped"] & {
                        intentId: string;
                        /** @enum {string} */
                        state: "pending" | "rejected" | "queued" | "submitting" | "uncertain" | "submitted" | "cancelled";
                        riskCode?: string | null;
                        venueOrderId?: string | null;
                    };
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["Internal"];
        };
    };
    killSwitch: {
        parameters: {
            query?: never;
            header?: {
                /** @description absent or empty means 503 SIGNER_UNAVAILABLE rather than a 401, so a misconfigured dev box cannot look like an attack */
                "X-Admin-Token"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    engaged: boolean;
                    reason: string;
                };
            };
        };
        responses: {
            /** @description new state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        engaged: boolean;
                        atMs: number;
                    };
                };
            };
            /** @description two answers, deliberately: VALIDATION when `reason` is absent (shape), BAD_REASON when it is present but outside 4-400 characters (the rule the DB's CHECK enforces). "Your body is wrong" and "say why you pulled the switch" are different advice, and the app used to collapse them. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["Internal"];
            503: components["responses"]["Denied"];
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    identifier: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description see the summary; every field is derived from a row, no token material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no bearer session, or the session ended */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the session is fine; the action needs more */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the body is not the shape this route takes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description too many attempts against this credential */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the global handler answered with the envelope and a request id; nothing in this route may answer outside that envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the security backend is not configured here */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                };
            };
        };
        responses: {
            /** @description see the summary; every field is derived from a row, no token material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no bearer session, or the session ended */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the session is fine; the action needs more */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the body is not the shape this route takes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description too many attempts against this credential */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the global handler answered with the envelope and a request id; nothing in this route may answer outside that envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the security backend is not configured here */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description see the summary; every field is derived from a row, no token material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no bearer session, or the session ended */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the body is not the shape this route takes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the global handler answered with the envelope and a request id; nothing in this route may answer outside that envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description see the summary; every field is derived from a row, no token material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stamped"];
                };
            };
            /** @description no bearer session, or the session ended */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the body is not the shape this route takes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the global handler answered with the envelope and a request id; nothing in this route may answer outside that envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    sessionId: string;
                    everywhere?: boolean;
                };
            };
        };
        responses: {
            /** @description see the summary; every field is derived from a row, no token material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no bearer session, or the session ended */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the body is not the shape this route takes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the global handler answered with the envelope and a request id; nothing in this route may answer outside that envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    authTelegram: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    initData: string;
                };
            };
        };
        responses: {
            /** @description see the summary; every field is derived from a row, no token material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no bearer session, or the session ended */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the session is fine; the action needs more */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the body is not the shape this route takes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description too many attempts against this credential */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the global handler answered with the envelope and a request id; nothing in this route may answer outside that envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the security backend is not configured here */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    totpEnroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description see the summary; every field is derived from a row, no token material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no bearer session, or the session ended */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the session is fine; the action needs more */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the body is not the shape this route takes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description too many attempts against this credential */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the global handler answered with the envelope and a request id; nothing in this route may answer outside that envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the security backend is not configured here */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    totpVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                };
            };
        };
        responses: {
            /** @description see the summary; every field is derived from a row, no token material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no bearer session, or the session ended */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the session is fine; the action needs more */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the body is not the shape this route takes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description too many attempts against this credential */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the global handler answered with the envelope and a request id; nothing in this route may answer outside that envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the security backend is not configured here */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listAddresses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description see the summary; every field is derived from a row, no token material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stamped"];
                };
            };
            /** @description no bearer session, or the session ended */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the body is not the shape this route takes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the global handler answered with the envelope and a request id; nothing in this route may answer outside that envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    addAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    address: string;
                    label?: string;
                    code?: string;
                };
            };
        };
        responses: {
            /** @description see the summary; every field is derived from a row, no token material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no bearer session, or the session ended */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the session is fine; the action needs more */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the destination is inside its 24 hour hold */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the body is not the shape this route takes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description too many attempts against this credential */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the global handler answered with the envelope and a request id; nothing in this route may answer outside that envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the security backend is not configured here */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    removeAddress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    addressId: string;
                    code?: string;
                };
            };
        };
        responses: {
            /** @description see the summary; every field is derived from a row, no token material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description no bearer session, or the session ended */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the session is fine; the action needs more */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the destination is inside its 24 hour hold */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the body is not the shape this route takes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description too many attempts against this credential */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the global handler answered with the envelope and a request id; nothing in this route may answer outside that envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the security backend is not configured here */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    adminRevokeSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                    approvers: string[];
                    /** @enum {string} */
                    scope?: "user" | "all";
                    userId?: string;
                };
            };
        };
        responses: {
            /** @description see the summary; every field is derived from a row, no token material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description the session is fine; the action needs more */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the body is not the shape this route takes */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the global handler answered with the envelope and a request id; nothing in this route may answer outside that envelope */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description the security backend is not configured here */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
