"""P13 D3 — contract tests.

Four contracts, and the failure each one is designed to catch:

  1. **The venue's payloads -> our normalised rows.** `tests/fixtures/p05/` holds the recorded venue payloads and
     `tests/test_ingest.py` replays them, which proves the inputs still parse. It does not prove our *output*
     still carries what the product reads. `tests/fixtures/p13/contracts.json` records the normalised shape
     (keys and types) of each parser, so an upstream rename that our parser tolerates silently — a field that
     stops appearing, a number that becomes a string — fails here.
  2. **Our responses -> the clients.** The same recording covers the read routes the web and the bot consume,
     with each route's status and content type. A rename is a red test instead of a broken screen.
  3. **Our orders -> the venue's struct.** `build_signed_payload` is the only thing the venue ever sees; its
     field set is recorded, and the payload is fed through the mock's own validator.
  4. **Our refusals -> the user.** Every venue code the executor can surface is checked against the API's
     refusal vocabulary, because a code with no sentence is a support ticket with extra steps.

The recorded shapes are re-generated by `tools/build-p13-contract-fixtures.py`; `test_the_recorded_contracts_are_current`
runs its `--check` mode, which is also the CI step, so a rename fails the build even if nobody runs pytest.
"""
from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import unittest
from pathlib import Path

from conftest import ROOT

FIXTURE = ROOT / "tests" / "fixtures" / "p13" / "contracts.json"


def _load_tool(name: str):
    spec = importlib.util.spec_from_file_location(name.replace("-", "_"), ROOT / "tools" / name)
    mod = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = mod
    spec.loader.exec_module(mod)
    return mod


class TestRecordedContracts(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.recorded = json.loads(FIXTURE.read_text())
        cls.tool = _load_tool("build-p13-contract-fixtures.py")
        cls.current = cls.tool.build()

    def test_the_normalised_shape_of_every_recorded_venue_payload_is_unchanged(self):
        rec, cur = self.recorded["normalised"], self.current["normalised"]
        self.assertEqual(sorted(rec), sorted(cur), "a parser was added or removed without re-recording")
        for key in sorted(rec):
            self.assertEqual(rec[key], cur[key],
                             "the normalised shape of %s changed — an upstream rename must fail here" % key)

    def test_the_response_shape_of_every_pinned_route_is_unchanged(self):
        rec, cur = self.recorded["responses"], self.current["responses"]
        self.assertEqual(sorted(rec), sorted(cur))
        for route in sorted(rec):
            self.assertEqual(rec[route]["status"], cur[route]["status"], "status changed for %s" % route)
            self.assertEqual(rec[route]["shape"], cur[route]["shape"],
                             "the response shape of %s changed — the web and the bot read this" % route)
            self.assertEqual(rec[route]["content_type"], cur[route]["content_type"], route)

    def test_the_order_struct_sent_to_the_venue_is_unchanged(self):
        self.assertEqual(self.recorded["venue_payload"], self.current["venue_payload"],
                         "the V2 order struct changed; both the SDK and the venue's validation are downstream")

    def test_the_recorded_contracts_are_current(self):
        """The CI half: the same comparison as a command, so a rename fails the build."""
        r = subprocess.run([sys.executable, str(ROOT / "tools" / "build-p13-contract-fixtures.py"), "--check"],
                           cwd=str(ROOT), capture_output=True, text=True)
        self.assertEqual(0, r.returncode, r.stdout + r.stderr)


class TestOrderStructAgainstTheVenueValidator(unittest.TestCase):
    """Contract 3, the executable half: the mock's validator is the venue's rules in code."""

    def test_the_payload_we_sign_passes_the_venue_validators(self):
        from polygm_core.executor.executor import OrderIntent, build_signed_payload
        spec = importlib.util.spec_from_file_location("mock_clob_contract",
                                                      ROOT / "services" / "executor-mock" / "mock_clob.py")
        mock = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = mock
        spec.loader.exec_module(mock)

        intent = OrderIntent(id="i-contract", user_id="u-contract", token_id="token-contract", side="BUY",
                             price_micro=500_000, size_shares_micro=10_000_000, idempotency_key="k-contract",
                             condition_id="0xcondition", tick_size="0.01")
        payload = build_signed_payload(intent, client_order_hash="0x" + "c" * 64)
        venue = mock.MockClob()
        body = venue.post_order(payload)
        self.assertTrue(body.get("success"), "the venue refused a payload we built: %r" % body)
        # and the validator is capable of saying no — otherwise the line above proved nothing. Two different
        # refusals: a malformed payload (a missing required field is a KeyError inside the mock, which is the
        # same shape as a transport that never answered) and a well-formed one off the tick grid.
        broken = dict(payload)
        broken.pop("token_id")
        with self.assertRaises((KeyError, ValueError)):
            venue.post_order(broken)
        off_grid = dict(payload, price=0.500_123_4)
        self.assertFalse(venue.post_order(off_grid).get("success"), "an off-grid price was accepted")

    def test_every_venue_rejection_the_executor_can_surface_is_a_code_the_product_knows(self):
        """Two vocabularies have to cover the venue, and the test says which one covers what.

        The risk plane (`risk/limits.py` `DENY_CODES`) is the executor's own table — it is what P06 writes into
        `order_intents.risk_code` and what the intent status carries back. The API's `CODES` is what turns a code
        into an HTTP status and a sentence for the bot and the Mini App. A venue rejection that is in neither is
        a code nobody can explain, so the assertion is the union, and then the fallback: for the venue's own
        codes (`TICK`, `BALANCE`, ...) the sentence is the honest generic one.
        """
        from polygm_core.venue import clob_v2
        from polygm_core.risk import limits
        from conftest import import_app
        app = import_app("api-p13-codes")
        codes = set(app.CODES)
        mapped = set(clob_v2.BATCH_ITEM_CODES.values())
        unknown = sorted(c for c in mapped if not (limits.deny_code_known(c) or c in codes))
        self.assertEqual([], unknown, "these venue rejections are in neither vocabulary: %s" % unknown)
        # and the ones without their own sentence must still get a true one from the fallback
        for code in mapped - codes:
            sentence = app._tg_plain_refusal(code)
            self.assertIn("refused", sentence.lower(), "%s has no sentence and no fallback" % code)
        # the specific one D7.7 is about: a disabled builder code is its own sentence, not a generic refusal
        self.assertIn("builder_code_not_allowed", clob_v2.BATCH_ITEM_CODES)
        self.assertEqual("BUILDER_DISABLED", clob_v2.BATCH_ITEM_CODES["builder_code_not_allowed"])
        self.assertIn("BUILDER_DISABLED", codes)
        self.assertIn("builder code", app._tg_plain_refusal("BUILDER_DISABLED"))


class TestRefusalVocabularyIsOneTable(unittest.TestCase):
    """Contract 4. The API, the bot and the Mini App answer refusals from three tables that must agree."""

    def test_the_python_and_typescript_plain_refusal_tables_have_the_same_keys(self):
        from conftest import import_app
        import re
        app = import_app("api-p13-refusals")
        # The two extractions mirror `tools/p12-gate-check.py refusal_vocabulary` on purpose: that gate is the
        # CI half of this contract, and a test that parsed the files differently from the gate would disagree
        # with it about what the tables say.
        py_src = (ROOT / "services" / "api" / "app.py").read_text()
        py_table = py_src.split("def _tg_plain_refusal", 1)[1].split("def ", 1)[0]
        py_keys = set(re.findall(r'^\s{8}"([A-Z][A-Z0-9_]+)":', py_table, re.M))
        self.assertGreater(len(py_keys), 15, "the extraction found almost nothing, so it proves nothing")
        ts = (ROOT / "web" / "src" / "tma" / "trade.ts").read_text()
        ts_fn = ts.split("export function plainRefusal", 1)[1].split("\n}", 1)[0]
        ts_keys = set(re.findall(r"^\s{4}([A-Z][A-Z0-9_]+):", ts_fn, re.M))
        self.assertEqual(py_keys, ts_keys,
                         "the two dictionaries disagree: python-only %s, ts-only %s"
                         % (sorted(py_keys - ts_keys), sorted(ts_keys - py_keys)))
        self.assertTrue(py_keys - {"REFUSED"}, "the fallback key is not a translation")

    def test_every_key_in_the_plain_tables_is_a_code_the_api_can_return(self):
        from conftest import import_app
        import re
        app = import_app("api-p13-refusals-2")
        codes = set(app.CODES) | {"IDEM_KEY_REQUIRED", "TELEGRAM_INVALID", "TELEGRAM_REPLAY", "UPGRADE_REQUIRED"}
        py_src = (ROOT / "services" / "api" / "app.py").read_text()
        py_table = py_src.split("def _tg_plain_refusal", 1)[1].split("def ", 1)[0]
        py_keys = set(re.findall(r'^\s{8}"([A-Z][A-Z0-9_]+)":', py_table, re.M))
        unknown = sorted(py_keys - codes)
        self.assertEqual([], unknown, "these sentences can never be reached: %s" % unknown)


if __name__ == "__main__":
    unittest.main(verbosity=2)
