/**
 * A QR encoder, in the repo, with no dependency.
 *
 * The wallet screen shows a deposit address, and a deposit address is the one thing on that screen a person *scans*
 * rather than types: a clipboard-swap or a transcription typo is a loss with no undo, and the whole allowlist/cooldown
 * apparatus exists because of exactly that class of mistake. So the QR is not decoration — it is the safer input path.
 *
 * It is written here rather than pulled in for three reasons, and each is a rule this repo has already paid for:
 * a dependency in the money path is a supply chain (P13's list is about keys, but the argument is the same); the
 * Mini App is rendered inside a webview with no network, so nothing may be fetched at runtime; and an SVG we build
 * ourselves is testable against a reference encoder, which a black-box dependency is not — `qr.fixtures.json` holds
 * matrices generated by a second implementation, and `qr.test.ts` asserts this module reproduces them cell for cell,
 * including the mask the reference chose.
 *
 * Scope, stated because a partial implementation that pretends to be general is worse than a narrow one that says so:
 * **byte mode, error-correction level M, versions 1-10.** That is 14 to 213 bytes: a 42-character address, an EIP-681
 * URI, or a short bot link. Anything longer throws a typed error the screen turns into a sentence, because a QR that
 * silently truncates a destination is the failure this file exists to prevent.
 *
 * On indexing: the project compiles with `noUncheckedIndexedAccess`, which is the right default for data that arrives
 * from a server and noise for the fixed tables and square matrices below, where every index is bounded by a loop over
 * that same length. The two reads are named instead of asserted ad hoc — `lg`/`al` for the Galois-field tables,
 * `fixedAt`/`darkAt` for the matrix — and the two writes (`set`, `put`) throw rather than silently dropping a module,
 * because a wrong QR is worse than a crash.
 */

/** The alignment-pattern centres per version (ISO/IEC 18004 Table E.1), versions 1-10. */
const ALIGNMENT: readonly (readonly number[])[] = [
  [], [6, 18], [6, 22], [6, 26], [6, 30], [6, 34], [6, 22, 38], [6, 24, 42], [6, 26, 46], [6, 28, 50],
];

/** Block structure at level M: `[totalCodewords, dataCodewords]` per block, versions 1-10. */
const BLOCKS_M: readonly (readonly (readonly number[])[])[] = [
  [[26, 16]],
  [[44, 28]],
  [[70, 44]],
  [[50, 32], [50, 32]],
  [[67, 43], [67, 43]],
  [[43, 27], [43, 27], [43, 27], [43, 27]],
  [[49, 31], [49, 31], [49, 31], [49, 31]],
  [[60, 38], [60, 38], [61, 39], [61, 39]],
  [[58, 36], [58, 36], [58, 36], [59, 37], [59, 37]],
  [[69, 43], [69, 43], [69, 43], [69, 43], [70, 44]],
];

/** Remainder bits after the interleaved codewords, per version. */
const REMAINDER: readonly number[] = [0, 7, 7, 7, 7, 7, 0, 0, 0, 0];

const ECC_M_BITS = 0b00; // the two-bit format field for level M
const MAX_VERSION = 10;

export class QrTooLongError extends Error {
  constructor(public readonly bytes: number, public readonly capacity: number) {
    super(`a QR for ${bytes} bytes needs a version this encoder does not build (capacity ${capacity})`);
    this.name = "QrTooLongError";
  }
}

// --------------------------------------------------------------------------------------- GF(256) arithmetic
const EXP = new Uint8Array(512);
const LOG = new Uint8Array(256);
(() => {
  let x = 1;
  for (let i = 0; i < 255; i += 1) {
    EXP[i] = x;
    LOG[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= 0x11d; // the QR field's prime polynomial
  }
  for (let i = 255; i < 512; i += 1) EXP[i] = EXP[i - 255] ?? 0;
})();

/** The antilog table read — `EXP` covers two field orders, so any log sum is inside it. */
function al(index: number): number {
  return EXP[index] ?? 0;
}

/** The log table read; callers never pass zero. */
function lg(value: number): number {
  return LOG[value] ?? 0;
}

function gmul(a: number, b: number): number {
  if (a === 0 || b === 0) return 0;
  return al(lg(a) + lg(b));
}

/** The Reed-Solomon generator polynomial of `degree`, highest power first, leading coefficient dropped. */
function generator(degree: number): number[] {
  let poly = [1];
  for (let i = 0; i < degree; i += 1) {
    const next = new Array<number>(poly.length + 1).fill(0);
    poly.forEach((coefficient, j) => {
      next[j] = (next[j] ?? 0) ^ coefficient;
      next[j + 1] = (next[j + 1] ?? 0) ^ gmul(coefficient, al(i));
    });
    poly = next;
  }
  return poly;
}

/** The `degree` error-correction codewords for one block, by synthetic division. */
function ecCodewords(data: readonly number[], degree: number): number[] {
  const gen = generator(degree);
  const rem = new Array<number>(degree).fill(0);
  for (const byte of data) {
    const factor = byte ^ (rem[0] ?? 0);
    rem.shift();
    rem.push(0);
    for (let i = 0; i < degree; i += 1) {
      const next = (rem[i] ?? 0) ^ gmul(gen[i + 1] ?? 0, factor);
      rem[i] = next;
    }
  }
  return rem;
}

// ------------------------------------------------------------------------------------------ BCH for the headers
function bch(value: number, poly: number, bits: number): number {
  let v = value << (bits - 1);
  for (let i = 31; i >= bits - 1; i -= 1) if (v >>> i) v ^= poly << (i - (bits - 1));
  return v;
}

function formatCodeword(mask: number): number {
  const data = (ECC_M_BITS << 3) | mask;
  return ((data << 10) | bch(data, 0x537, 11)) ^ 0x5412;
}

function versionCodeword(version: number): number {
  return (version << 12) | bch(version, 0x1f25, 13);
}

// --------------------------------------------------------------------------------------------- the bit stream
class Bits {
  readonly bits: number[] = [];

  push(value: number, length: number): void {
    for (let i = length - 1; i >= 0; i -= 1) this.bits.push((value >>> i) & 1);
  }

  get length(): number {
    return this.bits.length;
  }
}

/** Mode indicator, character count, payload, terminator, pad to the codeword boundary, then the pad codewords. */
function messageCodewords(payload: Uint8Array, version: number, capacity: number): number[] {
  const bits = new Bits();
  bits.push(0b0100, 4);                                   // byte mode
  bits.push(payload.length, version >= 10 ? 16 : 8);      // character count
  for (const byte of payload) bits.push(byte, 8);
  bits.push(0, Math.min(4, capacity * 8 - bits.length));  // terminator, only as long as it fits
  while (bits.length % 8 !== 0) bits.push(0, 1);
  const out: number[] = [];
  for (let i = 0; i < bits.length; i += 8) {
    let byte = 0;
    for (let j = 0; j < 8; j += 1) byte = (byte << 1) | (bits.bits[i + j] ?? 0);
    out.push(byte);
  }
  let pad = 0xec;
  while (out.length < capacity) {
    out.push(pad);
    pad = pad === 0xec ? 0x11 : 0xec;
  }
  return out;
}

/** Data codewords split into blocks, each with its error-correction tail, then interleaved as the spec orders. */
function interleave(codewords: readonly number[], version: number): number[] {
  const structure = BLOCKS_M[version - 1] ?? [];
  const dataBlocks: number[][] = [];
  const ecBlocks: number[][] = [];
  let offset = 0;
  for (const block of structure) {
    const [total = 0, dataCount = 0] = block;
    const data = codewords.slice(offset, offset + dataCount);
    offset += dataCount;
    dataBlocks.push(data);
    ecBlocks.push(ecCodewords(data, total - dataCount));
  }
  const out: number[] = [];
  const maxData = Math.max(0, ...dataBlocks.map((block) => block.length));
  for (let i = 0; i < maxData; i += 1) for (const block of dataBlocks) out.push(...block.slice(i, i + 1));
  const maxEc = Math.max(0, ...ecBlocks.map((block) => block.length));
  for (let i = 0; i < maxEc; i += 1) for (const block of ecBlocks) out.push(...block.slice(i, i + 1));
  return out;
}

// --------------------------------------------------------------------------------------------- the matrix
type Grid = { size: number; fixed: boolean[][]; dark: boolean[][] };

function blank(size: number): Grid {
  return {
    size,
    fixed: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
    dark: Array.from({ length: size }, () => new Array<boolean>(size).fill(false)),
  };
}

/** A read of a matrix cell that is outside the symbol reads as light — which is what the quiet zone is. */
function darkAt(dark: readonly (readonly boolean[])[], row: number, col: number): boolean {
  return dark[row]?.[col] === true;
}

function fixedAt(grid: Grid, row: number, col: number): boolean {
  return grid.fixed[row]?.[col] === true;
}

/** Write a function module. Out of range would mean this file's own arithmetic is wrong, so it throws instead. */
function set(grid: Grid, row: number, col: number, dark: boolean): void {
  const line = grid.dark[row];
  const marks = grid.fixed[row];
  if (line === undefined || marks === undefined) {
    throw new RangeError(`qr: module (${row}, ${col}) is outside a ${grid.size}-module symbol`);
  }
  line[col] = dark;
  marks[col] = true;
}

function drawFunctionPatterns(grid: Grid, version: number): void {
  const { size } = grid;
  // The window is 9x9 because the finder is 7x7 and the separator is the light ring around it: the -1 and 7
  // offsets are the separator, the 0/6 ring is dark, and the core is 3x3 — not 4x4, which is what a loop bound of
  // "2 to 5" quietly draws.
  const finder = (row: number, col: number): void => {
    for (let r = -1; r <= 7; r += 1) {
      for (let c = -1; c <= 7; c += 1) {
        const rr = row + r;
        const cc = col + c;
        if (rr < 0 || cc < 0 || rr >= size || cc >= size) continue;
        const inside = r >= 0 && r <= 6 && c >= 0 && c <= 6; // the 7x7 finder itself; outside it is separator
        const ring = r === 0 || r === 6 || c === 0 || c === 6;
        const core = r >= 2 && r <= 4 && c >= 2 && c <= 4;
        set(grid, rr, cc, inside && (ring || core));
      }
    }
  };
  finder(0, 0);
  finder(0, size - 7);
  finder(size - 7, 0);
  for (let i = 8; i < size - 8; i += 1) {
    set(grid, 6, i, i % 2 === 0); // horizontal timing
    set(grid, i, 6, i % 2 === 0); // vertical timing
  }
  const centres = ALIGNMENT[version - 1] ?? [];
  for (const row of centres) {
    for (const col of centres) {
      // The three centres that fall inside a finder pattern are not alignment patterns at all.
      const nearFinder = (row <= 8 && col <= 8) || (row <= 8 && col >= size - 9) || (row >= size - 9 && col <= 8);
      if (nearFinder) continue;
      for (let r = -2; r <= 2; r += 1) {
        for (let c = -2; c <= 2; c += 1) {
          const ring = Math.max(Math.abs(r), Math.abs(c));
          set(grid, row + r, col + c, ring !== 1);
        }
      }
    }
  }
  set(grid, size - 8, 8, true); // the dark module
  // Reserve the format areas and the version areas so the data walk skips them.
  for (let i = 0; i < 9; i += 1) {
    if (!fixedAt(grid, 8, i)) set(grid, 8, i, false);
    if (!fixedAt(grid, i, 8)) set(grid, i, 8, false);
  }
  for (let i = 0; i < 8; i += 1) {
    if (!fixedAt(grid, 8, size - 1 - i)) set(grid, 8, size - 1 - i, false);
    if (!fixedAt(grid, size - 1 - i, 8)) set(grid, size - 1 - i, 8, false);
  }
  if (version >= 7) {
    for (let i = 0; i < 6; i += 1) {
      for (let j = 0; j < 3; j += 1) {
        set(grid, size - 11 + j, i, false);
        set(grid, i, size - 11 + j, false);
      }
    }
  }
}

function drawData(grid: Grid, codewords: readonly number[], version: number): void {
  const { size } = grid;
  const total = codewords.length * 8 + (REMAINDER[version - 1] ?? 0);
  let index = 0;
  const bit = (): boolean => {
    if (index >= total) return false;
    const byte = codewords[index >> 3] ?? 0;
    const value = (byte >> (7 - (index & 7))) & 1;
    index += 1;
    return value === 1;
  };
  let upward = true;
  // Two columns at a time, right to left, and the pair that would *start* on column 6 (the vertical timing pattern)
  // is shifted one to the left instead: `right -= 2` alone lands on (5,4), (4,3), (2,1) and leaves columns 3 and 0
  // unfilled, which is a QR that still looks like a QR and reads as nothing.
  for (let right = size - 1; right > 0; right -= 2) {
    if (right === 6) right = 5;
    const column = right;
    for (let i = 0; i < size; i += 1) {
      const row = upward ? size - 1 - i : i;
      const line = grid.dark[row];
      if (line === undefined) continue;
      for (const c of [column, column - 1]) {
        if (c < 0 || fixedAt(grid, row, c)) continue;
        line[c] = bit(); // data modules stay unfixed: this is the region the mask applies to
      }
    }
    upward = !upward;
  }
}

const MASKS: readonly ((row: number, col: number) => boolean)[] = [
  (r, c) => (r + c) % 2 === 0,
  (r) => r % 2 === 0,
  (_r, c) => c % 3 === 0,
  (r, c) => (r + c) % 3 === 0,
  (r, c) => (Math.floor(r / 2) + Math.floor(c / 3)) % 2 === 0,
  (r, c) => ((r * c) % 2) + ((r * c) % 3) === 0,
  (r, c) => (((r * c) % 2) + ((r * c) % 3)) % 2 === 0,
  (r, c) => (((r + c) % 2) + ((r * c) % 3)) % 2 === 0,
];

function applyMask(grid: Grid, mask: number): boolean[][] {
  const flip = MASKS[mask];
  if (flip === undefined) throw new RangeError(`qr: mask ${mask} does not exist`);
  return grid.dark.map((row, r) => row.map((dark, c) => (fixedAt(grid, r, c) ? dark : dark !== flip(r, c))));
}

/** A write the spec has already fixed the position of; out of range would be this file's bug, not the caller's. */
function put(dark: boolean[][], row: number, col: number, value: boolean): void {
  const line = dark[row];
  if (line === undefined) throw new RangeError(`qr: module (${row}, ${col}) is outside the symbol`);
  line[col] = value;
}

/** Format information, in both copies the spec requires: beside the top-left finder, and split bottom-left/top-right. */
function drawFormat(dark: boolean[][], size: number, mask: number): void {
  const bits = formatCodeword(mask);
  const bit = (i: number): boolean => ((bits >> i) & 1) === 1;
  // Two copies, and the *whole* point of pinning this against a reference encoder is here: the bit order and the
  // placement are a mirror of each other in the two directions, and a version that is plausible-but-rotated still
  // scans in some readers and not others. Bit 0 is the least significant bit of the 15-bit word.
  for (let i = 0; i <= 14; i += 1) {          // down column 8, and on into the bottom-left corner
    if (i < 6) put(dark, i, 8, bit(i));
    else if (i < 8) put(dark, i + 1, 8, bit(i)); // rows 7 and 8: the timing row is at 6, so bit 6 skips to 7
    else put(dark, size - 15 + i, 8, bit(i));
  }
  for (let i = 0; i <= 14; i += 1) {          // along row 8, and on into the top-right corner
    if (i < 8) put(dark, 8, size - i - 1, bit(i));
    else if (i === 8) put(dark, 8, 7, bit(i)); // column 6 is the timing column
    else put(dark, 8, 15 - i - 1, bit(i));
  }
  put(dark, size - 8, 8, true);               // the dark module, always set
}

function drawVersion(dark: boolean[][], size: number, version: number): void {
  if (version < 7) return;
  const bits = versionCodeword(version);
  for (let i = 0; i < 18; i += 1) {
    const value = ((bits >> i) & 1) === 1;
    const row = Math.floor(i / 3);
    const col = i % 3;
    put(dark, size - 11 + col, row, value);
    put(dark, row, size - 11 + col, value);
  }
}

/** The first index of `needle` in `hay` at or after `from`, or -1. Missing modules read as light, as in the quiet zone. */
function indexOfPattern(hay: readonly boolean[], needle: readonly boolean[], from: number): number {
  outer: for (let i = Math.max(0, from); i + needle.length <= hay.length; i += 1) {
    for (let j = 0; j < needle.length; j += 1) {
      if ((hay[i + j] ?? false) !== (needle[j] ?? false)) continue outer;
    }
    return i;
  }
  return -1;
}

/** The ISO/IEC 18004 Annex B penalty: the score the least-penalised mask wins on. */
function penalty(dark: readonly (readonly boolean[])[], size: number): number {
  const at = (row: number, col: number): boolean => darkAt(dark, row, col);
  let score = 0;
  // Rule 1: runs of five or more, horizontally and vertically.
  for (let i = 0; i < size; i += 1) {
    for (const horizontal of [true, false]) {
      let run = 1;
      for (let j = 1; j < size; j += 1) {
        const prev = horizontal ? at(i, j - 1) : at(j - 1, i);
        const cur = horizontal ? at(i, j) : at(j, i);
        if (cur === prev) {
          run += 1;
        } else {
          if (run >= 5) score += 3 + (run - 5);
          run = 1;
        }
      }
      if (run >= 5) score += 3 + (run - 5);
    }
  }
  // Rule 2: every 2x2 block of one colour.
  for (let r = 0; r < size - 1; r += 1) {
    for (let c = 0; c < size - 1; c += 1) {
      const v = at(r, c);
      if (at(r, c + 1) === v && at(r + 1, c) === v && at(r + 1, c + 1) === v) score += 3;
    }
  }
  // Rule 3: the finder lookalike — `1:1:3:1:1`, with four light modules on one side *or* the symbol's edge.
  //
  // This rule is written out the long way because the short version is wrong in a way that does not look wrong:
  // searching for the eleven-module sequence `10111010000` (and its mirror) finds only the patterns with four light
  // modules *inside* the symbol, and misses every one that sits flush against an edge — including the three finder
  // patterns themselves, which is most of the score on a small symbol. It cost a wrong mask on one of the three
  // fixtures, which is how it was found. This is the rule `segno` implements; `qrcode` scores candidates with their
  // format information already drawn, which is not what ISO/IEC 18004 section 7.8 asks for.
  const core = [true, false, true, true, true, false, true];
  const matches = (seq: readonly boolean[]): number => {
    let found = 0;
    let at_ = indexOfPattern(seq, core, 0);
    while (at_ !== -1) {
      let next = at_ + core.length;
      const before = seq.slice(Math.max(at_ - 4, 0), at_);
      const after = seq.slice(next, next + 4);
      const flush = at_ === 0 || at_ === size - core.length;
      if (flush || !before.some(Boolean) || !after.some(Boolean)) found += 40;
      else next = at_ + 4; // no light area here: resume four modules along, so an overlapping match still counts
      at_ = indexOfPattern(seq, core, next);
    }
    return found;
  };
  for (let i = 0; i < size; i += 1) {
    const across: boolean[] = [];
    const down: boolean[] = [];
    for (let j = 0; j < size; j += 1) {
      across.push(at(i, j));
      down.push(at(j, i));
    }
    score += matches(across);
    score += matches(down);
  }
  // Rule 4: the balance of dark to light.
  let darkCount = 0;
  for (let r = 0; r < size; r += 1) for (let c = 0; c < size; c += 1) if (at(r, c)) darkCount += 1;
  const percent = (darkCount * 100) / (size * size);
  score += Math.floor(Math.abs(percent - 50) / 5) * 10;
  return score;
}

/** The data codewords available at level M for `version` — the budget the payload and its header must fit in. */
function dataCodewordsFor(version: number): number {
  return (BLOCKS_M[version - 1] ?? []).reduce((sum, block) => sum + (block[1] ?? 0), 0);
}

export type QrMatrix = readonly (readonly boolean[])[];

/** The smallest version in this encoder's range that fits `bytes`, or `null`. */
export function qrVersionFor(bytes: number): number | null {
  for (let version = 1; version <= MAX_VERSION; version += 1) {
    const dataCodewords = dataCodewordsFor(version);
    const overhead = 4 + (version >= 10 ? 16 : 8);
    if (overhead + bytes * 8 <= dataCodewords * 8) return version;
  }
  return null;
}

/**
 * `text` as a QR matrix, no quiet zone and no rendering: rows of booleans, `true` meaning dark.
 *
 * The quiet zone is the caller's job because it is a *rendering* decision (four modules of light, and how big a module
 * is depends on the surface). Returning the raw matrix is what makes this testable against a reference encoder.
 */
export function encodeQr(text: string, ecc: "M" = "M"): QrMatrix {
  void ecc; // level M is the only one built; the parameter is here so a caller cannot think otherwise
  const payload = new TextEncoder().encode(text);
  const version = qrVersionFor(payload.length);
  if (version === null) {
    const capacity = dataCodewordsFor(MAX_VERSION) - (4 + 16) / 8;
    throw new QrTooLongError(payload.length, Math.floor(capacity));
  }
  const capacity = dataCodewordsFor(version);
  const codewords = interleave(messageCodewords(payload, version, capacity), version);
  const size = version * 4 + 17;
  const grid = blank(size);
  drawFunctionPatterns(grid, version);
  drawData(grid, codewords, version);
  let best: boolean[][] | null = null;
  let bestMask = 0;
  let bestScore = Number.POSITIVE_INFINITY;
  for (let mask = 0; mask < 8; mask += 1) {
    const candidate = applyMask(grid, mask);
    // The penalty is computed with the format and version areas still EMPTY, which ISO/IEC 18004 is explicit about
    // (7.8, and it is easy to miss): the mask is chosen on the data region's appearance, not on the mask plus the
    // header that describes it. Filling them first is not a cosmetic difference — with this encoder's own fixtures
    // it changes which mask wins for one of the three, so the QR would still scan and would not be the reference's.
    const score = penalty(candidate, size);
    if (score < bestScore) {
      bestScore = score;
      best = candidate;
      bestMask = mask;
    }
  }
  if (best === null) throw new Error("qr: no mask candidate was scored"); // unreachable: the loop always runs
  drawFormat(best, size, bestMask);
  drawVersion(best, size, version);
  return best;
}

/** The matrix as SVG path data on a 0-1 grid, so the caller can size it with CSS instead of arithmetic. */
export function qrSvgPath(matrix: QrMatrix): string {
  const parts: string[] = [];
  matrix.forEach((row, r) => {
    row.forEach((dark, c) => {
      if (dark) parts.push(`M${c} ${r}h1v1h-1z`);
    });
  });
  return parts.join("");
}
