/**
 * The share card, drawn as an image — and drawn from the SAME object the page renders.
 *
 * Why the card comes from the API rather than from the page's props: an unfurl is generated by a service that
 * has never run our JavaScript, at a URL (`/opengraph-image`) that has no other context, so the only thing that
 * can keep the image and the page agreeing is that both read one payload. `packages/polygm_core/public_pages/
 * cards.py` builds it — including the footnote's priority order, where the provisional label and the drawdown
 * are placed whether or not they fit — and this module draws it.
 *
 * Two rules from the design system hold here as well, with one adaptation:
 *
 *  * **No colour literal in the code.** `styles/og-colors.json` is generated from `brand/tokens.css` by
 *    `tools/build-web-tokens.mjs` (the P08 c5 scan forbids a hex in the shipped tree; an `ImageResponse` draws
 *    outside the document, so it cannot read a custom property). The card is drawn in the dark palette, which is
 *    the theme the brand was designed in and the one that survives being pasted onto an unknown background.
 *  * **Text that renders as text.** satori measures text with the fonts it is given; there is no font binary in
 *    the repo (the P02 brand kit names the families, the web loads them as woff2), so the card uses the generic
 *    families satori ships with. That is a real, stated limitation: the image's typography is close to the
 *    brand's rather than identical to it, and the alternative — a 300 KB font in the repo — is a decision for
 *    the deployment, not for this route.
 */
import { ImageResponse } from "next/og";
import ogColors from "../../styles/og-colors.json";
import { cardFootnote, cardLines } from "./card";
import type { PublicCard } from "./wire";

/** 1200×630: the size every unfurler crops to, and the one the card is laid out for. */
export const OG_SIZE = { width: 1200, height: 630 };
export const OG_CONTENT_TYPE = "image/png";

const C = ogColors.colors as Record<string, string>;

export function OgCard({ card }: { card: PublicCard }) {
  const lines = cardLines(card);
  const foot = cardFootnote(card);
  return (
    <div
      style={{
        width: "100%",
        height: "100%",
        display: "flex",
        flexDirection: "column",
        justifyContent: "space-between",
        backgroundColor: C["bg-base"],
        color: C["text-primary"],
        padding: 64,
        fontFamily: "sans-serif",
      }}
    >
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <span style={{ fontSize: 34, fontWeight: 700, color: C["brand-primary"] }}>{card.brand}</span>
        <span style={{ fontSize: 26, color: C["text-muted"] }}>{card.ranked ? "#ranked" : "#provisional"}</span>
      </div>

      <div style={{ display: "flex", flexDirection: "column" }}>
        <div style={{ fontSize: 30, color: C["text-secondary"] }}>{card.subtitle}</div>
        <div style={{ fontSize: 62, fontWeight: 700, marginTop: 16 }}>{card.title}</div>
      </div>

      <div style={{ display: "flex", gap: 56 }}>
        {lines.map((line) => (
          <div key={line.label} style={{ display: "flex", flexDirection: "column" }}>
            <span style={{ fontSize: 24, color: C["text-muted"] }}>{line.label}</span>
            <span style={{ fontSize: 52, fontWeight: 700 }}>{line.value}</span>
          </div>
        ))}
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
        {foot.map((note) => (
          <span key={note} style={{ fontSize: 26, color: C["text-secondary"] }}>
            {note}
          </span>
        ))}
        <span style={{ fontSize: 22, color: C["text-muted"] }}>{card.footer}</span>
      </div>
    </div>
  );
}

/**
 * The image, or `null` for a card the API did not produce.
 *
 * A missing card is a 404 from the API, and the route that calls this turns that into Next's own 404 rather than
 * drawing an empty rectangle: an OG image that says nothing is still an image somebody posts.
 */
export function renderCard(card: PublicCard | null): ImageResponse | null {
  if (!card) return null;
  return new ImageResponse(<OgCard card={card} />, { ...OG_SIZE });
}
