#!/usr/bin/env node
/**
 * Generates brand/tokens.css from brand/tokens.json.
 *
 * Why a generator rather than a hand-written stylesheet: brand/BRAND-KIT.md's palette and the audit
 * output are the source of truth, and a hand-copied CSS drifts from them silently — usually in the
 * one hex nobody re-checks. Run after editing tokens.json:
 *
 *   node tools/build-tokens.mjs            # writes brand/tokens.css
 *   node tools/build-tokens.mjs --check    # exit 1 if brand/tokens.css is stale
 */
import fs from 'node:fs';

const ROOT = new URL('..', import.meta.url).pathname;
const tokensPath = `${ROOT}brand/tokens.json`;
const cssPath = `${ROOT}brand/tokens.css`;
const t = JSON.parse(fs.readFileSync(tokensPath, 'utf8'));

const kebab = (k) => k.replace(/\./g, '-');
const block = (sel, obj) =>
  `${sel}\n{\n${Object.entries(obj).map(([k, v]) => `  --pgm-${kebab(k)}: ${v};`).join('\n')}\n}`;

const css = `/* PolyGM / Openout design tokens — GENERATED by tools/build-tokens.mjs. Do not edit by hand.
   Values: tools/colour-audit.py (WCAG) + tools/palette-search.py (Brettel ΔE*ab). Light is :root,
   dark-first is [data-theme="dark"], per brand/BRAND-KIT.md. */
${block(':root', t.semantic.light)}

${block('[data-theme="dark"]', t.semantic.dark)}

/* chart arrays — per theme, because no theme-agnostic 8-hue set clears ΔE≥10 once outcome and
   money hues are excluded (measured: best such set is 9.1) */
:root { --pgm-chart-count: ${t.chart.perThemeCount.light};
${t.chart.light.map((c, i) => `  --pgm-chart-${i + 1}: ${c};`).join('\n')} }
[data-theme="dark"] { --pgm-chart-count: ${t.chart.perThemeCount.dark};
${t.chart.dark.map((c, i) => `  --pgm-chart-${i + 1}: ${c};`).join('\n')} }

/* rules the palette cannot express as colour */
:root, [data-theme="dark"] {
  --pgm-mark-min-size-px: ${t.rules['mark-min-size-px']};   /* below this, brand/svg/favicon.svg is mandatory */
  --pgm-radius: 11.2px; --pgm-radius-card-dense: 8px; --pgm-radius-chip: 999px;
  --pgm-spacing-1: 4px; --pgm-spacing-2: 8px; --pgm-spacing-3: 12px;
  --pgm-spacing-4: 16px; --pgm-spacing-5: 24px; --pgm-spacing-6: 32px; --pgm-spacing-7: 48px;
}
/* NEVER put .pgm-outcome--no and .pgm-severity--critical in the same row (see tokens.json rules) */
.pgm-outcome--yes { color: var(--pgm-outcome-yes); }
.pgm-outcome--no  { color: var(--pgm-outcome-no); }
.pgm-outcome--yes::before { content: "▲ "; }   /* colour is never the only channel */
.pgm-outcome--no::before  { content: "● "; }
`;

if (process.argv.includes('--check')) {
  const cur = fs.existsSync(cssPath) ? fs.readFileSync(cssPath, 'utf8') : '';
  if (cur !== css) {
    console.error('brand/tokens.css is stale — run: node tools/build-tokens.mjs');
    process.exit(1);
  }
  console.log('brand/tokens.css is up to date with brand/tokens.json');
  process.exit(0);
}
fs.writeFileSync(cssPath, css);
console.log(`wrote ${cssPath} (${Buffer.byteLength(css)} bytes, chart: dark=${t.chart.perThemeCount.dark}, light=${t.chart.perThemeCount.light})`);
