#!/usr/bin/env python3
"""Generate the D4 contrast table straight from brand/tokens.json, and (with --check) verify that
docs/P02-brand.md still contains exactly those numbers.

One implementation of WCAG relative luminance is used by this, tools/colour-audit.py and
tools/p02-gate-check.py — imported, not re-typed. That is deliberate: the first version of the P02
table was generated by an inline script with its own rounding, the gate then re-derived the values,
and they disagreed (16.34 vs 13.94 on dark text.primary). A doc table and a checker must not each
own their own arithmetic, so this file is the only place the table is produced.

    python3 tools/build-contrast-table.py            # print markdown
    python3 tools/build-contrast-table.py --check    # exit 1 if the doc's table is stale
"""
from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))

import json  # noqa: E402

from colour_audit_lib import contrast  # noqa: E402

ROWS = [
    ("bg.base", None), ("bg.elevated", None), ("bg.inset", None),
    ("border.default", None), ("border.strong", None),
    ("text.primary", 4.5), ("text.secondary", 4.5), ("text.muted", 3.0),
    ("brand.primary", 3.0), ("brand.primary-text", 4.5), ("brand.on-primary", 3.0),
    ("outcome.yes", 3.0), ("outcome.no", 3.0),
    ("action.buy", 3.0), ("action.sell", 3.0),
    ("result.profit", 3.0), ("result.loss", 3.0),
    ("alert.info", 3.0), ("alert.watch", 3.0), ("alert.high", 3.0), ("alert.critical", 3.0),
]


def grade(r: float, floor: float) -> str:
    if floor <= 3.0:
        return "AAA" if r >= 4.5 else ("AA" if r >= 3.0 else "FAIL")
    return "AAA" if r >= 7 else ("AA" if r >= 4.5 else ("AA-large" if r >= 3 else "FAIL"))


def build(tokens: dict) -> str:
    lines = ["| token | dark | light | contrast on own canvas (dark / light) | floor | grade |",
             "|---|---|---|---|---|---|"]
    for key, floor in ROWS:
        d, l = tokens["semantic"]["dark"], tokens["semantic"]["light"]
        if floor is None:  # surfaces/lines are not text; printing contrast(bg, bg) = 1.00 is noise
            lines.append(f"| `{key}` | `{d[key]}` | `{l[key]}` | — (non-text) | 3.0 (UI) | — |")
            continue
        rd, rl = contrast(d[key], d["bg.base"]), contrast(l[key], l["bg.base"])
        lines.append(f"| `{key}` | `{d[key]}` | `{l[key]}` | **{rd:.2f} / {rl:.2f}** | {floor} | "
                     f"{grade(rd, floor)} / {grade(rl, floor)} |")
    return "\n".join(lines)


def main() -> int:
    tokens = json.load(open(os.path.join(ROOT, "brand", "tokens.json")))
    table = build(tokens)
    if "--check" in sys.argv:
        doc = open(os.path.join(ROOT, "docs", "P02-brand.md"), encoding="utf-8").read()
        stale = []
        for line in table.splitlines()[2:]:
            m = re.match(r"\| `([^`]+)`.*? \*\*([\d.]+) / ([\d.]+)\*\*", line)
            if not m:
                continue
            tok, dark, light = m.group(1), m.group(2), m.group(3)
            row = re.search(rf"^\| `{re.escape(tok)}` \| `[^`]+` \| `[^`]+` \| \*\*([\d.]+) / ([\d.]+)\*\*", doc, re.M)
            if not row:
                stale.append(f"{tok}: row missing from the doc")
            elif (row.group(1), row.group(2)) != (dark, light):
                stale.append(f"{tok}: doc {row.group(1)}/{row.group(2)} vs generated {dark}/{light}")
        if stale:
            print("D4 table is stale:\n  " + "\n  ".join(stale))
            print("  fix: python3 tools/build-contrast-table.py  (paste over the D4 table)")
            return 1
        print("D4 contrast table matches brand/tokens.json exactly")
        return 0
    print(table)
    return 0


if __name__ == "__main__":
    sys.exit(main())
