#!/usr/bin/env python3
"""P03 D7.3 — enumerate Storybook stories: every component × every applicable state.

Generated, not written by hand, for the reason the whole P02→P03 chain keeps hitting: a story list a
human maintains is a list that silently loses states. `tools/p03-gate-check.py` recomputes this file's
content from brand/tokens.json and fails if they disagree, so "we covered every state" is arithmetic.

  python3 tools/build-storybook-list.py            # writes docs/verification/P03-storybook-list.txt
  python3 tools/build-storybook-list.py --check     # exit 1 if the file is stale
"""
import json
import sys

TOKENS = "brand/tokens.json"
OUT = "docs/verification/P03-storybook-list.txt"

# States that are genuinely not applicable to a given component. Kept SHORT and *justified*: every
# entry here is a hole the gate will happily paper over if the reason is wrong.
NOT_APPLICABLE = {
    "Icon": {"hover", "active", "loading", "error", "empty", "insufficient", "disabled", "stale", "disconnected"},
    "Divider": {"loading", "error", "empty", "stale", "disconnected", "insufficient", "active"},
    "Skeleton": {"loading", "hover", "active", "error", "empty", "stale", "disconnected", "insufficient"},
    "Spinner": {"hover", "active", "error", "empty", "loading", "stale", "disconnected", "insufficient"},
    # An avatar's own image cannot fail with a server error; the *row* around it can.
    "Avatar": {"error", "insufficient"},
    # Purely presentational: no interaction, no own data fetch.
    "DepthChart": {"insufficient"},
    "TapeRow": {"error", "insufficient"},
    "MarketCard": {"insufficient"},
    "TraderCard": {"insufficient"},
    "EmptyState": {"empty", "loading"},
    "ErrorState": {"error", "loading"},
}
# Interactive surfaces must show every density × theme, because 11px text in a 20px row is where
# clipping and overlap bugs live.
DENSITY_THEMED = {"PriceCell", "TapeRow", "PositionRow", "OrderBook", "DataTable", "VirtualList", "Badge", "NumberInput"}

# Cross-cutting states that only exist per-component and would otherwise be "tested later".
EXTRA = {
    "OrderBook": ["balanced", "near-empty", "one-sided", "locked"],
    "YesNoPair": ["normal", "residual-warn", "no-book-one-side"],
    "TapeRow": ["trade", "redeem", "convert"],
    "StaleIndicator": ["watch", "stale", "blocking"],
    "TradeTicket": ["valid", "not-accepting", "below-min", "bad-tick", "insufficient", "confirm-required"],
    "PriceCell": ["tick-0.001", "tick-0.01", "flash-up", "flash-down", "stale", "no-value"],
    "PositionRow": ["profit-yes", "profit-no", "loss-yes", "loss-no", "greyscale", "deuter-sim", "protan-sim"],
    "WalletPanel": ["empty", "reconciled", "mismatch", "rpc-stale"],
    "CopyConfigPanel": ["off", "armed", "confirm-consequences", "paused-source-stale"],
}


def build() -> list[str]:
    t = json.load(open(TOKENS))
    c = t["components"]
    states = c["states"]
    out = []
    for group in ("primitives", "domain"):
        for comp in c[group]:
            na = NOT_APPLICABLE.get(comp, set())
            for st in states:
                if st in na:
                    continue
                if comp in DENSITY_THEMED:
                    for dens in c["densities"]:
                        for th in c["themes"]:
                            out.append(f"{comp}--{st}--{dens}--{th}")
                else:
                    out.append(f"{comp}--{st}")
            for x in EXTRA.get(comp, []):
                out.append(f"{comp}--{x}")
    # screen shells × the states that can only be seen at page level
    for scr in t["screens"]:
        for st in ("loading", "empty", "error", "partial", "stale", "disconnected", "unauthenticated"):
            out.append(f"screen/{scr['name']}--{st}")
    seen, uniq = set(), []
    for s in out:
        if s not in seen:
            seen.add(s)
            uniq.append(s)
    return sorted(uniq)


def main() -> int:
    stories = build()
    body = "# GENERATED by tools/build-storybook-list.py — do not edit.\n" \
           "# Component × state inventory; tools/p03-gate-check.py re-derives this from tokens.json.\n" \
           f"# total: {len(stories)}\n" + "\n".join(stories) + "\n"
    if "--check" in sys.argv:
        try:
            cur = open(OUT).read()
        except FileNotFoundError:
            cur = ""
        if cur != body:
            print(f"STALE {OUT} — run: python3 tools/build-storybook-list.py")
            return 1
        print(f"OK   {OUT} matches the token inventory ({len(stories)} stories)")
        return 0
    open(OUT, "w").write(body)
    per = {}
    for s in stories:
        per[s.split("--")[0]] = per.get(s.split("--")[0], 0) + 1
    print(f"wrote {OUT}: {len(stories)} stories across {len(per)} roots")
    top = sorted(per.items(), key=lambda kv: -kv[1])[:6]
    print("  densest: " + ", ".join(f"{k}×{v}" for k, v in top))
    return 0


if __name__ == "__main__":
    sys.exit(main())
