#!/usr/bin/env python3
"""Generate the D4 contrast table straight from brand/tokens.json, and (with --check) verify that
docs/P02-brand.md still contains exactly those numbers.

With --foundations this same file owns the numeric part of P03's D1 tables, and
`--foundations --check` verifies docs/P03-design-system.md still matches brand/tokens.json. It exists
because a spec that *types* token values eventually contradicts them: P03's D1 was first written by hand
and the flash figure drifted (600ms, then 350ms, then 290ms in tokens) while the doc kept the old number.
Prose in those subsections stays the author's; the numbers are this script's.

One implementation of WCAG relative luminance is used by this, tools/colour-audit.py and
tools/p02-gate-check.py — imported, not re-typed. That is deliberate: the first version of the P02
table was generated by an inline script with its own rounding, the gate then re-derived the values,
and they disagreed (16.34 vs 13.94 on dark text.primary). A doc table and a checker must not each
own their own arithmetic, so this file is the only place the table is produced.

    python3 tools/build-contrast-table.py            # print markdown
    python3 tools/build-contrast-table.py --check    # exit 1 if the doc's table is stale
"""
from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))

import json  # noqa: E402

from colour_audit_lib import contrast  # noqa: E402

ROWS = [
    ("bg.base", None), ("bg.elevated", None), ("bg.inset", None),
    ("border.default", None), ("border.strong", None),
    ("text.primary", 4.5), ("text.secondary", 4.5), ("text.muted", 3.0),
    ("brand.primary", 3.0), ("brand.primary-text", 4.5), ("brand.on-primary", 3.0),
    ("outcome.yes", 3.0), ("outcome.no", 3.0),
    ("action.buy", 3.0), ("action.sell", 3.0),
    ("result.profit", 3.0), ("result.loss", 3.0),
    ("alert.info", 3.0), ("alert.watch", 3.0), ("alert.high", 3.0), ("alert.critical", 3.0),
]


def grade(r: float, floor: float) -> str:
    if floor <= 3.0:
        return "AAA" if r >= 4.5 else ("AA" if r >= 3.0 else "FAIL")
    return "AAA" if r >= 7 else ("AA" if r >= 4.5 else ("AA-large" if r >= 3 else "FAIL"))


def build(tokens: dict) -> str:
    lines = ["| token | dark | light | contrast on own canvas (dark / light) | floor | grade |",
             "|---|---|---|---|---|---|"]
    for key, floor in ROWS:
        d, l = tokens["semantic"]["dark"], tokens["semantic"]["light"]
        if floor is None:  # surfaces/lines are not text; printing contrast(bg, bg) = 1.00 is noise
            lines.append(f"| `{key}` | `{d[key]}` | `{l[key]}` | — (non-text) | 3.0 (UI) | — |")
            continue
        rd, rl = contrast(d[key], d["bg.base"]), contrast(l[key], l["bg.base"])
        lines.append(f"| `{key}` | `{d[key]}` | `{l[key]}` | **{rd:.2f} / {rl:.2f}** | {floor} | "
                     f"{grade(rd, floor)} / {grade(rl, floor)} |")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# --foundations: the numeric half of P03's D1 tables. Prose is the doc's; these numbers are the tokens'.
# --------------------------------------------------------------------------- #

P03 = os.path.join(ROOT, "docs", "P03-design-system.md")


def foundations_tables(tokens: dict) -> dict:
    """table_id -> rows of (doc_row_label, [cell texts]). --check compares these numbers, nothing else.

    Row labels are emitted in the exact form the doc uses (`cell_x` pad, not `cell_x pad`) because the
    doc is what gets checked; inventing a tidier label here would just make every row look "absent".
    """
    sp, den = tokens["spacing"], tokens["density"]

    offgrid = [(f"`--pgm-space-off-{i + 1}`", [str(x["px"])])
               for i, x in enumerate(sp["allowed_offgrid"])]

    # ONE column order for the whole density table, derived from the canonical row-height scale, smallest
    # first (dense -> compact -> comfortable). Taking it from setting.levels (comfortable-first) produced a
    # table whose header and numbers disagreed with the doc while every number was individually correct.
    heights = den["row_heights_px"]["table_row"]
    densities = sorted(heights, key=lambda d: heights[d])
    metrics = [(f"`{k}`", v) for k, v in den["row_heights_px"].items()] + \
              [(f"`{k}` pad", v) for k, v in den["padding_px"].items() if k != "screen"] + \
              [("font size", den["font_size_px"])]
    drows = [(label, [str(vals[d]) for d in densities]) for label, vals in metrics]

    bp = tokens["breakpoints"]
    brows = []
    for b in bp["values"]:
        trig = f"<{b['max'] + 1}" if "max" in b else f"\u2265{b['min']}"
        brows.append((f"`{b['name']}`", [trig]))

    # the spacing scale, in the two forms the doc is allowed to use. Formatting is the author's; the
    # NUMBERS are the tokens'. A single hard-coded separator string made this report false staleness.
    nums = [x["px"] for x in sp["scale"]]
    names = [x["name"] for x in sp["scale"]]
    scale_forms = [
        # name list AND pixel list both present, in either separator style
        "steps `" + " ".join(names) + "` (" + "/".join(str(n) for n in nums) + " px)",
        "steps `" + " ".join(names) + "` (" + " ".join(f"{n}{sp['unit']}" for n in nums) + ")",
        " ".join(str(n) for n in nums) + f" ({'/'.join(str(n) for n in nums)} px)",
        " ".join(str(n) for n in nums) + " (" + " ".join(f"{n}{sp['unit']}" for n in nums) + ")",
        " ".join(f"{n}{sp['unit']}" for n in nums),
    ]
    return {
        "spacing-offgrid": offgrid,
        "density": drows,
        "breakpoints": brows,
        "_scale_forms": scale_forms,
        "_header": densities,
    }


def foundations_check(tokens: dict) -> int:
    doc = open(P03, encoding="utf-8").read()
    tables = foundations_tables(tokens)
    stale: list[str] = []

    # the density header is part of the contract: 9 correct figures under a reversed header render wrong
    header = re.search(r"^\| px \|(.*)$", doc, re.M)
    want_head = tables["_header"]
    if not header:
        stale.append("[density] no `| px | dense | … |` header found — columns cannot be attributed")
    else:
        got = [c.strip().strip("*` ") for c in header.group(1).split("|") if c.strip()]
        if got != want_head:
            stale.append(f"[density] header {got} vs token order {want_head}")

    for tid in ("spacing-offgrid", "density", "breakpoints"):
        rows = dict(tables[tid])
        for line in doc.splitlines():
            if not line.startswith("| "):
                continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) < 2 or cells[0] not in rows:
                continue
            want = rows[cells[0]]
            got = cells[1:1 + len(want)]
            if got != want:
                stale.append(f"[{tid}] {cells[0]}: doc {got} vs tokens {want}")
        absent = [k for k in rows if k not in doc]
        if absent:
            stale.append(f"[{tid}] rows absent from the doc: {absent}")

    if not any(f in doc for f in tables["_scale_forms"]):
        stale.append("[spacing-scale] no accepted form of the token scale appears in the doc; want one of:")
        for f in tables["_scale_forms"]:
            stale.append(f"    {f}")

    if stale:
        print("D1 foundations are stale vs brand/tokens.json:")
        for x in stale:
            print("  ✗", x)
        print("  the tokens are the source of truth — change the JSON (and regenerate), or fix the doc")
        return 1
    n = sum(len(tables[t]) for t in ("spacing-offgrid", "density", "breakpoints"))
    print(f"D1 foundations match tokens.json: {n} table rows, the header order, and the spacing scale")
    print("  prose in those subsections is authored; the numbers are generated. Regenerate, don't retype.")
    return 0


def main() -> int:
    tokens = json.load(open(os.path.join(ROOT, "brand", "tokens.json")))
    if "--foundations" in sys.argv:
        if "--check" in sys.argv:
            return foundations_check(tokens)
        tables = foundations_tables(tokens)
        for tid, rows in tables.items():
            if tid.startswith("_"):
                continue
            print(f"### {tid}\n| row | values |\n|---|---|")
            for k, v in rows:
                print(f"| {k} | {' | '.join(v)} |")
        return 0
    table = build(tokens)
    if "--check" in sys.argv:
        doc = open(os.path.join(ROOT, "docs", "P02-brand.md"), encoding="utf-8").read()
        stale = []
        for line in table.splitlines()[2:]:
            m = re.match(r"\| `([^`]+)`.*? \*\*([\d.]+) / ([\d.]+)\*\*", line)
            if not m:
                continue
            tok, dark, light = m.group(1), m.group(2), m.group(3)
            row = re.search(rf"^\| `{re.escape(tok)}` \| `[^`]+` \| `[^`]+` \| \*\*([\d.]+) / ([\d.]+)\*\*", doc, re.M)
            if not row:
                stale.append(f"{tok}: row missing from the doc")
            elif (row.group(1), row.group(2)) != (dark, light):
                stale.append(f"{tok}: doc {row.group(1)}/{row.group(2)} vs generated {dark}/{light}")
        if stale:
            print("D4 table is stale:\n  " + "\n  ".join(stale))
            print("  fix: python3 tools/build-contrast-table.py  (paste over the D4 table)")
            return 1
        print("D4 contrast table matches brand/tokens.json exactly")
        return 0
    print(table)
    return 0


if __name__ == "__main__":
    sys.exit(main())
