#!/usr/bin/env python3
"""The P06 kill-switch drill, against running processes.

    Engage the switch. Measure, in milliseconds, how long each component takes to refuse. Report the number,
    including the ones that are embarrassing.

`make gate-p06` proves the switch is fail-closed in a single process with the clock in our hands. That is not a
drill: a drill is what happens at 03:00 with a live queue, a running executor and an operator typing into a
real endpoint. This harness therefore starts the API under uvicorn, the mock venue on a socket, and TWO
executor processes (a deploy runs more than one, and the second one is what catches a claim the first one
leased and lost). Then it engages the switch through the HTTP endpoint — not through the database — and times
each component's refusal.

Five components are sampled, and the artifact says how each was measured, because "networked HTTP" and
"in-process against the same engaged database" are different claims:

  api         POST /v1/orders/draft after engaging          real HTTP, real process
  executor    an intent queued AFTER the engage response     the child's own gate, seen in the DB
  worker      a second executor process, reconcile loop      same, second pid
  copy        the copy engine's decision on a source fill    in-process
  automation  the automation engine's live tick             in-process

The budget is `lm.KILL_BUDGET_MS` (1000 ms), the same number the phase doc states, and it is applied to the
WORST component, not the average: a plane that stops in 40 ms in four places and 4 s in one place is a plane
that takes 4 seconds to stop.

The drill also checks the probe is capable of *not* firing: before engaging, the draft request must be
accepted. A measurement that reads "0 ms to refusal" against a plane that was already refusing is not a
drill, it is a tautology.

    python3 tools/p06-drill.py --record docs/verification/P06-drill.txt
    python3 tools/p06-drill.py --interval-ms 250        # a slower loop, to watch the number grow
"""
from __future__ import annotations

import argparse
import json
import os
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PY = sys.executable
sys.path[:0] = [str(ROOT / "packages"), str(ROOT / "services" / "executor"), str(ROOT / "tools"),
                str(ROOT / "tests"), str(ROOT / "services" / "api"), str(ROOT / "services" / "executor-mock")]

from polygm_core.risk import limits as lm                                    # noqa: E402


class Out:
    def __init__(self, record: Path | None) -> None:
        self.lines: list[str] = []
        self.record = record

    def __call__(self, text: str = "") -> None:
        self.lines.append(text)
        print(text, flush=True)

    def save(self) -> None:
        head = ["P06 kill-switch drill — %s" % time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "generated by tools/p06-drill.py; the numbers below are measured, not transcribed",
                "budget: %d ms from the engage call to the refusal, worst component" % lm.KILL_BUDGET_MS,
                ""]
        self.record.parent.mkdir(parents=True, exist_ok=True)
        self.record.write_text("\n".join(head + self.lines) + "\n")


def get(url: str, timeout: float = 6.0) -> tuple[int, dict]:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as r:
            return r.status, json.loads(r.read() or b"{}")
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read() or b"{}")
    except (urllib.error.URLError, TimeoutError, ConnectionError) as e:
        return 0, {"error": type(e).__name__}


def free_port() -> int:
    s = socket.socket()
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


def post(url: str, body: dict, headers: dict | None = None, timeout: float = 8.0) -> tuple[int, dict, float]:
    """Returns (status, json, round-trip ms) — the round trip is part of the measurement on purpose: an
    operator experiences the switch as the latency of the call that got refused."""
    raw = json.dumps(body).encode()
    h = {"content-type": "application/json", **(headers or {})}
    req = urllib.request.Request(url, data=raw, method="POST", headers=h)
    t0 = time.perf_counter()
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status, json.loads(r.read() or b"{}"), (time.perf_counter() - t0) * 1000
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read() or b"{}"), (time.perf_counter() - t0) * 1000


def wait_api(base: str, *, until: float) -> bool:
    while time.time() < until:
        try:
            with urllib.request.urlopen(base + "/healthz", timeout=1.0) as r:
                if r.status == 200:
                    return True
        except Exception:                                       # noqa: BLE001 - polling
            time.sleep(0.15)
    return False


def order_body(market: str, token: str, price: str, key: str) -> tuple[dict, dict]:
    """The real request shape this API accepts: decimal STRINGS for money, camelCase fields, a user header and
    an idempotency key. A drill that posts a invented shape measures a 422, not a kill switch."""
    body = {"marketId": market, "tokenId": token, "side": "BUY", "price": price, "size": "6"}
    return body, {"X-User-Id": "u-demo", "Idempotency-Key": key}


def main() -> int:
    ap = argparse.ArgumentParser(description="P06 kill-switch drill against running processes")
    ap.add_argument("--record", default="", help="write the artifact here")
    ap.add_argument("--interval-ms", type=int, default=100, help="the executor loop period (what we are also")
    ap.add_argument("--ticks", type=int, default=40, help="how long each child stays up")
    a = ap.parse_args()
    say = Out(Path(a.record) if a.record else None)
    procs: list[subprocess.Popen] = []
    code = 1
    sys.path[:0] = [str(ROOT / "tests")]
    import importlib.util
    spec = importlib.util.spec_from_file_location("p06_gate_for_drill", str(ROOT / "tools" / "p06-gate-check.py"))
    gate = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = gate
    spec.loader.exec_module(gate)

    say("booting a plane, a venue, an API under uvicorn and two executor processes...")
    p = gate.Plane()
    p.tight_book()
    p.fund(policy=p.wl.Policy())
    vport = free_port()
    venue = subprocess.Popen([PY, str(ROOT / "services" / "executor-mock" / "mock_clob.py"), "--host",
                             "127.0.0.1", "--port", str(vport)], stdout=subprocess.DEVNULL,
                             stderr=subprocess.DEVNULL)
    procs.append(venue)
    aport = free_port()
    env = dict(os.environ)
    env["PYTHONPATH"] = os.pathsep.join([str(ROOT / "packages"), str(ROOT / "services" / "api"),
                                        str(ROOT / "services" / "executor"),
                                        str(ROOT / "services" / "executor-mock"), str(ROOT / "tools")])
    env["PGM_DB_PATH"] = p.db
    api = subprocess.Popen([PY, "-m", "uvicorn", "app:app", "--host", "127.0.0.1", "--port", str(aport),
                            "--log-level", "warning"], cwd=str(ROOT / "services" / "api"), env=env,
                           stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
    procs.append(api)
    base = "http://127.0.0.1:%d" % aport
    # the children must outlive the API boot: a dead child is indistinguishable from a child that refused
    ticks = max(a.ticks, int(45_000 / max(a.interval_ms, 10)))
    kids, kid_logs = [], []
    for i in range(2):
        kenv = dict(env)
        kenv["PGM_NODE_ID"] = "drill-%d" % i
        kenv["PYTHONPATH"] = os.pathsep.join([str(ROOT / "packages"), str(ROOT / "services" / "executor"),
                                             str(ROOT / "services" / "executor-mock"), str(ROOT / "tools")])
        log_path = p.db + ".executor-%d.log" % i
        kid_logs.append(log_path)
        kids.append(subprocess.Popen([PY, str(ROOT / "services" / "executor" / "main.py"), "--db", p.db,
                                     "--venue", "http://127.0.0.1:%d" % vport, "--ticks", str(ticks),
                                     "--interval-ms", str(a.interval_ms)], cwd=str(ROOT), env=kenv,
                                     stdout=open(log_path, "w"), stderr=subprocess.STDOUT))
        procs.append(kids[-1])
    venue_base = "http://127.0.0.1:%d" % vport
    try:
        if not wait_api(base, until=time.time() + 30):
            say("FAIL: the API never answered /healthz; the drill cannot measure what it cannot reach")
            return 1
        say("api on %d, venue on %d, executors on %d ms ticks" % (aport, vport, a.interval_ms))

        def order(key: str) -> tuple[int, dict, float]:
            body, hdr = order_body(p.market, p.token, "0.50", key)
            return post(base + "/v1/orders", body, headers=hdr)

        # ------------------------------------------------------------------ first: the plane is trading
        # Every component gets a control measurement with the switch OFF, before it gets a refusal measurement
        # with it on. Without the controls, "0 orders placed" after the engage is a tautology — it would also
        # be true of a plane that never places anything.
        from polygm_core.copy import engine as cp
        from polygm_core.automation import engine as au
        ts = int(time.time() * 1000)
        p.store.conn.execute("INSERT OR REPLACE INTO copy_configs (id,user_id,source_user,mode,ratio_bps,"
                             "max_order_micro,max_daily_micro,blocked_markets,enabled,created_ms) "
                             "VALUES (?,?,?,?,?,?,?,?,?,?)",
                             ("drill-cc", p.user, "u-src", "mirror", 10_000, 25_000_000, 250_000_000,
                              "[]", 1, ts))
        p.store.save_copy_config_policy(config_id="drill-cc", at=ts, max_entry_deviation_bps=150,
                                       take_profit_bp=None, stop_loss_bp=None, min_seconds_to_resolution=900)
        p.store.conn.commit()
        ceng = cp.CopyEngine(p.store, builder_bps=100, fee_rate_bps=0)
        aeng = au.AutomationEngine(p.store)
        aeng.save_rule(rule_id="ar-drill", user_id=p.user, kind="entry", at=ts, enabled=True,
                      rule={"trigger": {"kind": "price_cross", "op": ">=", "price_micro": 480_000,
                                       "uses": "ask"},
                            "actions": [{"kind": "market", "side": "BUY", "size_shares_micro": 10 * 10**6,
                                         "max_slippage_bps": 100}],
                            "max_loss_micro": 1_000_000},
                      market_ids=[(p.market, p.token)])
        aeng.tick(at=ts, mode="dry_run")          # the engine only arms a rule it has SEEN evaluated
        aeng.mark_dry_run_done("ar-drill", at=ts + 1)
        arming = aeng.enable("ar-drill", at=ts + 2)
        armed = bool(arming["enabled"])

        def fill_of(tag: str, when: int) -> cp.SourceFill:
            return cp.SourceFill(wallet="u-src", intent_id="i-" + tag, token_id=p.token, market_id=p.market,
                                 side="BUY", price_micro=500_000, size_shares_micro=10 * 10**6, at_ms=when)

        def refresh(when: int) -> int:
            p.store.conn.execute("UPDATE book_levels SET updated_ms=?", (when,))
            p.store.conn.execute("UPDATE markets SET updated_ms=? WHERE id=?", (when, p.market))
            p.store.conn.commit()
            return when

        t = refresh(int(time.time() * 1000))
        ctrl_copy = ceng.on_source_fill(fill_of("ctrl", t), at=t)
        ctrl_copy_ok = bool(ctrl_copy) and all(r.get("action") == "copied" for r in ctrl_copy)
        ctrl_auto = aeng.tick(at=refresh(t + 500) + 500, mode="live")
        ctrl_placed = [o for o in (ctrl_auto.get("outcomes") or []) if o.get("outcome") == "placed"]
        say("controls with the switch OFF: copy acted=%s, automation armed=%s placed=%d — a plane "
            "that was never going to trade cannot be stopped"
            % (ctrl_copy_ok, armed, len(ctrl_placed)))

        def order(key: str) -> tuple[int, dict, float]:
            body, hdr = order_body(p.market, p.token, "0.50", key)
            return post(base + "/v1/orders", body, headers=hdr)

        # the sensitivity check: with the switch OFF, the same request must be accepted. Without this line the
        # drill would report 0 ms to refusal against a plane that was already refusing everything.
        st, body, ms = order("drill-baseline-%d" % (int(time.time() * 1000) % 1000000))
        accepted_before = st == 202 and not (body.get("error") or {}).get("code")
        say("baseline (switch OFF): POST /v1/orders -> %d in %.0f ms%s — %s"
            % (st, ms, " err=%s" % (body.get("error") or {}).get("code") if body.get("error") else "",
               "the probe CAN pass, so a refusal will mean something" if accepted_before
               else "PROBE IS DEAD: the API refuses an order with the switch off"))

        t_zero = int(time.time() * 1000)
        st_k, body_k, ms_k = post(base + "/v1/admin/kill-switch",
                                 {"engaged": True, "reason": "P06 drill: scheduled kill-switch test"},
                                 headers={"X-Admin-Token": "drill"})
        say("engage: POST /v1/admin/kill-switch -> %d in %.0f ms (server said atMs %s)"
            % (st_k, ms_k, body_k.get("atMs")))
        engaged_at = t_zero
        if st_k >= 400:
            say("FAIL: the engage call itself was refused (%d): %s" % (st_k, json.dumps(body_k)[:160]))
            return 1

        # api: the first order request after the engage must be refused, and we time that request end to end
        st_a, body_a, ms_a = order("drill-refused-%d" % (int(time.time() * 1000) % 1000000))
        code_a = str((body_a.get("error") or {}).get("code") or "")
        refused_api = code_a == "RISK_HALT"
        api_ms = int(round(ms_a)) if refused_api else None
        say("  api        refused=%s status=%d in %s ms  (code %s, retryable %s)"
            % (refused_api, st_a, api_ms, code_a or "-", (body_a.get("error") or {}).get("retryable")))

        # executor + worker: TWO batches, because a switch has a propagation path and a drill that ignores it
        # measures the wrong thing. A child re-reads the switch at most every KILL_POLL_MS and acts once per
        # tick, so an intent queued in the same instant can legitimately be submitted before the process
        # notices — the design says "in-flight work finishes". What may NOT happen is any POST at all after
        # that window has passed, so the second batch is queued after it and must be refused.
        from store import KILL_POLL_MS
        grace_ms = KILL_POLL_MS + a.interval_ms + 60

        def venue_posts() -> int:
            _code, snap = get(venue_base + "/v1/orders")
            return len(snap.get("requests") or [])

        refresh(int(time.time() * 1000))
        in_flight = {p.queue(key="drill-flight-%s" % kid, price=500_000, size=6 * 10**6): kid
                     for kid in ("executor", "worker")}
        posts_at_engage = venue_posts()
        time.sleep(grace_ms / 1000.0)
        posts_after_grace = venue_posts()
        sent_in_flight = posts_after_grace - posts_at_engage
        say("    in-flight tolerance: %d ms (poll %d + tick %d + slack 60); venue POSTs went %d -> %d in that "
            "window (%d order(s) legitimately finished)"
            % (grace_ms, KILL_POLL_MS, a.interval_ms, posts_at_engage, posts_after_grace, sent_in_flight))
        for iid, kid in in_flight.items():
            r = p.store.conn.execute("SELECT state FROM order_intents WHERE id=?", (iid,)).fetchone()
            say("    in-flight %s: intent ended %s" % (kid, r[0] if r else "gone"))

        refresh(int(time.time() * 1000))
        probes = {p.queue(key="drill-refuse-%s" % kid, price=500_000, size=6 * 10**6): kid
                  for kid in ("executor", "worker")}
        seen: dict[str, int] = {}
        deadline = time.time() + (a.interval_ms * 12 + 6_000) / 1000.0
        while time.time() < deadline and len(seen) < len(probes):
            for iid, kid in probes.items():
                if kid in seen:
                    continue
                r = p.store.conn.execute("SELECT state, COALESCE(risk_code,'') FROM order_intents WHERE id=?",
                                         (iid,)).fetchone()
                if r and r[0] == "rejected" and r[1] == "RISK_HALT":
                    seen[kid] = int(time.time() * 1000) - engaged_at
            time.sleep(0.005)
        late_posts = venue_posts() - posts_after_grace
        for kid in ("executor", "worker"):
            say("  %-11s refused after %s ms; %d POST(s) sent after the grace window (must be 0)"
                % (kid, seen.get(kid), late_posts))
        for iid, kid in probes.items():
            r = p.store.conn.execute("SELECT state, COALESCE(risk_code,'') FROM order_intents WHERE id=?",
                                     (iid,)).fetchone()
            say("    refused-batch %s: state=%s risk=%s" % (kid, r[0], r[1] or "-"))
        for i, path in enumerate(kid_logs):
            txt = Path(path).read_text().strip().splitlines() if Path(path).exists() else []
            say("    executor-%d alive=%s log lines=%d halted=%s"
                % (i, kids[i].poll() is None, len(txt),
                   "yes" if any('\"halted\": true' in x or '"halted":true' in x for x in txt) else "not yet"))
        if late_posts:
            say("    FAIL: the plane put %d order(s) on the venue after the switch was readable" % late_posts)

        # copy + automation, engaged. `decide()` is a pure function with no view of the switch, so timing it
        # would measure arithmetic; these are the calls that can put an order on the wire.
        t = refresh(int(time.time() * 1000))
        intents_before = p.store.conn.execute("SELECT COUNT(*) FROM order_intents").fetchone()[0]
        t0 = time.perf_counter()
        cres = ceng.on_source_fill(fill_of("post", t), at=t)
        copy_ms = int((time.perf_counter() - t0) * 1000)
        queued_now = p.store.conn.execute("SELECT COUNT(*) FROM order_intents").fetchone()[0]
        copy_refused = bool(cres) and all(r.get("action") == "skipped" and "disabled" in str(r.get("reason"))
                                          for r in cres) and queued_now == intents_before
        say("  copy       %d ms, %d copier(s) answered, %d new intent row(s): %s"
            % (copy_ms, len(cres), queued_now - intents_before, str((cres or [{}])[0].get("reason"))[:56]))
        # the control fired a moment ago and a rule may run once per MIN_INTERVAL_MS, so the measurement tick
        # is placed past that clock: the refusal we want to see is the switch's, not the interval's.
        t0 = time.perf_counter()
        aout = aeng.tick(at=refresh(t + au.MIN_INTERVAL_MS + 1_000) + au.MIN_INTERVAL_MS + 1_000, mode="live")
        auto_ms = int((time.perf_counter() - t0) * 1000)
        ao = (aout.get("outcomes") or [{}])[0]
        placed = [o for o in (aout.get("outcomes") or []) if o.get("outcome") == "placed"]
        auto_refused = bool(armed and not placed and "disabled" in str(ao.get("reason")))
        say("  automation %d ms, armed=%s outcome=%s (%s); %d order(s) placed while engaged"
            % (auto_ms, armed, ao.get("outcome"), str(ao.get("reason"))[:44], len(placed)))
        if not armed:
            say("  (automation could not be armed even before the engage: %s — the refusal is reported, not "
                "scored as a pass)" % str(arming)[:80])

        samples = []
        for kid, ms_val, method in (("api", api_ms, "real HTTP to uvicorn"),
                                   ("executor", seen.get("executor"), "child process, decision read from the DB"),
                                   ("worker", seen.get("worker"), "second child process, same DB"),
                                   ("copy", copy_ms if copy_refused else None,
                                    "in-process CopyEngine.on_source_fill, engaged DB"),
                                   ("automation", auto_ms if auto_refused else None,
                                    "in-process AutomationEngine live tick, armed while engaged")):
            if ms_val is None:
                say("  !! %s did not refuse inside the window — reported, not rounded away" % kid)
                continue
            samples.append(lm.DrillSample(component=kid, t_zero_ms=engaged_at,
                                         refused_at_ms=engaged_at + int(ms_val), method=method))
        verdict = lm.drill_verdict(samples)
        say("")
        say("sampled %d of %d components; worst %s ms; budget %d ms; verdict %s"
            % (len(samples), len(lm.COMPONENTS), verdict["worst_ms"], lm.KILL_BUDGET_MS, verdict["verdict"]))
        if verdict.get("negative_latency"):
            say("NEGATIVE LATENCY (a sample that refused before T0 is a broken clock, not a fast plane): %s"
                % verdict["negative_latency"])
        ok = (verdict["verdict"] == "pass" and accepted_before and len(samples) == len(lm.COMPONENTS)
              and not verdict.get("negative_latency"))
        for k, v in (("api", api_ms), ("executor", seen.get("executor")), ("worker", seen.get("worker"))):
            if v is not None and v > lm.KILL_BUDGET_MS:
                say("OVER BUDGET: %s took %d ms (budget %d)" % (k, v, lm.KILL_BUDGET_MS))
                ok = False
        say("")
        say("DRILL RESULT: %s" % ("PASS" if ok else "FAIL"))
        say("what this does NOT prove: that the venue saw no further fills. In-flight orders stay on the book; "
            "the switch stops NEW orders, and cancelling what is already live is `CANCEL ALL ORDERS` on the "
            "orders page, which is a different action with a different reason.")
        code = 0 if ok else 1
    finally:
        for pr in procs:
            try:
                pr.terminate()
                pr.wait(timeout=6)
            except Exception:                                   # noqa: BLE001 - cleanup only
                pass
        p.close()
        if a.record:
            say.save()
            print("recorded: %s" % a.record, flush=True)
    return code


if __name__ == "__main__":
    sys.exit(main())
