#!/usr/bin/env python3
"""P06's mid-flight chaos test: SIGKILL the executor at the three moments that cost money, and count what the
venue ends up holding.

    Kill the process between the signature and the POST. Between the POST and the answer. Between the venue's
    fill and our ledger. After each, restart and reconcile. Exactly one order must exist at the venue, and
    exactly one ledger row must exist per venue trade.

Why a subprocess and not a mock: the claim under test is "the plane survives a process that stopped existing".
An in-process simulation cannot make that claim, because the code that simulates is the code that would have
had to recover. So this harness starts the real `services/executor/main.py` as a child process, and the mock
venue as a SECOND process on a socket that deliberately outlives the executor. The number that decides whether
recovery worked is the venue's, not ours.

Each scenario gets its own database and its own venue process, because a venue shared between scenarios counts
everybody's orders and "exactly one" stops meaning anything.

  S1   signed, then killed before the POST        venue holds 0; recovery POSTs exactly 1
  S2   killed inside the POST, after the accept    venue holds 1; recovery ADOPTS it; POST count does not move
  S2b  the queue hands that intent back again      the attempt row + the venue's answer stop the re-send
  S3   killed after a fill was booked             one ledger row for that venue trade, forever

`--crash-after <stage>` with `PGM_CRASH_SIGNAL=stop` is the seam that makes the instant deterministic: the child
freezes itself at the stage and waits to be killed, so the kill lands exactly where the sentence says it does.
It is not `sys.exit`: a stopped process has run no `finally`, closed no connection and committed nothing, and
the harness sends the `SIGKILL` itself.

    python3 tools/p06-chaos-test.py                              # ~30 s, prints and checks everything
    python3 tools/p06-chaos-test.py --record docs/verification/P06-chaos-output.txt
    python3 tools/p06-chaos-test.py --age-ms 600000              # a ten-minute outage instead of a minute
    python3 tools/p06-chaos-test.py --only s2                    # one scenario while editing
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import signal
import socket
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GATE = ROOT / "tools" / "p06-gate-check.py"
PY = sys.executable


class Out:
    """What the harness prints is what it records, so the artifact is a transcript and not a re-typed summary
    of a run that may have differed."""

    def __init__(self, record: Path | None) -> None:
        self.lines: list[str] = []
        self.record = record

    def __call__(self, text: str = "") -> None:
        line = ("%s  %s" % (time.strftime("%H:%M:%S"), text)) if text else ""
        self.lines.append(line)
        print(line, flush=True)

    def save(self) -> None:
        head = ["P06 mid-flight chaos test — %s" % time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "generated by tools/p06-chaos-test.py; not hand-written and not edited afterwards",
                "real processes: services/executor/main.py (SIGKILLed by this harness), the mock venue on a",
                "socket (a second process, on purpose, so it survives the executor's death and can be asked)",
                "each scenario: its own SQLite database and its own venue",
                ""]
        self.record.parent.mkdir(parents=True, exist_ok=True)
        self.record.write_text("\n".join(head + self.lines) + "\n")


def http(method: str, url: str, body: dict | None = None, timeout: float = 8.0) -> tuple[int, dict]:
    raw = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=raw, method=method, headers={"content-type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as r:
            return r.status, json.loads(r.read() or b"{}")
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read() or b"{}")
    except (urllib.error.URLError, TimeoutError, ConnectionError) as e:
        return 0, {"error": type(e).__name__, "message": str(e)[:120]}


def free_port() -> int:
    s = socket.socket()
    s.bind(("127.0.0.1", 0))
    port = s.getsockname()[1]
    s.close()
    return port


class Pump(threading.Thread):
    """Reads a child's stdout as lines so the harness can WAIT for `halted-after=signed` instead of sleeping
    for a guess about when the child got there."""

    def __init__(self, stream) -> None:
        super().__init__(daemon=True)
        self.stream, self._lines, self.lock = stream, [], threading.Lock()
        self.start()

    def run(self) -> None:
        for line in self.stream:
            with self.lock:
                self._lines.append(line.rstrip("\n"))

    def wait_for(self, needle: str, *, timeout: float) -> str | None:
        until = time.time() + timeout
        while time.time() < until:
            with self.lock:
                for ln in self._lines:
                    if needle in ln:
                        return ln
            time.sleep(0.02)
        return None

    def tail(self, n: int = 5) -> str:
        with self.lock:
            return " | ".join(self._lines[-n:]) or "(the child printed nothing)"


class Scenario:
    """One isolated plane: temp database, seeded market, funded wallet, venue on a socket, and the executor
    run as a child process that can be killed without taking the venue with it."""

    def __init__(self, name: str, say, *, age_ms: int, ticks: int) -> None:
        self.name, self.say, self.age_ms, self.ticks = name, say, age_ms, ticks
        sys.path[:0] = [str(ROOT / "packages"), str(ROOT / "services" / "api"),
                        str(ROOT / "services" / "executor"), str(ROOT / "services" / "executor-mock"),
                        str(ROOT / "tests"), str(ROOT / "tools")]
        spec = importlib.util.spec_from_file_location("p06_gate_for_chaos", str(GATE))
        gate = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = gate
        spec.loader.exec_module(gate)
        self.p = gate.Plane()
        self.p.tight_book()
        # provision the wallet under the DEFAULT policy, because that is the policy a bare
        # `python3 services/executor/main.py` runs with. The child re-derives the live policy and refuses to
        # sign when the provisioned hash differs (POLICY_DRIFT); that refusal is right, and a harness that
        # fought it would be measuring its own fixture instead of recovery.
        self.p.fund(policy=self.p.wl.Policy())
        self.port = free_port()
        self.url = "http://127.0.0.1:%d" % self.port
        self.venue_proc = subprocess.Popen([PY, str(ROOT / "services" / "executor-mock" / "mock_clob.py"),
                                           "--host", "127.0.0.1", "--port", str(self.port)],
                                           stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
        until = time.time() + 20
        while time.time() < until:
            code, _ = http("GET", self.url + "/healthz", timeout=1.0)
            if code == 200:
                break
            time.sleep(0.1)
        else:
            raise SystemExit("%s: the venue never answered /healthz on %d" % (name, self.port))
        self.conn = self.p.store.conn
        self.say("  venue on port %d, db %s" % (self.port, Path(self.p.db).name))

    # ------------------------------------------------------------------ venue facts, read from the venue
    def snap(self) -> dict:
        code, snap = http("GET", self.url + "/v1/orders")
        if code != 200:
            raise SystemExit("%s: venue snapshot failed with %d" % (self.name, code))
        return snap

    def posts(self) -> int:
        """Every order POST the venue was asked to accept, batch or not, one entry each — the number a
        duplicate re-send would move."""
        return len(self.snap().get("requests") or [])

    def held(self, client_order_hash: str) -> int:
        """How many venue orders carry OUR deterministic hash. 0 = it never left, 1 = exactly right, 2 = the
        double-spend this whole phase exists to prevent."""
        return sum(1 for o in self.snap()["orders"].values() if o.get("client_order_hash") == client_order_hash)

    def scenario(self, name: str, **kw) -> None:
        http("POST", self.url + "/v1/scenario", {"scenario": name, **kw})

    # --------------------------------------------------------------------- our side, read from our rows
    def hash_of(self, iid: str) -> str:
        r = self.conn.execute("SELECT COALESCE(client_order_hash,'') FROM order_intents WHERE id=?",
                              (iid,)).fetchone()
        return r[0] if r else ""

    def state_of(self, iid: str) -> str:
        return self.conn.execute("SELECT state FROM order_intents WHERE id=?", (iid,)).fetchone()[0]

    def money(self, iid: str) -> dict:
        """Our three money counters for ONE intent, and the venue's trade list for the SAME order.

        The ledger is matched by venue trade id (`cash_ledger.ref_id` is the dedupe key `trade_id|side|...`),
        because "one row per venue trade" is the claim; counting all of a user's rows would let a leftover from
        another order hide a missing one here.
        """
        row = self.conn.execute("SELECT id FROM orders WHERE intent_id=?", (iid,)).fetchone()
        oid = row[0] if row else ""
        if not oid:
            return {"orders": 0, "order_id": "", "fills": 0, "ledger": 0, "trades": 0, "trade_ids": []}
        fills = self.conn.execute("SELECT COUNT(*) FROM fills WHERE order_id=?", (oid,)).fetchone()[0]
        _code, body = http("GET", "%s/v1/trades?orderID=%s" % (self.url, oid))
        trade_ids = [str(t.get("tradeID") or "") for t in (body.get("trades") or [])]
        ledger = sum(self.conn.execute("SELECT COUNT(*) FROM cash_ledger WHERE ref_table='fills' AND ref_id "
                                       "LIKE ?", ("%" + t + "%",)).fetchone()[0]
                     for t in trade_ids if t)
        return {"orders": self.conn.execute("SELECT COUNT(*) FROM orders WHERE intent_id=?", (iid,)).fetchone()[0],
                "order_id": oid, "fills": fills, "ledger": ledger, "trades": len(trade_ids),
                "trade_ids": [t[:18] for t in trade_ids]}

    def trail(self, iid: str) -> list[str]:
        return [r[0] for r in self.conn.execute(
            "SELECT state FROM order_lifecycle WHERE intent_id=? ORDER BY id", (iid,))]

    def actions(self, iid: str) -> list[str]:
        return [r[0] for r in self.conn.execute(
            "SELECT action FROM reconcile_actions WHERE intent_id=? ORDER BY id", (iid,))]

    # ----------------------------------------------------------------------------------- the child itself
    def executor(self, extra: list[str], *, stop_at: str = "") -> tuple[subprocess.Popen, Pump]:
        env = dict(os.environ)
        env["PYTHONPATH"] = os.pathsep.join([str(ROOT / "packages"), str(ROOT / "services" / "executor"),
                                            str(ROOT / "services" / "executor-mock"), str(ROOT / "tools")])
        env.pop("PGM_CRASH_AFTER", None)
        env.pop("PGM_CRASH_SIGNAL", None)
        if stop_at:
            env["PGM_CRASH_AFTER"] = stop_at
            env["PGM_CRASH_SIGNAL"] = "stop"
        proc = subprocess.Popen([PY, str(ROOT / "services" / "executor" / "main.py"), "--db", self.p.db,
                                "--venue", self.url, *extra], cwd=str(ROOT), env=env,
                                stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)
        return proc, Pump(proc.stdout)

    def kill(self, proc: subprocess.Popen) -> int:
        """The real thing. `waitpid` afterwards so a zombie is not mistaken for an executor that is still
        working."""
        t0 = time.perf_counter()
        os.kill(proc.pid, signal.SIGKILL)
        try:
            rc = proc.wait(timeout=15)
        except subprocess.TimeoutExpired:                     # pragma: no cover
            proc.kill()
            rc = proc.wait(timeout=15)
        self.say("    SIGKILL -> pid %d gone in %d ms (wait status %s); no finally block ran, nothing was "
                 "flushed on purpose" % (proc.pid, int((time.perf_counter() - t0) * 1000), rc))
        return rc

    def age(self, iid: str) -> None:
        """Represent the outage to the database: the crash happened `age_ms` ago, which is what makes the 45 s
        claim lease and the 10 s no-ack grace elapse without the harness sitting there for a minute."""
        self.conn.execute("UPDATE order_intents SET updated_ms=updated_ms-? WHERE id=?", (self.age_ms, iid))
        self.conn.execute("UPDATE orders SET updated_ms=updated_ms-? WHERE intent_id=?", (self.age_ms, iid))
        self.conn.commit()
        self.say("    the outage is %d ms of DB clock (claim lease 45 s, no-ack grace 10 s)" % self.age_ms)

    def recover(self) -> str:
        proc, pump = self.executor(["--ticks", str(self.ticks), "--interval-ms", "120"])
        try:
            proc.wait(timeout=180)
        except subprocess.TimeoutExpired:                     # pragma: no cover
            self.kill(proc)
        return pump.tail()

    def close(self) -> None:
        try:
            self.venue_proc.terminate()
            self.venue_proc.wait(timeout=5)
        except Exception:                                     # noqa: BLE001 - cleanup only
            pass
        self.p.close()


# ======================================================================================== the scenarios ==
def s1_signed_then_killed(sc: Scenario, res: list) -> None:
    sc.say("S1  signed, then killed before the POST")
    iid = sc.p.queue(key="chaos-s1", price=500_000, size=10 * 10**6)
    proc, pump = sc.executor(["--ticks", "40", "--interval-ms", "40"], stop_at="signed")
    hit = pump.wait_for("halted-after=signed", timeout=60)
    sc.say("    child said: %s" % (hit or "NOTHING — it never reached the stage"))
    h = sc.hash_of(iid)
    sc.say("    at the instant of the kill: intent=%s, hash stamped=%s, venue holds %d order(s) for it, "
           "POSTs=%d" % (sc.state_of(iid), bool(h), sc.held(h), sc.posts()))
    res.append(("S1a a signature exists, the venue has nothing, and the hash is on the intent",
                bool(hit) and not sc.held(h) and bool(h) and sc.state_of(iid) in
                ("submitting", "signed", "unknown", "uncertain"),
                "intent %s, lifecycle %s, hash stamped before the wire so any later process can ask about it"
                % (sc.state_of(iid), sc.trail(iid)[-3:])))
    sc.kill(proc)
    sc.age(iid)
    before = sc.posts()
    sc.recover()
    held, posts, money = sc.held(h), sc.posts(), sc.money(iid)
    sc.say("    after recovery: venue orders created: %d, POSTs %d -> %d, our rows %s, intent=%s"
           % (held, before, posts, {k: v for k, v in money.items() if k != "order_id"}, sc.state_of(iid)))
    res.append(("S1b recovery POSTs exactly one venue order and only once",
                held == 1 and posts - before == 1 and money["orders"] == 1,
                "orders created: %d (the venue's own count, not ours); POST count moved %d -> %d; our order "
                "rows %d; final intent %s" % (held, before, posts, money["orders"], sc.state_of(iid))))
    sc.say("    exactly one venue order after a crash between signing and submitting: %s"
           % ("yes" if held == 1 else "NO — %d" % held))


def s2_killed_inside_the_post(sc: Scenario, res: list) -> None:
    sc.say("S2  killed inside the POST: the venue accepted, the answer never arrived")
    iid = sc.p.queue(key="chaos-s2", price=500_000, size=8 * 10**6)
    sc.scenario("timeout_after_accept", delay_ms=6_000)
    proc, pump = sc.executor(["--once"])
    time.sleep(1.4)                                        # the child is parked inside the 6 s request
    h = sc.hash_of(iid)
    held, posts = sc.held(h), sc.posts()
    sc.say("    at the instant of the kill: venue holds %d order(s) for our hash (POSTs=%d), intent=%s"
           % (held, posts, sc.state_of(iid)))
    sc.kill(proc)
    res.append(("S2a the venue really did take the order while we were dying", held == 1,
                 "accepted-and-unacknowledged at the venue; our side has the attempt row and a stamped hash, "
                 "which is the only reason the next process can find it"))
    sc.scenario("accept")
    sc.age(iid)
    before = sc.posts()
    sc.recover()
    held, money, acts = sc.held(h), sc.money(iid), sc.actions(iid)
    posts = sc.posts()
    sc.say("    after recovery: venue orders created: %d, POSTs %d -> %d, our rows %s, intent=%s"
           % (held, before, posts, {k: v for k, v in money.items() if k != "order_id"}, sc.state_of(iid)))
    sc.say("    reconcile actions on this intent: %s" % (acts or "none"))
    ok = bool(held == 1 and posts == before and money["orders"] == 1
              and sc.state_of(iid) in ("submitted", "live", "partial"))
    res.append(("S2b recovery adopts the venue's order and re-POSTs nothing", ok,
                "orders created: 1 by adoption, not by a second send; POST count stayed %d; our order row %d "
                "created by the reconciler's adopt path; actions %s; final intent %s"
                % (posts, money["orders"], acts or "none", sc.state_of(iid))))
    sc.say("    reconciled by client_order_hash, exactly one venue order, zero duplicate POSTs: %s"
           % ("yes" if ok else "NO"))


def s2b_the_queue_hands_it_back(sc: Scenario, res: list) -> None:
    sc.say("S2b the same intent, pushed back onto the queue as a stale lease would")
    iid = sc.p.queue(key="chaos-s2b", price=500_000, size=5 * 10**6)
    sc.scenario("timeout_after_accept")
    proc, pump = sc.executor(["--once"])
    proc.wait(timeout=90)
    h = sc.hash_of(iid)
    held_now = sc.held(h)
    sc.say("    the POST timed out (no answer); venue holds %d order(s) for the hash, intent=%s"
           % (held_now, sc.state_of(iid)))
    sc.conn.execute("UPDATE order_intents SET state='queued', updated_ms=updated_ms-? WHERE id=?",
                    (sc.age_ms, iid))
    sc.conn.commit()
    before = sc.posts()
    sc.say("    now the queue is handed the same intent back — the requeue-after-crash path, where a naive "
           "executor re-sends and the user pays twice")
    sc.recover()
    posts, held, state = sc.posts(), sc.held(h), sc.state_of(iid)
    sc.say("    after that pass: POSTs %d -> %d, venue orders created: %d, intent=%s"
           % (before, posts, held, state))
    res.append(("S2c an intent the venue already holds is never sent a second time",
                posts == before and held == 1 and state in ("uncertain", "submitted", "live"),
                "the attempt row says 'we may have sent this' and the venue's answer says whether we did; on "
                "'yes' the executor does nothing and reconciliation adopts (POSTs stayed %d, venue holds %d, "
                "intent %s)" % (posts, held, state)))


def s3_killed_with_a_fill_in_hand(sc: Scenario, res: list) -> None:
    sc.say("S3  killed after a venue fill was booked, before the pass finished")
    iid = sc.p.queue(key="chaos-s3", price=500_000, size=20 * 10**6)
    sc.scenario("partial_fill")
    proc, pump = sc.executor(["--ticks", "60", "--interval-ms", "60"], stop_at="booked")
    hit = pump.wait_for("halted-after=booked", timeout=60)
    money = sc.money(iid)
    sc.say("    child said: %s" % (hit or "NOTHING — it never reached the money line"))
    sc.say("    at the kill: our fills=%d, ledger rows=%d, venue trades=%d (%s)"
           % (money["fills"], money["ledger"], money["trades"], money["trade_ids"]))
    res.append(("S3a the kill landed on the money line", bool(hit) and money["fills"] >= 1,
                 "the reconciler books inside `book_fill`, the hook fires the instant it returns, and the "
                 "process is stopped there: fills %d, ledger %d" % (money["fills"], money["ledger"])))
    sc.kill(proc)
    sc.age(iid)
    sc.recover()
    after = sc.money(iid)
    sc.say("    after recovery: our fills=%d, ledger rows=%d, venue trades=%d (%s), intent=%s"
           % (after["fills"], after["ledger"], after["trades"], after["trade_ids"], sc.state_of(iid)))
    res.append(("S3b the same venue trade is booked exactly once, ever",
                after["fills"] == after["ledger"] == after["trades"] >= 1,
                "venue trades %d, our fills %d, cash_ledger rows %d: `book_fill` is the only door and it is "
                "idempotent on the venue trade id, so a restarted pass re-reads and adds nothing"
                % (after["trades"], after["fills"], after["ledger"])))


def main() -> int:
    ap = argparse.ArgumentParser(description="P06 mid-flight chaos: SIGKILL the executor, count the venue")
    ap.add_argument("--record", default="", help="write the transcript here (the phase gate reads this file)")
    ap.add_argument("--age-ms", type=int, default=60_000,
                    help="how long the outage is simulated to have lasted, in DB clock terms (lease is 45 s)")
    ap.add_argument("--ticks", type=int, default=6, help="ticks to run after each restart")
    ap.add_argument("--only", default="", help="run only the scenarios whose name contains this")
    a = ap.parse_args()
    say = Out(Path(a.record) if a.record else None)
    res: list[tuple[str, bool, str]] = []
    say("P06 mid-flight chaos — four scenarios, each with its own database and venue process")
    say("")
    runners = [("s1", s1_signed_then_killed), ("s2", s2_killed_inside_the_post),
               ("s2b", s2b_the_queue_hands_it_back), ("s3", s3_killed_with_a_fill_in_hand)]
    for name, fn in runners:
        if a.only and a.only not in name:
            continue
        sc = Scenario(name, say, age_ms=a.age_ms, ticks=a.ticks)
        try:
            fn(sc, res)
        finally:
            sc.close()
        say("")
    say("chaos test — %s" % time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()))
    passed = 0
    for label, ok, detail in res:
        passed += 1 if ok else 0
        say("  [%s] %s" % ("PASS" if ok else "FAIL", label))
        say("        %s" % detail)
    say("")
    say("%d/%d chaos assertions passed (outage %d ms, %d recovery ticks per scenario)"
        % (passed, len(res), a.age_ms, a.ticks))
    verdict = "PASS" if res and passed == len(res) else "FAIL"
    say("CHAOS RESULT: %s — mid-flight recovery demonstrated against a real SIGKILL" % verdict)
    if a.record:
        say.save()
        print("recorded: %s" % a.record, flush=True)
    return 0 if verdict == "PASS" else 1


if __name__ == "__main__":
    sys.exit(main())
