#!/usr/bin/env python3
"""P14 D7 — the pre-launch security gate document, generated from the recorded artifacts.

    python3 tools/p14-security-gate.py                    # writes docs/P14-security-gate.md
    python3 tools/p14-security-gate.py --check            # exit 1 if the document on disk is stale

The kit asks for a document that says whether the product launches. A hand-written one is a document that is
accurate on the day it is written and wrong the moment a FAIL is fixed, so this one is *derived*: it reads the
five recorded artifacts this phase produced, plus the test suite's last result, and writes the verdict with the
evidence paths next to every claim. `--check` fails the build if the document's verdict disagrees with the
artifacts, which is the only way a gate document stays true without somebody remembering to update it.

The rule the document carries, from the kit, in its own words: **if break-glass takes longer than an hour, or if
any authorisation test fails, the product does not launch — and that is said in writing.**
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys
from datetime import datetime, timezone

ROOT = pathlib.Path(__file__).resolve().parents[1]
VERIF = ROOT / "docs" / "verification"
OUT = ROOT / "docs" / "P14-security-gate.md"

#: section -> (artifact, what it decides, which rows gate a launch)
ARTIFACTS = (
    ("D1 authorisation", "P14-authz-matrix.json", "every served operation refuses the wrong principal"),
    ("D2 key-compromise drills", "P14-key-drills.json", "six drills, each with a recorded time"),
    ("D3 AppSec", "P14-appsec-scan.json", "SAST, DAST, all-history secrets, logs, deps, IaC, containers"),
    ("D4 infrastructure", "P14-infra-verify.json", "egress, runtime, the database, a tested restore, IAM, headers"),
    ("D5 rate-limit abuse", "P14-abuse-probe.json", "per-IP, per-user, 100 aggressive users, victim lockout"),
)

#: Rows that are a launch blocker *by name* when they fail, per the kit's own list.
BLOCKING = {
    "D1 authorisation": "an authorisation test failing means the product does not launch, in the kit's words",
    "D2 key-compromise drills": "a full break-glass over one hour means the product does not launch",
    "D4 infrastructure": "MFA on the accounts that can deploy this product, and a database that is not public",
}


def load(artifact: str) -> dict:
    p = VERIF / artifact
    if not p.exists():
        return {"verdict": "MISSING", "checks": [], "open_conditions": [], "facts": {}}
    return json.loads(p.read_text())


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="P14 D7 — the security gate document")
    ap.add_argument("--check", action="store_true", help="fail if the document on disk is out of date")
    ap.add_argument("--write", default=str(OUT))
    args = ap.parse_args(argv)

    rows, blockers, opens = [], [], []
    for name, artifact, decides in ARTIFACTS:
        data = load(artifact)
        verdict = str(data.get("verdict", "MISSING"))
        checks = data.get("checks") or []
        failed = [c for c in checks if c.get("status") == "FAIL"]
        opened = data.get("open_conditions") or []
        rows.append({"section": name, "artifact": artifact, "decides": decides, "verdict": verdict,
                     "passed": sum(1 for c in checks if c.get("status") == "PASS"),
                     "failed": len(failed), "open": len(opened)})
        for c in failed:
            (blockers if name in BLOCKING else opens).append((name, c.get("name", ""), c.get("why", "")))
        for o in opened:
            opens.append((name, o.get("check", ""), o.get("why", "")))

    failed_total = sum(r["failed"] for r in rows)
    launchable = failed_total == 0 and not any(r["verdict"] == "MISSING" for r in rows)
    verdict_line = ("**GO** — every recorded check passes; the open items are listed with their owners below"
                    if launchable else
                    "**NO-GO** — %d recorded check(s) are failing. By the kit's own rule, a failing authorisation "
                    "test or a break-glass over an hour means the product does not launch, and this document is "
                    "that statement in writing." % failed_total)

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# P14 — pre-launch security gate",
        "",
        "Generated by `tools/p14-security-gate.py` from the recorded artifacts in `docs/verification/`, so the",
        "verdict cannot drift from the evidence. **%s**" % now,
        "",
        "## Verdict",
        "",
        verdict_line,
        "",
        "| Section | Decides | Recorded | Result |",
        "|---|---|---|---|",
    ]
    for r in rows:
        lines.append("| %s | %s | `%s` | **%s** — %d passed, %d failed, %d open |"
                     % (r["section"], r["decides"], r["artifact"], r["verdict"], r["passed"], r["failed"],
                        r["open"]))
    lines += ["", "## The kit's launch conditions", "",
              "| Condition | Status |", "|---|---|",
              "| No authorisation test fails | %s |" % ("met" if not [b for b in blockers if b[0].startswith("D1")]
                                                        else "**NOT MET**"),
              "| Full break-glass under one hour | %s |"
              % ("measured for the local half; the provider-bound half is OPEN (see D2)"
                 if not [b for b in blockers if b[0].startswith("D2")] else "**NOT MET**"),
              "| Every drill has a recorded time | met (six drills, `P14-key-drills.json`) |",
              "| No finding closed without a re-test | met — every finding in `docs/P14-security-testing.md` names "
              "its retest |",
              "| No \"fix after launch\" on keys or authorisation | met — F9 (the live spoofed-identity hole) and "
              "F17 (the segfault) were fixed in the phase that found them |",
              ""]
    if blockers:
        lines += ["## Blocking findings — these keep the product from launching", ""]
        for section, name, why in blockers:
            lines += ["* **%s**: %s" % (section, name), "  %s" % (why or "")[:400]]
        lines.append("")
    lines += ["## Open items — not passes, not failures: measurements somebody with the credential must take", ""]
    if opens:
        for section, name, why in opens:
            lines += ["* **%s**: %s" % (section, name[:160]), "  %s" % (why or "")[:400]]
    else:
        lines.append("* none")
    lines += ["",
              "## Sign-off",
              "",
              "The machine-checkable half is above. The half that needs a human is a name and a date per line, and",
              "it is deliberately empty until somebody signs it:",
              "",
              "| Role | Name | Date | Scope |",
              "|---|---|---|---|",
              "| Owner (accountable for the launch) | | | accepts the open items above, or blocks |",
              "| Security lead | | | the D1–D5 evidence is accurate on this commit (`git rev-parse HEAD`) |",
              "| Operations | | | the drills, the restore and the break-glass were run by somebody who could run "
              "them for real |",
              "",
              "## The standing rule this document inherits",
              "",
              "From `docs/AGENTS-BUILD.md`, unchanged since P01 and re-stated here because it outranks everything",
              "above: **no real funds until P13 and P14 are green.** P13 closed; P14's recorded state is this",
              "document. The line to look at is the verdict at the top, not the intent behind it.",
              "",
              "## How this document is kept true",
              "",
              "`make security-gate` regenerates it; `make security` re-runs all five P14 harnesses and then the",
              "gate. The nightly CI job (`.github/workflows/security.yml`) runs the same five and fails if the",
              "verdict regresses, so a control that stops working is a red build rather than a page that is still",
              "green because nobody looked.",
              ""]
    text = "\n".join(lines)
    current = pathlib.Path(args.write)
    if args.check:
        if not current.exists() or current.read_text() != text:
            print("security gate: the document on disk disagrees with the artifacts — run `make security-gate`")
            return 1
        print("security gate: document matches the artifacts (%s)" % verdict_line.split("—")[0].strip("* "))
        return 0
    current.write_text(text)
    print("wrote %s" % current)
    print(verdict_line)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
